### ISSUE TITLE
py3 distribution not available in aiobotocore V2.1.2

### ISSUE THREAD

**Issue by semyonestrin** [aio-libs/aiobotocore#1000]
**Describe the bug**
- Kind request to create `py3` distribution package for [aiotobotocore V2.1.2](https://pypi.org/project/aiobotocore/2.1.2/#files)
- We are using `pipenv install` with `--platform` flag in order to work with the above lib on top of [AWS Lambda Runtime dependency](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)
- The above method is not able to find the package because it is not built for `python`.
- Screenshot with error description can be found below (when working with `--platform manylinux2014_x86_64`)
<img width="2429" alt="image" src="https://user-images.githubusercontent.com/16302201/222961687-9abdfde3-3d2d-467d-93d0-2614885c3730.png">

**Checklist**
- [ ] I have reproduced in an environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**Comment by thehesiod** [comment]
I'm not sure what you mean it's not built for python, these are the classifiers it has in setup.py for that version:
```
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Environment :: Web Environment',
    'Development Status :: 4 - Beta',
    'Framework :: AsyncIO',
```
on top of that, tar.gz means raw source any platform.

**Comment by semyonestrin** [comment]
Many thanks for the prompt reply. 

In later versions there is downloadable `.whl` file built especially for `py3`, but not in 2.1.2. 

I was wondering if it’s possible to publish such for 2.1.2. 

![9B554078-7198-49EF-81D8-6E1404BB277B](https://user-images.githubusercontent.com/16302201/223627573-54c9468d-6427-46c7-96a5-65500bb630dc.jpeg)

**Comment by thehesiod** [comment]
ah ok to add a wheel.  Ya will do

**Comment by thehesiod** [comment]
added
