### ISSUE TITLE
Invalid link in httpsession.py comment

### ISSUE THREAD

**Issue by vEpiphyte** [aio-libs/aiobotocore#1012]
**Describe the bug**
The link to an AWS forum post here https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/httpsession.py#L82 is no longer valid.

The url below links to a forum that is no longer available.
 ```
https://forums.aws.amazon.com/message.jspa?messageID=215367
```

An archived version of this can be found on archive.org

https://web.archive.org/web/20150926192339/https://forums.aws.amazon.com/message.jspa?messageID=215367

**Checklist**
N/A

**Environment:**
 - Web browser

**Comment by thehesiod** [comment]
thanks
