### ISSUE TITLE
aiobotocore has no session error

### ISSUE THREAD

**Issue by nvenkat94** [aio-libs/aiobotocore#1013]
`profile_session=aiobotocore.session.AioSession(profile=profile_name)`

The above snippet doesn't work with after build script as application(.exe). But that snippet works well locally. We facing issues after building that script. That error is aiobotocore has no session attribute.

How to fix this issue? We using above snippet with `s3fs` module for getting sso profile details.

**Comment by thehesiod** [comment]
I don't understand this bug.  What's the full code to repro?

**Comment by alanwong626** [comment]
If you are referring to this error: `AttributeError: module 'aiobotocore' has no attribute 'session'`

Try to do:
`import aiobotocore.session`, instead of  `import aiobotocore`.

**Comment by thehesiod** [comment]
going to close, no reproducible use case and I think it's user error
