### ISSUE TITLE
upgrade botocore to 1.29.98

### ISSUE THREAD

**Issue by igoichuk** [aio-libs/aiobotocore#1014]
botocore 1.29.98 has `ephemeralStorage` support for FARGATE Batch compute:
[https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#L440](https://github.com/boto/boto3/blob/develop/CHANGELOG.rst#L440)

Please upgrade when you have a chance.

**Comment by baggiponte** [comment]
As a reference, [here](https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore)'s the guide to update botocore for aiobotocore. Can't say when I will have time to look into that/

**Comment by thehesiod** [comment]
yep! super easy PR then.  Perhaps we can add an auto upgrader action that can propose PRs if there are only json changes

**Comment by baggiponte** [comment]
> yep! super easy PR then.  Perhaps we can add an auto upgrader action that can propose PRs if there are only json changes

So just to be clear: if the only change between botocore versions are just json files (outside of the .py files that contain the version specifier), nothing has to change in aiobotocore?

If that is the case, I can take care of upgrading the botocore dependency as much as I can

**Comment by baggiponte** [comment]
For completeness, some developments about this can also be found in #1017

**Comment by sachinrautixn** [comment]
Please upgrade `botocore` to v1.29.165

**Comment by thehesiod** [comment]
done
