### ISSUE TITLE
datetime.utcnow is deprecated in Python 3.12

### ISSUE THREAD

**Issue by tirkarthi** [aio-libs/aiobotocore#1021]
https://github.com/aio-libs/aiobotocore/blob/5ce00b8bb351192e32af7fcbe396aada31fa9b74/aiobotocore/signers.py#L262

Ref : https://github.com/python/cpython/issues/103857

> [datetime.datetime](https://docs.python.org/3.12/library/datetime.html#datetime.datetime)’s [utcnow()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcnow) and [utcfromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.utcfromtimestamp) are deprecated and will be removed in a future version. Instead, use timezone-aware objects to represent datetimes in UTC: respectively, call [now()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.now) and [fromtimestamp()](https://docs.python.org/3.12/library/datetime.html#datetime.datetime.fromtimestamp) with the tz parameter set to [datetime.UTC](https://docs.python.org/3.12/library/datetime.html#datetime.UTC). (Contributed by Paul Ganssle in [gh-103857](https://github.com/python/cpython/issues/103857).)

**Comment by thehesiod** [comment]
that comes from botocore: https://github.com/boto/botocore/blob/1.29.161/botocore/signers.py#L593 please log there

**Comment by thehesiod** [comment]
btw, didn't follow the instructions in logging an issue :)

**Comment by tirkarthi** [comment]
Sorry, I right clicked on the code line in GitHub UI and selected reference in new issue which seems to not show any template. I will check on the other repo. Thanks.

**Comment by thehesiod** [comment]
interesting, sounds like a github bug, here's the template btw: https://github.com/aio-libs/aiobotocore/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

**Comment by phillipuniverse** [comment]
To make this slightly easier to find via Google, this is the Deprecation warning raised on Python 3.12:

```
    def add_auth(self, request):
        if self.credentials is None:
            raise NoCredentialsError()
>       datetime_now = datetime.datetime.utcnow()
E       DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
```

Tracked in botocore at https://github.com/boto/botocore/issues/3088 which references a still-open issue at https://github.com/boto/boto3/issues/3889.

In my case with pytest, fix is:

```toml
[tool.pytest.ini_options]
filterwarnings = [
    "error", # treat all warnings as errors
    "ignore:datetime.datetime.utcnow\\(\\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning",
]
```
