### ISSUE TITLE
aiobotocore 2.6.0 not on conda-forge

### ISSUE THREAD

**Issue by martindurant** [aio-libs/aiobotocore#1036]
2.6.0 was released a few weeks ago on pypi, but conda-forge failed to built is even though https://github.com/conda-forge/aiobotocore-feedstock/pull/67 was green and merged. Raising here for more visibility.

**Comment by martindurant** [comment]
https://github.com/conda-forge/aiobotocore-feedstock/issues/68

**Comment by thehesiod** [comment]
looks like it succeeded, given this isn't an aiobotocore issue shouldn't be opened here anyways
