### ISSUE TITLE
add  CONTRIBUTING.rst file to the root directory

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#104]
We need to provide `CONTRIBUTING.rst` file with dev instruction to this repo.

Similar to: https://github.com/aio-libs/aiomonitor/blob/master/CONTRIBUTING.rst

**Comment by thehesiod** [comment]
probably should morph https://github.com/aio-libs/aiobotocore/blob/master/BOTOCORE_README.rst into this new file

**Comment by jettify** [comment]
Good point, github shows link to `CONTRIBUTING.rst` in PR if this file present. So file should contain basic stuff like create environment, running tests and content of `BOTOCORE_README.rst`

**Comment by jettify** [comment]
also we can add PR template like https://github.com/KeepSafe/aiohttp/blob/master/PULL_REQUEST_TEMPLATE.md
