### ISSUE TITLE
Instructions for running tests in README.rst are outdated

### ISSUE THREAD

**Issue by jakkdl** [aio-libs/aiobotocore#1040]
**Describe the bug**
Trying to follow the instructions in README.rst for running tests was .. not very helpful, and it ended up being easier to read [python-package.yml](https://github.com/aio-libs/aiobotocore/blob/master/.github/workflows/python-package.yml). So here's some suggestions for fixing stuff that tripped me up

```
    $ cd aiobotocore
    $ export AWS_ACCESS_KEY_ID=xxx
    $ export AWS_SECRET_ACCESS_KEY=xxx
    $ pip-sync requirements-dev.txt
```

1. This seems to assume that you start in a directory above the actual repo root (??), or it wants you to go into the https://github.com/aio-libs/aiobotocore/tree/master/aiobotocore directory (???). I think the first line should be removed entirely.
2. `requirements-dev.txt` does not exist, unless you first run `pip install pip-tools; pip-compile requirements-dev.in`. So a line with this should probably be added.

```
    $ pytest -v tests
```

1. When giving examples I think it's good manner to use the long form of flags to be maximally helpful, so imo this should be `pytest --verbose tests` to be extra clear that it's not a required flag.

**Comment by thehesiod** [comment]
yea, the docs are all probably outdated.  the regular tests don't require aws credentials because they use moto. The non moto tests are those not supported by moto that need to be run with someone's personal AWS creds
