### ISSUE TITLE
Bump botocore to latest version

### ISSUE THREAD

**Issue by andrii-i** [aio-libs/aiobotocore#1043]
**Describe the bug**

aiobotocore dependency on botocore 1.31.17 causes dependency conflict with packages that depend on newer version of botocore. For example, because of this latest versions of s3fs and boto3 conflict.

**Additional context**

Opened PR #1042 bumping to address this

**Comment by JackKolb-ElationHealth** [comment]
Will this update the list of services to include `bedrock-runtime` added in `1.28.57`? I'd really like AIO support for Amazon bedrock, and if we're bump dep versions it would be nice to get 2 for the price of 1. Sorry for hijacking this PR.
