### ISSUE TITLE
Support botocore 1.32.1 with its massive decrease in package size

### ISSUE THREAD

**Issue by huonw** [aio-libs/aiobotocore#1056]
**Describe the bug**

The 1.32.1 release of botocore comes with a massive decrease (like 25% of the size it used to be, ~60MB smaller) in installed package size, which is great for decreasing the sizes of packages (e.g. lambdas): https://github.com/boto/botocore/issues/2365#issuecomment-1813447304

```python
pip install --no-deps botocore==1.32.1 --target /tmp/botocore-1.32.1
pip install --no-deps botocore==1.31.85 --target /tmp/botocore-1.31.85

du -sh /tmp/botocore-*
#  83M	/tmp/botocore-1.31.85
#  20M	/tmp/botocore-1.32.1
```

Currently aiobotocore supports up to botocore==1.31.64 with support for 1.31.70 pending in #1048.

The changes from #1048 to 1.32.1 seem to touch quite a few Python files in addition to the service JSON bumps. https://github.com/boto/botocore/compare/1.31.70...1.32.1

**Checklist**
N/A

**pip freeze results**
N/A

**Environment:**
N/A

**Additional context**

Thanks for aiobotocore! 

I get the impression that botocore upgrades are generally done "whenever", but this particular one seems so impactful that I'd like to have a place to track (this issue) so I can get a notification if/when we can upgrade. Thanks!

**Comment by jakob-keller** [comment]
Interesting! I will take a look and report back in a few days.

**Comment by thehesiod** [comment]
hah, as I thought, they just compressed all the service jsons:
https://github.com/boto/botocore/blob/develop/CHANGELOG.rst#1321

**Comment by jakob-keller** [comment]
> Interesting! I will take a look and report back in a few days.

The upgrade might get a bit more involved than the previous bumps, but it sure looks doable. I might be able to prepare a PR this weekend.
