### ISSUE TITLE
drop aiobotocore prefix from releases

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#1058]

**Comment by thehesiod** [comment]
@jakob-keller @terrycain @jettify any issues you guys can think of?

**Comment by jakob-keller** [comment]
Sure, it seems like other projects typically release without the prefix. 👍🏻

**Comment by terrycain** [comment]
Should be fine, go for it 👍🏻

**Comment by thehesiod** [comment]
done! :)
