### ISSUE TITLE
Support botocore>=1.33.2

### ISSUE THREAD

**Issue by hammer** [aio-libs/aiobotocore#1065]
Creating an issue to track the implementation mentioned in https://github.com/aio-libs/aiobotocore/pull/1057#issuecomment-1830899886.

In particular, we are eager to try out S3 Express One Zone!

**Comment by thehesiod** [comment]
I think you meant https://github.com/aio-libs/aiobotocore/pull/1063 ?

**Comment by hammer** [comment]
Ah my apologies I only saw #1057 and did not realize a PR had already been created for the additional work, thanks!
