### ISSUE TITLE
2.10.0 release failed

### ISSUE THREAD

**Issue by adebrecht661** [aio-libs/aiobotocore#1076]
Attempting to install aiobotocore 2.10.0 from PyPI fails.

The latest version on PyPI is still 2.9.1. Appears to me like the CD failed. Since that was almost 12 hours ago, figured I'd raise an issue to be sure someone was aware.

**Comment by jakob-keller** [comment]
Thanks for reporting. I believe the cause is a mismatch between two GitHub actions. Merging #1068 should fix this.
