### ISSUE TITLE
Support `botocore==1.34.27`

### ISSUE THREAD

**Issue by jakob-keller** [aio-libs/aiobotocore#1078]
Hi @jakob-keller @thehesiod, I'm an open-source developer and sorry, but I'm finding this PR late. Is there a reason you can't support at least version 1.34.27? Or better, anything <1.35.0?

    If you look at botocore's [release history](https://pypi.org/project/botocore/#history), they've made multiple releases in the last few days. I maintain a software environment for the Python in Heliophysics Community (PyHC), and out of hundreds of packages, `aiobotocore`'s strict requirement of botocore<1.34.23 is the one thing breaking our build.

_Originally posted by @sapols in https://github.com/aio-libs/aiobotocore/issues/1069#issuecomment-1910520358_

**Comment by jakob-keller** [comment]
I've created #1079 to support `botocore==1.34.27`.  As soon as a collaborator is able to review the PR and trigger a release, it will be made available on PyPI.

@sapols: Can you share details about what breaks your build? Having `aiobotocore` as a requirement should not generally be a cause for any CI issues. We might be able to figure this out.

**Comment by sapols** [comment]
Thanks @jakob-keller! I appreciate the PR and the offer for help. I understand my issue though, and it's not entirely `aiobotocore`'s fault; we purposefully include a package in our environment that requires `botocore>=1.34.27`. Our build succeeds if we don't include that package, but obviously the preferable solution for us was just for you guys to bump your `botocore` requirement one more time. You merged your other `botocore` PR just last week with the intent of pinning to the latest version, and I assume you didn't expect that to get out-of-date so fast. So hopefully this is something you would've done anyway and I just sped you up a little?
