### ISSUE TITLE
Bump botocore to at least 1.34.40

### ISSUE THREAD

**Issue by Cole-Greer** [aio-libs/aiobotocore#1090]
Hi I was hoping to use a new feature which was first included in botocore 1.34.40. Is it possible to bump the allowed version to that or higher?

Thanks

**Comment by jakob-keller** [comment]
Thanks for your request. I will look into it and prepare a PR.

**Comment by Cole-Greer** [comment]
@jakob-keller Thanks for the quick response. Your help is greatly appreciated

**Comment by Cole-Greer** [comment]
@jakob-keller Thanks for all your efforts to push this update quickly. I'm currently planning some work which is dependent on this upgrade, I'm wondering if you may be able to provide a rough estimate on when this change might be reviewed, merged, and released. Thanks again for all your help!

**Comment by jakob-keller** [comment]
> @jakob-keller Thanks for all your efforts to push this update quickly. I'm currently planning some work which is dependent on this upgrade, I'm wondering if you may be able to provide a rough estimate on when this change might be reviewed, merged, and released. Thanks again for all your help!

@thehesiod: Any chance we can do a quick release?

**Comment by thehesiod** [comment]
yep, sorry again for not being as available, I expect to be busy for another week until I have our place squared away (so sore from so much painting!)
