### ISSUE TITLE
Instance of `StreamingBody` returns `True` for `isinstance` `Iterable` check

### ISSUE THREAD

**Issue by FeeeeK** [aio-libs/aiobotocore#1098]
**Describe the bug**
`StreamingBody` returns `True` for `isinstance` `Iterable` check when it shouldn't, this can lead to some problems, for example, wrong content encoding in httpx ([link](https://github.com/encode/httpx/blob/7df47ce4d93a06f2c3310cd692b4c2336d7663ba/httpx/_content.py#L184-L216)) and inability to use `StreamingBody` as `content` in `httpx.AsyncClient`
```py
> isinstance(StreamingBody, Iterable)
False
> isinstance(StreamingBody, AsyncIterable)
False
> isinstance(StreamingBody(b"", 0), Iterable)
True
> isinstance(StreamingBody(b"", 0), AsyncIterable)
True
> StreamingBody(b"", 0).__iter__
<method-wrapper '__iter__' of StreamingBody object at 0x0000021D9F2B93C0>
> StreamingBody(b"", 0).__aiter__
<bound method StreamingBody.__aiter__ of <StreamingBody at 0x0000021D9FC6AC40 for bytes at 0x00007FF96586D328>>
> for _ in streaming_body: pass
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'ClientResponse' object is not iterable
```

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [x] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [x] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**
```
...
aioboto3==11.3.1
aiobotocore==2.6.0
aiohttp==3.9.3
boto3==1.28.17
botocore==1.31.17
...
```

**Environment:**
 - Python Version: 3.11.8
 - OS name and version: windows

**Additional context**

**Comment by jakob-keller** [comment]
Hello and thanks for reporting!

I believe you are correct: `StreamingBody` is indeed not iterable. The false positive `isinstance` check appears to be due to having `wrapt.ObjectProxy` as a parent class.

There might be several ways to deal with this issue:
1. Make `wrapt.ObjectProxy` play nicely with isinstance checks by addressing the issue upstream
2. Tweak `StreamingBody` to ensure isinstance check returns expected result (if possible)
3. Drop `wrapt.ObjectProxy` as a parent class
4. Leave StreamingBody as it is and work around the issue in downstream code

@thehesiod: Any thoughts?

**Comment by FeeeeK** [comment]
Looks like this issue is already 8 years old: https://github.com/GrahamDumpleton/wrapt/issues/93 so it seems to me that option 3 would most likely be the solution

**Comment by jakob-keller** [comment]
> Looks like this issue is already 8 years old: [GrahamDumpleton/wrapt#93](https://github.com/GrahamDumpleton/wrapt/issues/93) so it seems to me that option 3 would most likely be the solution

That's what I feared

**Comment by thehesiod** [comment]
nice detective work. we can drop the proxy, just means we'll have to be
more careful when upgrading

**Comment by thehesiod** [comment]
ping so it doesn't close
