### ISSUE TITLE
Switch CI/CD to PyPI trusted publishing

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aiobotocore#1116]
Just got a warning from PyPI:
![Screenshot_2024-05-16-16-17-11-73_e307a3f9df9f380ebaf106e1dc980bb6](https://github.com/aio-libs/aiobotocore/assets/578543/a83b7ef8-1fda-4809-9dd9-6852bb14e058)

To fix this, GHA should be configured similarly to aiomonitor.

**Comment by thehesiod** [comment]
might as well update the coverage section as well
