### ISSUE TITLE
Release aiobotocore 0.2.0

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#112]
We have nice changes already, I belive we can release new version to PyPI

**Comment by thehesiod** [comment]
https://github.com/aio-libs/aiobotocore/releases/tag/0.2.0
bumped to dev ver: https://github.com/aio-libs/aiobotocore/pull/114

**Comment by jettify** [comment]
Good practice also to post release updates here https://groups.google.com/forum/#!forum/aio-libs for example something like https://groups.google.com/forum/#!topic/aio-libs/QDo_Ccfzjas I always forget to do this :)
