### ISSUE TITLE
Support Bedrock Converse by bumping `botocore` and `boto3`

### ISSUE THREAD

**Issue by AndreCNF** [aio-libs/aiobotocore#1123]
The new [AWS Bedrock Converse API](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html) became available in `botocore` and `boto3` version `1.34.116`, yet `aiobotocore` currently restricts `botocore` and `boto3` to `<1.34.107`.

I'd like this update to happen so as to address [this issue in aioboto3](https://github.com/terricain/aioboto3/issues/341) and [this PR in LlamaIndex](https://github.com/run-llama/llama_index/pull/14326).

**Comment by lou-k** [comment]
The converse api is actually why I opened https://github.com/aio-libs/aiobotocore/pull/1122!

**Comment by wzjin2017** [comment]
Same issue here. I can force install latest `boto3` after `aiobotocore` but this does not feel ideal...
