### ISSUE TITLE
Will 2.13.2 Be Available Through PyPI?

### ISSUE THREAD

**Issue by jamesonwilliams** [aio-libs/aiobotocore#1130]
Hi, there!

I see that version [2.13.2](https://github.com/aio-libs/aiobotocore/releases/tag/2.13.2) is released, but I'm not able to install it in my project:

```console
$ pip3 install aiobotocore==2.13.2
ERROR: Could not find a version that satisfies the requirement aiobotocore==2.13.2 (from versions: 0.0.5, 0.0.6, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1a0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.11.0, 0.11.1, 0.12.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.6.0, 2.7.0, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 2.11.1, 2.11.2, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.13.0, 2.13.1)
ERROR: No matching distribution found for aiobotocore==2.13.2
```

It seems that there is no such version in [PyPI](https://pypi.org/project/aiobotocore/#history). Is there a better way to install this version, or will it be made available in PyPI soon?

Thanks!

**Comment by jakob-keller** [comment]
Oops, it looks like CI failed back then: https://github.com/aio-libs/aiobotocore/actions/runs/9994091866/job/27623057889

@thehesiod: Can we re-release 2.13.2 or simply cut a new release soon?

**Comment by thehesiod** [comment]
re-running failed build job 👀

**Comment by thehesiod** [comment]
fixed, sorry about that!  perhaps should have a re-try for that task
