### ISSUE TITLE
AioJSONParser.parse contributes to most of response time

### ISSUE THREAD

**Issue by pechersky** [aio-libs/aiobotocore#1132]
**Describe the bug**
We are loading on the order of thousands of items from DynamoDB using aioboto3/aiobotocore. Each item is ~16KB, and we combine/filter items and forward them to a client. We noticed that in a loop retrieving these items, `AioJSONParser.parse` is the largest contributor of the time (as measured by `pyinstrument`). 

Compared to botocore, which took 40 s for 1000 dynamodb queries (20% inside JSONParser.parse)
aiobotocore took 12.9 s for 1000 dynamodb queries (75% inside AioJSONParser.parse)

Would it be possible to have a version of making an API request without parsing the response into a dict? This is a aiobotocore specific issue because AioJSONParser has additional wrapping on top of the botocore JSONParser.

botocore script:
```
import json
from botocore.session import get_session

def main():
    session = get_session()
    tasks = []
    query_kwarg_list = json.load(open("kwargs.json"))
    assert len(query_kwarg_list) == 1000
    client = session.create_client("dynamodb")
    for kwargs in query_kwarg_list:
        tasks.append(client.query(**kwargs))
    result = tasks
    assert len(result) == 1000


if __name__ == "__main__":
    main()
```
aiobotocore script:
```
import asyncio
import json
from aiobotocore.session import get_session

async def main():
    session = get_session()
    tasks = []
    query_kwarg_list = json.load(open("kwargs.json"))
    assert len(query_kwarg_list) == 1000
    async with session.create_client("dynamodb") as client:
        for kwargs in query_kwarg_list:
            tasks.append(client.query(**kwargs))
        result = await asyncio.gather(*tasks)
    assert len(result) == 1000


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
example invocation: `pyinstrument -o profile_boto.html -r html -- lowlevel_boto.py`

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**
```
aiobotocore==2.13.2
aiohappyeyeballs==2.3.5
aiohttp==3.10.3
aioitertools==0.11.0
aiosignal==1.3.1
async-timeout==4.0.3
attrs==24.2.0
botocore==1.34.131
frozenlist==1.4.1
idna==3.7
jmespath==1.0.1
multidict==6.0.5
pyinstrument==4.7.2
python-dateutil==2.9.0.post0
six==1.16.0
urllib3==2.2.2
wrapt==1.16.0
yarl==1.9.4
```

**Environment:**
 - Python Version: 3.10
 - OS name and version: Ubuntu 20.04

**Additional context**

**Comment by jakob-keller** [comment]
Thank you for reporting and providing all the details!

As you noted, overall runtime is actually cut down to 1/3 when leveraging concurrent aiobotocore. This is expected when performing the requests concurrently vs. sequentially.

Moreover, if my math checks out, time spent in `parse` is *only* about 20% higher, when running asynchronuously:
* botocore: 20% of 40 s = 8 s
* aiobotocore: 75% * 12.9 s = 9,7 s

I would guess that this is to be expected, given the overhead of several nested `await` statements, in particular when run under non-current versions of Python. Have you tried upgrading to leverage performance improvements in Python 3.11 and 3.12? That could narrow the gap.

> Would it be possible to have a version of making an API request without parsing the response into a dict? This is a aiobotocore specific issue because AioJSONParser has additional wrapping on top of the botocore JSONParser.

I beg to differ: The actual code performing the JSON decoding is found in botocore and not touched by aiobotocore: https://github.com/boto/botocore/blob/3e85531776532a9de1accbb86180698017bacc6f/botocore/parsers.py#L746

May I advise to raise an issue with botocore to improve performance of JSON coding, e.g. by supporting alternative JSON libraries such as [orjson](https://github.com/ijl/orjson)? That would benefit users of both botocore and aiobotocore.

**Comment by jakob-keller** [comment]
> May I advise to raise an issue with botocore to improve performance of JSON coding, e.g. by supporting alternative JSON libraries such as [orjson](https://github.com/ijl/orjson)? That would benefit users of both botocore and aiobotocore.

I just noticed https://github.com/boto/botocore/issues/3238 and realised: For your use case, the actual bottleneck is not low-level JSON decoding, but rather the higher-level parsing performed by botocore's JSONParser class. This is where performance tuning and/or the raw-mode you suggest would be beneficial.

**Comment by pechersky** [comment]
Thanks for looking into it and the quick response! As you saw, I made the botocore issue as well. Let's see what happens!

**Comment by pechersky** [comment]
Actually, most of the time is in parsing the shape, not even the json parse itself:
![image](https://github.com/user-attachments/assets/d62ea009-27fe-4c1b-af48-233787366929)
I'll leave the comment on the other issue.

**Comment by pechersky** [comment]
Likely relevant issue: https://github.com/boto/boto3/issues/2928

**Comment by thehesiod** [comment]
btw I worked on a project a few years ago related to speeding up (aio)botocore and this was my biggest perf boost: https://github.com/boto/botocore/pull/1201. Unfortunately no-one in botocore took it up

**Comment by pechersky** [comment]
Thanks for that pointer! Fortunately/unfortunately for us, we're storing datetimes mostly in unix timestamps (incurring the `decimal.Decimal` cost).

Regarding your pointer of 3.10 vs 3.11+, we saw no practical difference, for better or worse.

**Comment by thehesiod** [comment]
this isn't about storing datetimes yourself, it's when you do a get-object botocore returns the last modified timestamp as a native datetime object and to do that uses this convoluted way to parse the datetime string.  but please do notify us if you see anything egregious in terms of perf specifically due to aiobotocore's wrapping.  One thing which botocore should probably do is allow you to override the json encoder/decoder

**Comment by pechersky** [comment]
Thanks for the clarification, that's useful to know. For our u

**Comment by thehesiod** [comment]
wow we use botocore extensively, so I'm going to monitor this intently :)  good luck as I never got traction from the AWS devs for enhancements :(

**Comment by pechersky** [comment]
We've ended up going with https://github.com/awslabs/aws-sdk-python-signers/ and making direct `aiohttp` calls. Using (aio)boto's RequestSigner had overhead we didn't need.

**Comment by dacevedo12** [comment]
Found a way to override this only for the session you want, instead of globally.


```python
class OptimizedJSONParser(AioJSONParser):
    def _handle_json_body(self: Any, raw_body: str, _shape: Any) -> Any:
        return self._parse_body_as_json(raw_body)


class OptimizedParserFactory(AioResponseParserFactory):
    def create_parser(self, protocol_name: str) -> ResponseParser:
        parsers = {**PROTOCOL_PARSERS, "json": OptimizedJSONParser}
        parser_cls = parsers[protocol_name]
        return parser_cls(**self._defaults)


class OptimizedAioSession(AioSession):
    def _register_response_parser_factory(self) -> None:
        self._components.register_component(
            "response_parser_factory", OptimizedParserFactory()
        )
```

If using aioboto3, you can then
```python
SESSION = aioboto3.Session(botocore_session=OptimizedAioSession())
```

**Comment by dacevedo12** [comment]
haven't benchmarked it yet, but the `slow_callback_duration` logs from asyncio debug mode are gone. without this change, those logs showed tasks taking up to 1s or more to yield under high load
