### ISSUE TITLE
pep-561: Add typing support (mypy)

### ISSUE THREAD

**Issue by ssbarnea** [aio-libs/aiobotocore#1133]
This library should follow [pep-561](https://peps.python.org/pep-0561/).

**Comment by jakob-keller** [comment]
Type stubs for `aiobotocore` are available via https://pypi.org/project/types-aiobotocore, as is [documented in our README](https://github.com/aio-libs/aiobotocore?tab=readme-ov-file#enable-type-checking-and-code-completion).

**Comment by ssbarnea** [comment]
@jakob-keller Thanks. For some reason, mypy was not able to susggest use of types-aiobotocore while it did this for 4-5 other dependencies. I wonder where it takes these suggestions from.

**Comment by jakob-keller** [comment]
I believe this is hard coded in mypy: https://github.com/python/mypy/blob/master/mypy/stubinfo.py
