### ISSUE TITLE
Standardize YAML format

### ISSUE THREAD

**Issue by jakob-keller** [aio-libs/aiobotocore#1168]
yeah, that's why there should be a shared config so that every PR author wouldn't reformat by accident. I usually have yamllint wired via the pre-commit.com tool

_Originally posted by @webknjaz in https://github.com/aio-libs/aiobotocore/pull/1163#discussion_r1725194345_

**Comment by webknjaz** [comment]
```console
$ cat .yamllint
---

extends: default

rules:
  indentation:
    level: error
    indent-sequences: false
  truthy:
    allowed-values:
    - >-
      false
    - >-
      true
    - >-  # Allow "on" key name in GHA CI/CD workflow definitions
      on

...
```
