### ISSUE TITLE
Run CI/CD on merge queue

### ISSUE THREAD

**Issue by jakob-keller** [aio-libs/aiobotocore#1170]
In a follow-up PR, I'd also enable merge queues.

_Originally posted by @webknjaz in https://github.com/aio-libs/aiobotocore/pull/1163#discussion_r1727056403_

**Comment by webknjaz** [comment]
Example: https://github.com/cherrypy/cheroot/blob/1ff20b1/.github/workflows/ci-cd.yml#L6-L10

**Comment by webknjaz** [comment]
Or you could extend it to a year or something like that..

**Comment by thehesiod** [comment]
meh, there's so few issues not worth the hassle, more hassle in terms of having to ping issues we want to eventually fix

**Comment by webknjaz** [comment]
Now, alls-green needs to be integrated so it could be used in branch protection...

**Comment by jakob-keller** [comment]
> Now, alls-green needs to be integrated so it could be used in branch protection...

That's #1171 :-)
