### ISSUE TITLE
Check that git tag matches version in CI/CD

### ISSUE THREAD

**Issue by jakob-keller** [aio-libs/aiobotocore#1182]
In the CI pipeline, you can also check that it matches the tag.

_Originally posted by @webknjaz in https://github.com/aio-libs/aiobotocore/issues/1178#issuecomment-2306812536_

**Comment by webknjaz** [comment]
When using `setuptools-scm` I even go as far as computing the expected dists filenames and assert that when building them. If you want to switch to it, I'll find some examples..
