### ISSUE TITLE
AioInstanceMetadata not timing out

### ISSUE THREAD

**Issue by Azmisov** [aio-libs/aiobotocore#1224]
```
session = aiobotocore.session.get_session()
session.set_config_variable("metadata_service_timeout", 1)
async with session.create_client("s3", config=AioConfig(
    max_pool_connections=16,
    connect_timeout=1,
    read_timeout=1,
)) as client:
    ...
```

This freezes and never acquires the client. It is freezing at `AioCredentialResolver`, loading `iam-role` provider. The stack looks something like this: `retrieve_iam_role_credentials` > `AioInstanceMetadataFetcher _fetch_metadata_token` > `AioIMDSFetcher session.send` > `AIOHttpSession session.request` > `ClientSession _connector.connect` > `TCPConnector _wrap_create_connection` > `TCPConnector aiohappyeyeballs.start_connection`.

There's a `ceil_timeout` context manager on a couple aiohttp calls, which I assume are supposed to enforce timeouts. The timeout variable values for each of those is `{ceil_threshold:5, connect:None, sock_connect:1, total:None}`

I've tried with botocore and it does not freeze. It holds up for about 1 second or so before timeout on its own `_fetch_metadata_token` method and continues on.

Sounds like it might be an aiohttp issue, but perhaps I'm just not configuring the timeouts correctly.

**Environment:**
python=3.12
aiobotocore=2.13.3
aiohttp=3.10.10

**Comment by Azmisov** [comment]
Update: I've done some more tests and `await asyncio.sleep(1)` will block forever. So I don't think aiobotocore is the issue. Very strange... not looking forward to debugging this.

**Comment by thehesiod** [comment]
good luck! :]. try with debug asyncio mode: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONASYNCIODEBUG
