### ISSUE TITLE
Bump `botocore` dependency

### ISSUE THREAD

**Issue by edgarrmondragon** [aio-libs/aiobotocore#1229]
Similar to https://github.com/aio-libs/aiobotocore/commit/89af505abae609314ea6d2ccced2244636ddb191, as the current constraint is blocking updates of `langchain-aws`, which now depends on boto3 `>=1.35.74`:

https://github.com/langchain-ai/langchain-aws/compare/v0.2.7...v0.2.9

**Comment by edgarrmondragon** [comment]
I tried to submit a PR, but I'm not sure what changes `tests/test_patches.py` expects.

**Comment by thehesiod** [comment]
if you want to help, we just need to do some testing in https://github.com/aio-libs/aiobotocore/pull/1221

**Comment by dacevedo12** [comment]
in 1.35.74 they introduced support for Aurora DSQL, fairly new service but would be cool if the range could be extended to try it out https://github.com/boto/boto3/blob/aa78fa97e17479edbae495587f60ceae52ac5bca/CHANGELOG.rst#L81
