### ISSUE TITLE
allow passing in an aiohttp ClientSession to allow host code to manage pooling etc.

### ISSUE THREAD

**Issue by graingert** [aio-libs/aiobotocore#125]

**Comment by thehesiod** [comment]
IMHO this would not bode well with how botocore works, botocore has several `Config` options to handle pool size, etc per client, not per session.  See:

* `max_pool_connections`: https://github.com/boto/botocore/blob/develop/botocore/config.py#L52
* `read_timeout`: https://github.com/boto/botocore/blob/develop/botocore/config.py#L41
* `connect_timeout`: https://github.com/boto/botocore/blob/develop/botocore/config.py#L36
* SSL `verify`: https://github.com/boto/botocore/blob/develop/botocore/client.py#L58

we allow for setting aiohttp TCPConnector params via `AioConfig`  see: https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/config.py#L37

**Comment by thehesiod** [comment]
do you still feel strongly about this?  If not let's close this.

**Comment by graingert** [comment]
I'd still rather be able to pass in a whole aiohttp ClientSession.

**Comment by thehesiod** [comment]
what is your response to my first comment?  @jettify what do you think?

**Comment by graingert** [comment]
when passing the actual session you could raise an exception if any of the other config variables were non None.

**Comment by thehesiod** [comment]
there are defaults for all those even if you don't specify them

**Comment by thehesiod** [comment]
also as botocore doesn't allow you to do this, why should aiobotocore

**Comment by graingert** [comment]
@thehesiod I'd like botocore to do it too, but I don't use it.

**Comment by jettify** [comment]
We configure timeouts and headers very carefully in order to maintain proper request signature, external session object may breaks things...

**Comment by jettify** [comment]
Closing issue for now, looks like we are not going to implement this.
