### ISSUE TITLE
head_object is broken

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#131]
it will not return the ETag, the issue is due to https://github.com/aio-libs/aiobotocore/pull/116.  botocore expect the ETag to be in the correct case.  We can't fix this until https://github.com/KeepSafe/aiohttp/issues/1570 is fixed. After that is fixed we can switch to raw_headers and use botocore's CaseInsensitiveDict

**Comment by thehesiod** [comment]
@Fedorof @jettify I knew this was going to bite us =)

**Comment by jettify** [comment]
what a pain, headers supposed to be case insensitive...
