### ISSUE TITLE
upgrade botocore version

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#143]
I think there's three tasks here until there's official asyncio support from boto

1) Do the manual process
2) create a script that will create an upgrade issue each time there's a new version of botocore detected
3) Investigate if we can automate this any more
    - detect files added/removed
    - detect new methods/signatures, function hashes, etc

**Comment by jettify** [comment]
pyup-bot  will create PR with botocore version bumps, but setup.py still should be updated manually

**Comment by thehesiod** [comment]
cool, ya we can then re-use that template PR to do the *real* work :)

**Comment by jettify** [comment]
Looks like 1.5.28 green with our tests
https://travis-ci.org/aio-libs/aiobotocore/jobs/214043233

**Comment by thehesiod** [comment]
I'll take a diff look shortly

**Comment by jettify** [comment]
Here is PR with change log https://github.com/aio-libs/aiobotocore/pull/146

**Comment by jettify** [comment]
@thehesiod do you think we need to test at least several version between 1.5.0 and 1.5.28 ?

**Comment by thehesiod** [comment]
good news, no changes to our sources, looks like they just changed json files and some credential stuff...I think we can range it from 1.5.0-1.5.28

**Comment by thehesiod** [comment]
this is the kind of change which we could approve by bot...basically no changes to certain "critical" files, and widen the allowed range.

**Comment by jettify** [comment]
agreed, so lets merge #146 and release new version.

**Comment by thehesiod** [comment]
but don't you want to range it instead of fix it?

**Comment by jettify** [comment]
I was thinking about `botocore>=1.5.0, <1.5.28` in `setup.py` and leave fixed version in `requirements-dev.txt`, bot tracks only `requirements-dev.txt` file

**Comment by jettify** [comment]
Have to go, feel free to do release and do versions if you have time today, otherwise I can do that tomorrow.

**Comment by thehesiod** [comment]
done

**Comment by jettify** [comment]
Thanks a lot!
