### ISSUE TITLE
Suggestion: Use localstack for testing

### ISSUE THREAD

**Issue by achimnol** [aio-libs/aiobotocore#155]
https://bitbucket.org/atlassian/localstack
This project emulates AWS APIs in the HTTP server level instead of mocking API client methods.
We could write more realistic test cases using this, though I haven't tried this personally yet.

**Comment by jettify** [comment]
We use moto in same way, there is fixture that starts http mocking server
in separate process, all moto tests use proxy setting in order to make call
to local server instead.

**Comment by jettify** [comment]
Here is our code that does mocking server logic https://github.com/aio-libs/aiobotocore/blob/99fd4bfd0151595a04cd6800fe35ec509e983fd6/tests/mock_server.py#L16-L70. `localstack` looks nice but I have not tried it too.

**Comment by thehesiod** [comment]
just looked at localstack and it uses moto under the covers for S3, closing this issue.  Furthermore, note that I've found several shortcomings in moto: https://github.com/spulec/moto/pull/922#issuecomment-300069050
