### ISSUE TITLE
move to python >=3.5 

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#16]
Do we want to move to python 3.5 only?

**Comment by eestrada** [comment]
Such a change would be problematic for my needs; I'm targeting systems that only support 3.4 as the latest version. All the code that works in 3.3+ should still work the same in 3.5. What would be the benefit of cutting off support for older versions?

**Comment by jettify** [comment]
No much benefit, my project still using python 3.4 too. Just developing for python 3.5 more fun, you know `async/await` syntax :)

 Since there are users still on python 3.4 I think it would not be wise to break compatibility.

**Comment by eestrada** [comment]
I get it. I like shiny new features too :grinning:. Thanks for holding off though :+1:.
