### ISSUE TITLE
switch moto to run in a thread instead of process

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#184]
I have some code I did here https://github.com/DataDog/dd-trace-py/pull/248 which runs ddtrace in a thread.  btw what's weird is why the regular decorator style (after adding coroutine support) doesn't work...it seems like they patch socket.socket or something.

**Comment by jettify** [comment]
Could you please explain benefits of thread in our case? I used process because:
1) better isolation
2) it is easy to terminate process, thread does not have such api
