### ISSUE TITLE
[Tracking] reset stream support

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#221]
I just ran into this error for the first time with aiobotocore, logging here for us to check if we're missing any adaptation from aiohttp 2.x

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/botocore/awsrequest.py", line 426, in reset_stream
    self.body.seek(0)
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    response = await self._client.put_object(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/aiobotocore/client.py", line 79, in _make_api_call
    operation_model, request_dict)
  File "/usr/local/lib/python3.5/site-packages/aiobotocore/endpoint.py", line 211, in _send_request
    request.reset_stream()
  File "/usr/local/lib/python3.5/site-packages/botocore/awsrequest.py", line 429, in reset_stream
    raise UnseekableStreamError(stream_object=self.body)
botocore.exceptions.UnseekableStreamError: Need to rewind the stream <_io.BytesIO object at 0x7f6025b68258>, but stream is not seekable.
```

**Comment by thehesiod** [comment]
validated that the body is getting closed in aiohttp 2.x

**Comment by thehesiod** [comment]
due to aiohttp 2.x change

**Comment by thehesiod** [comment]
have submitted a provisional fix for this until we have a final resolution on the aiohttp issue I logged

**Comment by jolleon** [comment]
I'm seeing this issue intermittently as well. @thehesiod looks like aiohttp folks are not too keen on fixing it there as you suggested... is this something that can be fixed directly in aiobotocore?

**Comment by thehesiod** [comment]
latest release should work ok, see https://github.com/aio-libs/aiobotocore/pull/248.  Also I think I've convinced them to release a fix soon that will support this workflow natively.

**Comment by jolleon** [comment]
Awesome, will use this, thanks!

**Comment by thehesiod** [comment]
@jolleon we had a dev run into this when downloading multiple gigs of data :)

**Comment by jolleon** [comment]
Interesting, for me it happened in a service that uploads a lot of small files to S3... might need to investigate performance a bit deeper at some point...

**Comment by thehesiod** [comment]
now that you mentioned it, I have an issue I'm investigating where my read_timeout is not being obeyed...I'm hoping this fixes it.
