### ISSUE TITLE
[Tracking] Config read_timeout not behaving correctly

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#245]
We just ran into this due to: https://github.com/aio-libs/aiohttp/issues/1954.  Here until we have a resolution to that issue.  To work around this we'd have to disable read_timeout, and re-impl read() to have a timeout per chunk.

**Comment by thehesiod** [comment]
Unfortunately one of the aiohttp devs doesn't understand both precedence and the literal meaning of read_timeout so we'll have to re-implement this ourselves. I'll work on this today.  Many people are going to need similar functionality (including me in my other projects) so I'm going to see if we can allow users to use the fix for their own usage of aiohttp.   I'm not 100% certain we'll be able to get this to work cleanly as IIRC they create the stream class from cython without backref to the request.  Based on the bizarre design decisions being made in aiohttp: this, the stream `close` issue, the odd multidict camel casing of headers, and various strange behaviors found in the past I'm really almost to the point of creating a separate core impl of aiohttp.

**Comment by adamrothman** [comment]
Man that guy is being such a pain in the ass. Thanks for fighting the good fight @thehesiod!

**Comment by thehesiod** [comment]
@adamrothman  I don't know how many ways I can prove something is wrong, lol

**Comment by thehesiod** [comment]
re-opening until ideally aiohttp supports this natively

**Comment by thehesiod** [comment]
update: asvetlov said he'd impl it for is

**Comment by thehesiod** [comment]
update on this issue, support for timeouts was added to master, just waiting on a release with the feature.

@samuelcolvin as soon as the next aiohttp release happens we'll have a medium sized change to support it and remove a lot of workarounds we added to support proper client timeouts.  Hopefully soon!  You could try however no guarantees it will work.  If you'd like to make sure it will work correctly there are some instructions here of what's required: https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#how-to-upgrade-botocore

**Comment by samuelcolvin** [comment]
woop. Thank you.

**Comment by thehesiod** [comment]
it has for awhile, we just forgot to close this ;)
