### ISSUE TITLE
[Tracking] support compressed responses

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#258]
See https://github.com/aio-libs/aiohttp/issues/1992 and comment in endpoint.py

**Comment by thehesiod** [comment]
this is now dependent on https://github.com/boto/botocore/issues/1255

**Comment by thehesiod** [comment]
update: just need to write a unittest for this as it should be supported in 0.5.1

**Comment by socketpair** [comment]
I think this issue should be closed.
