### ISSUE TITLE
Create stubs for documentation

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#285]
We need to add documentation, as a first step, just create simple stub and add README.rst information and probably examples.

**Comment by jettify** [comment]
initial version created at http://aiobotocore.readthedocs.io/en/latest/#

**Comment by jettify** [comment]
btw @thehesiod do you have readthedocs.io account?

**Comment by mivade** [comment]
This looks like it can probably be closed.

**Comment by thehesiod** [comment]
@jettify just created one: thehesiod
