### ISSUE TITLE
Help with simple aiobotocore usage examples for different AWS services

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#288]
In order to ease adoption of aiobotocore we need bunch of examples for different services, personally, I am not big AWS user myself, worked only with S3, so need your help for other services. 

Examples should be short, self describing and be complete python program.

**Comment by zkanda** [comment]
This would be very awesome, I'm trying to work out in SQS but I can't seem to model it well with long polling. So an example would be greatly appreciated. :+1:

**Comment by morissette** [comment]
I'm working on cloudwatch currently; will write an example when implemented.

**Comment by terrycain** [comment]
@zkanda  In the docs there is now a producer consumer example with SQS that uses WaitTimeSeconds to set the polling interval - https://aiobotocore.readthedocs.io/en/latest/examples.html#sqs 

Hope that helps.

**Comment by thehesiod** [comment]
btw, almost everything is the same as botocore, the only difference is the API calls are now async, and some of the high level classes are `Aio` (Ex: AioSession).  There's not much magic to it.
