### ISSUE TITLE
How do i upload huge files with aiobotocore.

### ISSUE THREAD

**Issue by sourcepirate** [aio-libs/aiobotocore#320]

**Comment by thehesiod** [comment]
I haven't tried this yet but theoretically it should work like botocore.  Can you try with an `io.BytesIO` instance as the `Body` to `put_object` ?  If it doesn't work we can fix it

**Comment by bsamuel-ui** [comment]
You probably want to open a socket and write data to it. Unfortunately, requests to S3, like all AWS requests, have to be signed. (Even an unauthenticated request needs an MD5 hash.) The facility S3 provides for large amounts of data is [a multipart upload](http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html).

First be certain that the S3Transfer class in regular boto3 really doesn't do what you want, as it's going to use a thread pool to saturate your connection, it handles retries, it's fairly configurable, and it's maintained by the S3 team.

If you want to recreate that using asyncio, the key ingredient is to create a bounded worker pool. You're just going to call UploadPart a bunch of times, and you just want to make sure you limit how many requests are open at once. Also, you'll need to ensure the max_connections in your config are bumped up to the size of the pool. Hope this helps!

**Comment by sourcepirate** [comment]
Thanks! do we have multipart upload as a part of aiobotocore ?

**Comment by thehesiod** [comment]
Aiobotocore supports everything botocore does

**Comment by jettify** [comment]
In my project I use aiobotocore multipart upload for fast uploading of large files, basically 10 coroutines push large file by chunks in parallel.

**Comment by jettify** [comment]
closing issue for now, feel free to open new one if you need more help
