### ISSUE TITLE
Aiobotocore support for botocore blocks custom EMR AMIs

### ISSUE THREAD

**Issue by georgebihtas** [aio-libs/aiobotocore#337]
AWS now supports custom EMR AMIs (Amazon EMR version 5.7.0 or later). This functionality is supported by botocore >= 1.6.1

Current version of aiobotocore supports 'botocore>=1.5.71, <=1.5.78'

Could we please get the aiobotocore updated in order to support botocore >= 1.6.1? It's a very crucial feature and it blocks a number of projects.

**Comment by hughchristensen** [comment]
This would be very helpful.

**Comment by jettify** [comment]
Have you tried explicitly install botocore==1.6.1 ? It may work without any changes?

**Comment by jettify** [comment]
Looks like tests for 1.7.1 are green so there is great chance that simply upgrading botocore will work 
https://github.com/aio-libs/aiobotocore/pull/335

**Comment by georgebihtas** [comment]
I have tried aiobotocore 0.4.4 with botocore 1.6.1 and breaks.

It seems to work with aiobotocore 0.4.4 and and botocore 1.5.78 but I had to copy

 botocore/botocore/data/emr/2009-03-31/service-2.json

from botocore 1.6.1 to botocore 1.5.78

I suspect this is going to be the case with 1.7.1 as well

**Comment by jettify** [comment]
can you share your testing snippet?

**Comment by georgebihtas** [comment]
Unfortunately I don't have one. I tested it using our API and I was able to start an EMR cluster and I could see the custom AMI's id on AWS web interface.

But if I pip install aiobotocore 0.4.4 and botocore 1.6.1 seems to fail

If I understand correctly what you suggest here: https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst

is more or less what I have already done. I would rather to be able to pip install what I want directly instead of manually applying the changes because I think it will complicate our deployment a bit (maybe not but this is how I see it).

But if aiobotocore is not going to be updated any time soon to support botocore >= 1.6.1 I might have no other option.

**Comment by jettify** [comment]
If you submit PR with required changes and tests (looks like moto mocking library, has some endpoints working for EMR), we can release new version right after merge of PR.

**Comment by jettify** [comment]
I will try to find time this week to investigate this issue.

**Comment by thehesiod** [comment]
There are a couple core changes required to update to 1.6.x+. See our notes for how to proceed. I can also help looking into it, almost muscle memory now ;)

**Comment by georgebihtas** [comment]
@jettify I am afraid I have only ever used aiobotocore/botocore as a client and do not have any experience of the core library. I am afraid I am not in a position to submit any PR (in a reasonable amount of time) - if I could I would of course do so. Sorry for this.

@thehesiod it sounds like you do have good idea of the problem ("couple core changes required to update to 1.6.x+.") - would you be able to submit the PR? It would be a massive help to me!

@thehesiod Thanks for your comment. Unfortunately I do not have any experience of the core library and I suppose I would need to spend a significant amount of time to make it work as it would require a good knowledge of aiobotocore and botocore.

**Comment by hughchristensen** [comment]
@jettify @thehesiod is there anything you can do to help here? We have a team here who are desperate to access this. Thank you!

**Comment by jettify** [comment]
@thehesiod have a PR with botocore update https://github.com/aio-libs/aiobotocore/pull/341 Can you test it?

**Comment by hughchristensen** [comment]
@jettify @thehesiod thank you so much for getting out the updated version of aiobotocore -- we are testing this now for our build.

**Comment by georgebihtas** [comment]
Thank you very much for releasing 0.4.5 :)

**Comment by jettify** [comment]
All the thanks to @thehesiod he did all the job!

**Comment by thehesiod** [comment]
and @jettify for the review w/ requirements fix :)

**Comment by jettify** [comment]
I think issue resolved, closing
