### ISSUE TITLE
Not possible to determine profile of boto3 session

### ISSUE THREAD

**Issue by tomers** [aio-libs/aiobotocore#349]
In `session.py`'s `get_session` it is not possible to pass arguments such as `profile` to constructor of `AioSession`.

I would like to get a session of a specific profile, but it is not possible.

**Comment by thehesiod** [comment]
we follow botocore's implementation: https://github.com/boto/botocore/blob/develop/botocore/session.py#L922

**Comment by tomers** [comment]
You cannot change session's profile after init, so getting the session does not help. I will send PR that fixes it tomorrow. It is a minor fix:
```
Index: aiobotocore/session.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- aiobotocore/session.py	(revision 097e2a7e57e5eaeda01a6c8cc3ae24ccd08dc90b)
+++ aiobotocore/session.py	(revision 11295aa269b75004e8d78ede9fc6ed8131930ec2)
@@ -77,9 +77,9 @@
         return client
 
 
-def get_session(*, env_vars=None, loop=None):
+def get_session(*, env_vars=None, loop=None, **kwargs):
     """
     Return a new session object.
     """
     loop = loop or asyncio.get_event_loop()
-    return AioSession(session_vars=env_vars, loop=loop)
+    return AioSession(session_vars=env_vars, loop=loop, **kwargs)
```

**Comment by thehesiod** [comment]
we want to minimize customizations to aiobotocore, you should just construct the session object directly like you would with botocore
```python
session = aiobotocore.session.AioSession(...)
```

**Comment by tomers** [comment]
I submitted https://github.com/aio-libs/aiobotocore/pull/352.

> we want to minimize customizations to aiobotocore
Why do you want to restrict the user from controlling botocore session? In my case I must use specific profile for the session.
I believe the user should have the ability to use `get_session()`, which is less tedious than constructing the session object directly. I don't see any drawback to this, as it has nothing to do with customizing `AioSession` itself.

**Comment by thehesiod** [comment]
We don't restrict anything, we follow their version exactly in this case. We reflect all changes of botocore's version of this method to our version. The fewer changes the better. I'll let @jettify give the final word.

**Comment by jettify** [comment]
Agree with @thehesiod, we try to follow `botocore` API as close as possible, also creating helper method inside users codebase is trivial. To improve things we probably can add note in README/docs about custom profiles.

**Comment by tomers** [comment]
Ok, agreed. I used @thehesiod suggestion and it worked for me.
Thank you for spending your time on this.

Regards,
Tomer

**Comment by jettify** [comment]
@tomers no problem, your suggestion totally make sense, you may try to convince `botocore` people, we will follow after them :)

**Comment by thehesiod** [comment]
@tomers yes, please open bug against botocore and link here if you feel strongly (we'll then pick up the changes per our integration procedures), however IMHO `get_session` is a pointless method and should should have never been created by the botocore devs.  My suggestion to botocore would be to deprecate and remove this method in a major rev.
