### ISSUE TITLE
New aiohttp release will happened in next few days

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#400]
@thehesiod new version of aiohttp will be release soon, I am trying to enumerate thing we need to do:
1) compression issue: https://github.com/aio-libs/aiobotocore/pull/298
2) redirect issue: https://github.com/aio-libs/aiobotocore/blob/097e2a7e57e5eaeda01a6c8cc3ae24ccd08dc90b/aiobotocore/endpoint.py#L292-L301

am I missing something?

**Comment by thehesiod** [comment]
It would be nice if it could support the non compliant newline issue with
multipart. But no biggie.

**Comment by thehesiod** [comment]
sorry, just realized you meant for aiobotocore (had responded from phone).  Ya I think they haven't implemented fix for read_timeout issue yet: https://github.com/aio-libs/aiobotocore/issues/245 or stream reset: https://github.com/aio-libs/aiobotocore/issues/221 so won't have to do those.

**Comment by asvetlov** [comment]
aiohttp 2.3 is out

**Comment by asvetlov** [comment]
Tests are failed in aiohttp 2.3.2
