### ISSUE TITLE
Support aiohttp 2.3.x+

### ISSUE THREAD

**Issue by hellysmile** [aio-libs/aiobotocore#419]
https://github.com/aio-libs/aiobotocore/pull/415

fails on `test_patches `

Is there any plans to support 2.3.x+?

Do wee need to support 2.2 and 2.3? Myabe next aiobotocore can support only 2.3.x+?

**Comment by jettify** [comment]
I wil try to find time this weekend, for more information see:
https://github.com/aio-libs/aiobotocore/issues/400
