### ISSUE TITLE
FYI: Kinesis works (at least basic stuff)

### ISSUE THREAD

**Issue by butla** [aio-libs/aiobotocore#441]
Yeah, I should make a PR saying that at probably prepare an example, but I don't have the time right now.
But that info will be useful for anyone looking at libraries to find something that can work with Kinesis from AsyncIO (like I was yearlier today).

The things that I've checked:
- create_stream
- add_tags_to_stream
- put_record
- get_shard_iterator
- get_records

I'll try to make a nice PR in the future.

**Comment by jettify** [comment]
Thanks for letting us know!

**Comment by thehesiod** [comment]
added note to readme
