### ISSUE TITLE
Example with custom S3 api server

### ISSUE THREAD

**Issue by zloidemon** [aio-libs/aiobotocore#45]
Hi,

I have my own S3 api server, but I can't get data because cert can't verify. I changed verify=False in client it not solve an issue. Then I've seen code and found that is reading configuration from where? Also, I have my own certs bundle (ca_certs) I changed settings in client to read that, but i got same error with verification. Would you like to provide an example file with custom S3 api server connection?

**Comment by jettify** [comment]
Honestly, I have never tried to supply cert bundle or anything to do  with certs...

As for none aws s3, `aiobotocore` should be able to connect, but that could be tricky since you need to disable `fix_s3_host` event in order to connect to custom host.

**Comment by jettify** [comment]
So you can try to do something like: `session.unregister('before-sign.s3', fix_s3_host)`

**Comment by zloidemon** [comment]
You can try it easy with install [sx](http://www.skylable.com/install/) and [libres3](http://www.skylable.com/install/#libres3). It takes around 10-20 min of real life.

**Comment by jettify** [comment]
I am not sure if this fix you problem, but you can pass `endpoint` parameter to the client, this way we test s3 with mocking server. Closing for now.
