### ISSUE TITLE
add to pip

### ISSUE THREAD

**Issue by nhumrich** [aio-libs/aiobotocore#51]
Can this get added to PyPi so it can be pip installed?

**Comment by nhumrich** [comment]
Looks like the aiobotocore package is already claimed on pypi, and the setup.py file is ready to go. Any reason this hasn't been published yet?

**Comment by jettify** [comment]
Hi, I will release library in day or two. The reason I have not released it yet because consider it in alpha stage (but I use it in production) and api also could be changed.

**Comment by nhumrich** [comment]
Thats fine, you can release alpha things so pypi. There is a classifier for that: `Development Status :: 3 - Alpha`

Just version it 0.x.x and people will understand.

**Comment by jettify** [comment]
I have release this package to pypi https://pypi.python.org/pypi/aiobotocore/0.0.5
