### ISSUE TITLE
Move to native coroutines

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#546]
Since we dropped support for python < 3.5, now we can use `async def` instead of `@asyncio.coroutine`

**Comment by jettify** [comment]
Task should be accomplished with 3 PRs

Port tests to async/await
Port full library to async/await
Update changes.rst and release new version and update README, docs, travisci

**Comment by thehesiod** [comment]
all these resolved by https://github.com/aio-libs/aiobotocore/pull/564, I'll try breaking it apart

**Comment by thehesiod** [comment]
I don't think any doc changes are necessary, we were already python 3.5+
