### ISSUE TITLE
[tracking aiohttp] Possible Memory Leak with SSL Sessions

### ISSUE THREAD

**Issue by TimOrme** [aio-libs/aiobotocore#552]
Hello,

I'm calling S3 using:

-python 3.6.3
-aiobotocore 0.6.0
-Ubuntu 17.10

I notice that when I have a loop of async calls to retrieve data, my memory usage seems to continually go up, even though I expect it to stay the same.  Here is a test case I could come up with:

```python
import asyncio
from hashlib import md5
import aiobotocore
from botocore.client import Config
import boto3
from botocore.exceptions import ClientError as BotoClientError
from itertools import islice, chain

class FileService(object):
    def __init__(self, loop=None):
        config = Config(signature_version='s3v4')
        self._loop = loop or asyncio.get_event_loop()

        self._session = boto3.Session()
        self._asession = aiobotocore.get_session(loop=self._loop)
        self._config = config

    def _get_s3_client(self):
        # Use the credentials created by boto3 session.
        creds = self._session.get_credentials()
        client = self._asession.create_client('s3', region_name="us-east-1",
                                              aws_secret_access_key=creds.secret_key,
                                              aws_access_key_id=creds.access_key,
                                              aws_session_token=creds.token,
                                              config=self._config)
        return client

    def readfiles(self, paths):
        return self._loop.run_until_complete(self.readfiles_async(paths))

    def readfile(self, path, client=None):
        return self._loop.run_until_complete(self.readfile_async(path, client=client))

    async def readfiles_async(self, paths):
        async with self._get_s3_client() as client:
            futures = [self.readfile_async(path, client=client) for path in paths]
            return await asyncio.gather(*futures)

    async def readfile_async(self, path, client=None):
        data = await self._get_object_async(client, path)
        return data

    async def _get_object_async(self, client, path):
        bucket, key = parse_s3_path(path)
        try:
            response = await client.get_object(Bucket=bucket, Key=key)
            async with response['Body'] as stream:
                return await stream.read()
        except BotoClientError as e:
            if e.response['Error']['Code'] == 'NoSuchKey':
                pass


def parse_s3_path(path):
    s3_tokens = path.split('/', 3)
    try:
        return s3_tokens[2], s3_tokens[3]
    except IndexError:
        return s3_tokens[2], ''


def chunked(iterable, size=None):
    if not size:
        yield iterable
    else:
        it = iter(iterable)
        while True:
            s = islice(it, size)
            yield chain([next(s)], s)


service = FileService()

ids = range(0, 10000)
for chunk in chunked(ids, 250):
    file_paths = ["s3://mybucket/%s.file" % x for x in chunk]
    all_data = service.readfiles(file_paths)
```

Each chunk increases the memory size my a noticeable margin, and does not seem to release it on subsequent chunks.

I am not an expert at debugging memory issues in python, but I tried using objgraph to see which objects were getting created on each subsequent loop and found that the majority appear to be SSL contexts.

Thanks,
Tim

**Comment by thehesiod** [comment]
I have a suspicious as well there's a leak with something related to SSL, our aiohttp service is leaking 10s of megabytes per week.  SSL in Python 3.5.2 had a leak with CRLs, perhaps there's something else.  Have you tried with tracemalloc?

**Comment by thehesiod** [comment]
here's a little utility I sometimes use: https://gist.github.com/thehesiod/2f56f98370bea45f021d3704b21707a9

**Comment by TimOrme** [comment]
Interestingly, if I remove the:

```python
        async with response['Body'] as stream:
            await stream.read()
```
The leak doesn't happen. So perhaps its something with the stream reader not properly closing up?

**Comment by thehesiod** [comment]
interesting, that would point to a aiohttp leak, perhaps in it's cython code.  btw sorry about the accidental close, hit the wrong button

**Comment by thehesiod** [comment]
here's an interesting potential leak that tracemalloc reported:
```bash
407 memory blocks: 29.1 KB
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/ssl.py", line 651
	    return self._sslobj.peer_certificate(binary_form)
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/sslproto.py", line 585
	    peercert = sslobj.getpeercert()
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/sslproto.py", line 204
	    self._handshake_cb(None)
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/sslproto.py", line 503
	    ssldata, appdata = self._sslpipe.feed_ssldata(data)
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/selector_events.py", line 731
	    self._protocol.data_received(data)
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/events.py", line 127
	    self._callback(*self._args)
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 1426
	    handle._run()
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 421
	    self._run_once()
	  File "/Users/amohr/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 454
	    self.run_forever()
	  File "/tmp/leak.py", line 35
	    return self._loop.run_until_complete(self.readfiles_async(paths))
```

@asvetlov

**Comment by thehesiod** [comment]
hmm, my stack isn't related to read, so may just be something that eventually gets released. I did a little digging and the peercert had a refcount of 1 so it seems to be misleading.  btw, note that "leaks" in python are really hard to trace because python keeps pool(s) of memory and doesn't always release them back to the system.  For details see: https://rushter.com/blog/python-memory-managment.  This is compounded by fragmentation.

**Comment by jettify** [comment]
https://github.com/aio-libs/aiobotocore/blob/52df9fc4b4eaf8145b2512b9daac312d3539232c/aiobotocore/endpoint.py#L86-L117

May be not directly related but `self.__response.close()`should coroutine right for new aiohttp?

**Comment by thehesiod** [comment]
@jettify on the line `async with response['Body'] as stream:` the `__aexit__` should await the close.

**Comment by TimOrme** [comment]
Yeah, it doesn't seem that the close method is ever called in this case. It seems that everything is going through the __aexit__ method.

**Comment by thehesiod** [comment]
btw @TimOrme last time I found a leak it was a native like in the cpython SSL adapter code triggered by SSL certs that had CRLs.  So it could be dependent on the types of certs returned from AWS.  Sorry haven't had more time to dig into this, it's pretty painful finding native leaks.  but rest assured we're seeing this in prod as well so I want to get to the bottom of it.

**Comment by thehesiod** [comment]
may be related to this: https://github.com/aio-libs/aiohttp/issues/3010

**Comment by navidnabavi** [comment]
Somehow this problem made this library unusable. Is there any plan for fixing it?

**Comment by thehesiod** [comment]
yay, I think this is now fixed

**Comment by thehesiod** [comment]
note: there are no releases with this yet, so you have to apply the patches to a custom build of python
