### ISSUE TITLE
This works with DigitalOcean Spaces also!

### ISSUE THREAD

**Issue by philgooch** [aio-libs/aiobotocore#556]
Was looking for a solution for async uploads to DigitalOcean spaces and aiobotocore fits the bill perfectly.

The only changes required to get the Basic Example working with Spaces are as follows:

`bucket = <your DO Space name>`

In `session.create_client`:

`region_name=<your DO region name, e.g. nyc3>`
`endpoint_url=<your DO endpoint, e.g. https://nyc3.digitaloceanspaces.com>`

e.g.

```
async with session.create_client('s3', region_name='nyc3',
                                   endpoint_url='https://nyc3.digitaloceanspaces.com',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID) as client:
```

**Comment by thehesiod** [comment]
so is this a request for documentation?

**Comment by philgooch** [comment]
Sorry, probably wrong place for this

**Comment by jettify** [comment]
I think we can add this information to the readme? Probably someone else will find this information useful
