### ISSUE TITLE
Incompatibility aiobotocore 0.6.0 and botocore >=1.10.4

### ISSUE THREAD

**Issue by mikepashin** [aio-libs/aiobotocore#559]
Hello!

After update all pip package in my project, i see problems Incompatibility aiobotocore 0.6.0 and botocore.

Console: **aiobotocore 0.6.0 has requirement botocore<=1.8.21,>=1.8.0, but you'll have botocore 1.10.4 which is incompatible.**

**Comment by thehesiod** [comment]
try installing with `pip -U` so that botocore will get downgraded

**Comment by jettify** [comment]
Fill free to open new issue if you have more questions
