### ISSUE TITLE
0.6.0 fail with DynamoDB

### ISSUE THREAD

**Issue by mannickutd** [aio-libs/aiobotocore#562]
return await client.get_item(TableName=self.table_name, Key={'org_id': {'S': key}})
python3.6/site-packages/aiobotocore/client.py", line 80, in _make_api_call
    operation_model, request_dict)
python3.6/site-packages/aiobotocore/endpoint.py", line 265, in _send_request
    exception)):
python3.6/site-packages/aiobotocore/endpoint.py", line 297, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
python3.6/site-packages/botocore/retryhandler.py", line 220, in __call__
    return self._check_response(attempt_number, response)
python3.6/site-packages/botocore/retryhandler.py", line 335, in _check_response
    actual_crc32 = crc32(response[0].content) & 0xffffffff
TypeError: a bytes-like object is required, not 'StreamReader'

Installed libraries
aiobotocore==0.6.0
aiohttp==3.1.3
aioresponses==0.4.1
alembic==0.9.7
astroid==1.6.1
async-timeout==2.0.1
asyncpg==0.15.0
asynctest==0.11.1
attrs==17.4.0
botocore==1.8.21
certifi==2018.1.18
chardet==3.0.4
coverage==4.4.1
Cython==0.27.3
docutils==0.14
gino==0.6.2
gunicorn==19.7.1
idna==2.6
idna-ssl==1.0.1
iso8601==0.1.12
isort==4.2.15
jmespath==0.9.3
json-logging-py==0.2
jsonschema==2.6.0
lazy-object-proxy==1.3.1
Mako==1.0.7
MarkupSafe==1.0
mccabe==0.6.1
multidict==4.2.0
packaging==17.1
psycopg2==2.7.3.2
py==1.5.2
pylint==1.8.2
pyparsing==2.2.0
pystrainer==1.3.1
pytest==3.1.3
pytest-aiohttp==0.1.3
pytest-cov==2.5.1
python-dateutil==2.7.2
python-editor==1.0.3
requests==2.18.4
requests-mock==1.4.0
six==1.11.0
SQLAlchemy==1.2.5
urllib3==1.22
uvloop==0.9.1
websockets==4.0.1
wrapt==1.10.11
yarl==1.1.1

**Comment by jettify** [comment]
@thehesiod this issue should be handled by this PR https://github.com/aio-libs/aiobotocore/pull/568 ?

**Comment by thehesiod** [comment]
fixed by https://github.com/aio-libs/aiobotocore/pull/569
