### ISSUE TITLE
Next release version 0.7.0

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#570]
We have bunch of awesome changes landed in 0.6.1 I think those deserves major version bump :) , so I suggest to have next release 0.7.0 instead of 0.6.2 . One outstanding issue for next release is to handle https://github.com/aio-libs/aiobotocore/pull/560

**Comment by thehesiod** [comment]
Oh dang, I had started 0.6.1 release, did u cancel. I agree we should do 0.7.0 instead

**Comment by jettify** [comment]
It is not big issue, no reason to cancel anything.
