### ISSUE TITLE
Documentation formatting broken on pypi.python.org

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#578]
may be related to new pypi server?

**Comment by asvetlov** [comment]
```
andrew•~/projects/aiobotocore(master)» python3 setup.py check -rms                                             [10:07:10]
running check
warning: check: Title underline too short. (line 160)

error: Please correct your package.
````

**Comment by thehesiod** [comment]
cool thanks, adding check in https://github.com/aio-libs/aiobotocore/pull/581.  @jettify  added a variant but looks like this is what matters now.

**Comment by thehesiod** [comment]
actually, that is a new line that wasn't in the release.  Only difference seems like this will also check the metadata and fail the script if the check fails

**Comment by thehesiod** [comment]
cool, closing
