### ISSUE TITLE
release py3 wheels

### ISSUE THREAD

**Issue by graingert** [aio-libs/aiobotocore#58]

**Comment by graingert** [comment]
@jettify bump

**Comment by jettify** [comment]
I will take a look, as far as i can tell we need to add `bdist_wheel` to our deploy config.

https://docs.travis-ci.com/user/deployment/pypi/

**Comment by graingert** [comment]
You can also go back and upload wheels to old releases

On 22 Feb 2017 15:08, "Nikolay Novik" <notifications@github.com> wrote:

I will take a look, as far as i can tell we need to add bdist_wheel to our
deploy config.

https://docs.travis-ci.com/user/deployment/pypi/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/aio-libs/aiobotocore/issues/58#issuecomment-281695807>,
or mute the thread

**Comment by jettify** [comment]
@graingert could you please elaborate why we should do upload of wheel for old releases? Since package is pure python, i do not see huge advantage of wheel, but may be i miss something

**Comment by graingert** [comment]
It's just something you can do. Makes stuff go faster for people on older versions

**Comment by thehesiod** [comment]
ya, I'm not seeing a benefit of using wheels, wheels are typically for modules that need to compile source files so you don't need to install the development packages on the destination box.

**Comment by graingert** [comment]
Can you at least ship a new release?

**Comment by jettify** [comment]
We do not have any significant changes for new release... I can upload wheel for current version manually, each next release will have those automatically

**Comment by graingert** [comment]
Either is fine

**Comment by jettify** [comment]
Done https://pypi.python.org/pypi?name=aiobotocore&version=0.2.1&:action=files

**Comment by graingert** [comment]
Neato thanms
