### ISSUE TITLE
How to batch write data to SQS

### ISSUE THREAD

**Issue by abuadan** [aio-libs/aiobotocore#599]
Hi is there a way to write a list of messages to sqs? there is a method for dynamodb but I don't know if that option is available for sqs  do I just use the example with a a for loop?

**Comment by jettify** [comment]
Hi, sorry for late reply, Is that option exists in botocore, if so it should be present in aiobotocore also

**Comment by thehesiod** [comment]
going to close, feel free to re-open if you have any further questions/issues.
