### ISSUE TITLE
'OperationModel' object has no attribute 'has_event_stream_output'

### ISSUE THREAD

**Issue by dabata** [aio-libs/aiobotocore#603]
all calls with dynamodb as a client fail with the following error:
```
/opt/anaconda/envs/jupyter/lib/python3.6/site-packages/aiobotocore/endpoint.py in _get_response(self, request, operation_model, attempts)
    330             # body.
    331             request.reset_stream()
--> 332             # Create a new request when retried (including a new signature).
    333             request = self.create_request(
    334                 request_dict, operation_model)

AttributeError: 'OperationModel' object has no attribute 'has_event_stream_output'
```
here is a sample code,
the non async equivalent for the following code works fine

```python
import asyncio
import aiobotocore

async def main(loop):
    session = aiobotocore.get_session(loop=loop)
    table_name = 'testTable'
    async with session.create_client('dynamodb') as client:
        response = await client.describe_table(TableName=table_name)
        print(response)

asyncio.set_event_loop(asyncio.new_event_loop())
loop = asyncio.get_event_loop()
loop.run_until_complete(main(loop))
```
aiobotocore 0.9.2

Edit: I temporarily reverted back to 0.8.0 with which there is no such issue

**Comment by thehesiod** [comment]
actually, this is included in our unittests: https://github.com/aio-libs/aiobotocore/blob/master/tests/test_dynamodb.py#L112  I think you don't have the matching botocore installed (`1.10.12`).  Can you confirm?

**Comment by thehesiod** [comment]
note if you want tools such as awscli/boto3 you need to install with our extras so they you pick up the right versions of those as well.

**Comment by dabata** [comment]
Thanks, works now with the right botocore version
