### ISSUE TITLE
Increase supported botocore version

### ISSUE THREAD

**Issue by terrisgit** [aio-libs/aiobotocore#605]
aiobotocore is working fine with botocore 1.10.48. Can you remove this warning?

aiobotocore 0.9.2 has requirement botocore<1.10.13,>=1.10.12, but you'll have botocore 1.10.48 which is incompatible.

**Comment by terrisgit** [comment]
Hm, after further research I can see that this is a generic wrapper around all of botocore3. I will try accessing the secrets manager and let you know what happens.

**Comment by askabelin** [comment]
It's not possible to install the latest boto3 and aiobotocore without warnings because botocore dependency can't be resolved:

```
boto3==1.7.57
  - botocore [required: >=1.10.57,<1.11.0, installed: 1.10.57]
aiobotocore==0.9.2
  - botocore [required: >=1.10.12,<1.10.13, installed: 1.10.57]
```

**Comment by thehesiod** [comment]
btw looks like latest version had some code code in areas we use: https://travis-ci.com/aio-libs/aiobotocore/jobs/134651598

**Comment by thehesiod** [comment]
note: not as simple as hoped as a new iterator was introduced in the `StreamReader` and since we need to support py35 it had to be un-rolled making it much more complicated :(
