### ISSUE TITLE
Consistent read timeout errors for Lambda payload read

### ISSUE THREAD

**Issue by mannickutd** [aio-libs/aiobotocore#607]
The error occurs when trying to read the data for a payload of a lambda function response. The response data size is not larger than 1KB. The error is intermittent.

```
Traceback (most recent call last):
  File \"/usr/lib/python3.6/site-packages/aiobotocore/endpoint.py\", line 157, in _wrapped_wait
    result = yield from wrapped(*args, **kwargs)
  File \"/usr/lib/python3.6/site-packages/aiohttp/streams.py\", line 259, in _wait
    yield from waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"execution_rest.py\", line 169, in post
    payload = await resp['Payload'].read()
  File \"/usr/lib/python3.6/site-packages/aiohttp/streams.py\", line 607, in read
    return (yield from super().read(n))
  File \"/usr/lib/python3.6/site-packages/aiohttp/streams.py\", line 323, in read
    block = yield from self.readany()
  File \"/usr/lib/python3.6/site-packages/aiohttp/streams.py\", line 623, in readany
    return (yield from super().readany())
  File \"/usr/lib/python3.6/site-packages/aiohttp/streams.py\", line 340, in readany
    yield from self._wait('readany')
  File \"/usr/lib/python3.6/site-packages/aiobotocore/endpoint.py\", line 158, in _wrapped_wait
    return result
  File \"/usr/lib/python3.6/site-packages/async_timeout/__init__.py\", line 45, in __exit__
    self._do_exit(exc_type)
  File \"/usr/lib/python3.6/site-packages/async_timeout/__init__.py\", line 92, in _do_exit
    raise asyncio.TimeoutError
concurrent.futures._base.TimeoutError
```

**Comment by thehesiod** [comment]
what version aiobotocore?

**Comment by thehesiod** [comment]
Ah. Can u try 0.5.2, and if that doesn't work the latest. We don't currently have a plan to support old versions

**Comment by mannickutd** [comment]
Yes the latest version fixed the issue.

**Comment by jettify** [comment]
Looks like resolved

**Comment by thehesiod** [comment]
just as FYI, with latest version I did see some potential hangs (potentially socket timeouts not working) after a few hundred thousand requests.  I'll let everyone know if I find any more details.

**Comment by mojimi** [comment]
@thehesiod Any update on this? Is lambda calls working correctly here? Can you wait asynchronously for lambda invocations? Can you post a working example?

**Comment by thehesiod** [comment]
@mojimi I haven't seen socket timeouts anymore with the latest versions.

**Comment by mojimi** [comment]
> 
> 
> @mojimi I haven't seen socket timeouts anymore with the latest versions.

Could you share some example on using it? I couldn't find any example on waiting on several lamba invocations using gather

**Comment by thehesiod** [comment]
The only waiter that seems to exist is function exists: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#id48

**Comment by mojimi** [comment]
> 
> 
> The only waiter that seems to exist is function exists: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#waiters

No by `wait` I meant `await` hehe, just wanted a simple example on how to invoke a lambda using aiobotocore

**Comment by thehesiod** [comment]
It should be the same as with botocore just you need to call with await. Is there a specific issue you're running into?

**Comment by mojimi** [comment]
> 
> 
> It should be the same as with botocore just you need to call with await. Is there a specific issue you're running into?

I hadn't try anything actually since I'm not sure which doc to follow since we're not using boto3 here.

Is it something like this?

```python
session = aiobotocore.get_session(loop=loop)
client = session.create_client('lambda')
images = [
    "http://via.placeholder.com/3000",
    "http://via.placeholder.com/3000",
    "http://via.placeholder.com/3000",
    "http://via.placeholder.com/3000",
    "http://via.placeholder.com/3000"
]
lambda_tasks = []
for image in images:
    lambda_tasks.append(
        client.invoke(
            FunctionName='imgToDataURI',
            InvocationType='RequestResponse',
            Payload=image.encode('utf-8'),
        )
    )
datauri_images = loop.run_until_complete(asyncio.gather(*lambda_tasks))
```

The idea is to call several lambdas that will return a img url as a base64 representation of the downloaded image

**Comment by thehesiod** [comment]
That should work, beware that with the regular gather if an error is raised all the other tasks continue running in the background unchecked.  I wrote some helpers for this: https://gist.github.com/thehesiod/524a1f005d0f3fb61a8952f272d8709e

btw are you aware of https://github.com/terrycain/aioboto3 ?

**Comment by mojimi** [comment]
> 
> 
> That should work, beware that with the regular gather if an error is raised all the other tasks continue running in the background unchecked. I wrote some helpers for this: https://gist.github.com/thehesiod/524a1f005d0f3fb61a8952f272d8709e
> 
> btw are you aware of https://github.com/terrycain/aioboto3 ?

Ah I  had no idea about aioboto3, thanks
