### ISSUE TITLE
generate_db_auth_token() returns a string instead of an awaitable

### ISSUE THREAD

**Issue by terrisgit** [aio-libs/aiobotocore#612]
This sets a string into the variable 'token', which does in fact work for me, but shouldn't it contain an awaitable?

session = aiobotocore.get_session()
async with session.create_client('rds', region_name=region) as client:
    token = client.generate_db_auth_token(hostname, port, username)

**Comment by thehesiod** [comment]
are you thinking because it may need to retrieve your IAM credentials?  See: https://github.com/aio-libs/aiobotocore/issues/2.  Not an easy fix, for now sync as it shouldn't take much time to get the token from AWS

**Comment by terrisgit** [comment]
I thought the point of aiobotocore was for every network access to be async. You could say "shouldn't take much time" about most AWS calls - until the network connection goes down.

**Comment by thehesiod** [comment]
yes, it does for 99% of the underlying botocore endpoints, the API in question (I believe) just relies on your AWS auth token (which is cached and refreshed when its expired iff you're using IAM creds)...from what I understand they above is like generating a presigned URL.  I'm not saying it shouldn't or won't be fixed, however that it would require re-writing large chunks of AWS code and we haven't found reason to do it yet. IOW stuff like: `s3_client.get_object` and what not are indeed async

**Comment by terrisgit** [comment]
I don't think this is accurate. If you provide a bogus region name, generate_db_auth_token will fail. That's a strong indicator that this method involves I/O.

**Comment by terrisgit** [comment]
Got it, this doesn't actually use I/O.
