### ISSUE TITLE
Broader version requirements for botocore

### ISSUE THREAD

**Issue by mmslindner** [aio-libs/aiobotocore#624]
setup.py specifies a very small range of versions for botocore:

    botocore<1.10.59,>=1.10.58

When using aiobotocore as a library, this easily leads unsolvable dependency conflicts. It would be great to allow a broader version range.

**Comment by thehesiod** [comment]
it would, but would require vendoring botocore which we do not want to do as this project should move fast and always support the latest botocore (see discussion in #626 .  Dependency conflicts should be solved via our extras, ex: aiobotocore[awscli,boto3].  Let us know if there are other conflicts!
