### ISSUE TITLE
Unclosed connection when reading data

### ISSUE THREAD

**Issue by demmsnt** [aio-libs/aiobotocore#64]
I get example https://github.com/aio-libs/aiobotocore/blob/master/examples/simple.py
replace line 28 on     
```
resp = yield from client.get_object(Bucket=bucket, Key=key)
data = yield from resp['Body'].readany()

```

And when i run this code i have message from aiohttp (i think):

> Unclosed connection

In tests https://github.com/aio-libs/aiobotocore/blob/master/tests/test_basic_s3.py#L107 i see resp['Body'].close() But if i add this line i get error AttributeError: 'FlowControlStreamReader' object has no attribute 'close'

**Comment by jettify** [comment]
That is strange, what is your aiobotocore version? could you try master?

**Comment by demmsnt** [comment]
Yes i try use github version. For example - my code. try it. http://pastebin.com/hB2GyE7M and i got files truncated 16384 bytes size. If you have a different result, tell me.... But that not only my workstation.

**Comment by jettify** [comment]
Truncated file is expected since you call `readany()` instead `read()`, what confuses me why you have access to `FlowControlStreamReader` since we are wrapping it with `ClientResponseContentProxy`. I need to debug it more carefully

**Comment by demmsnt** [comment]
Thank you. You have same result, as i understand?

**Comment by jettify** [comment]
I just executed this test, without any issues:
```
@pytest.mark.run_loop
def test_can_get_and_put_object(s3_client, create_object, bucket_name, loop):
    yield from create_object('foobarbaz', body='body contents')
    # Eventual consistency.
    yield from asyncio.sleep(3, loop=loop)

    resp = yield from s3_client.get_object(Bucket=bucket_name, Key='foobarbaz')
    data = yield from resp['Body'].readany()
    resp['Body'].close()
    assert data == b'body contents'
    assert isinstance(resp['Body'], ClientResponseContentProxy)
```
could you double check `aiobotocore` version? may be compare source code from your virtual env and current master?

**Comment by demmsnt** [comment]
i think i have version bug.

```
(env) vagrant@vagrant-ubuntu-trusty-64:~/src/tests$ python test_aibotocore_v2.py 
Traceback (most recent call last):
  File "test_aibotocore_v2.py", line 2, in <module>
    import aiobotocore
  File "/home/vagrant/src/tests/aiobotocore/__init__.py", line 1, in <module>
    from .session import get_session, AioSession
  File "/home/vagrant/src/tests/aiobotocore/session.py", line 7, in <module>
    from .client import AioClientCreator
  File "/home/vagrant/src/tests/aiobotocore/client.py", line 11, in <module>
    from botocore.client import ClientEndpointBridge
ImportError: cannot import name 'ClientEndpointBridge'

```

Can i get correct version of botocore?

**Comment by demmsnt** [comment]
Maybe in requirements need mention correct version botocore?

**Comment by jettify** [comment]
yeah, already did

**Comment by jettify** [comment]
version should be ok:
```
install_requires = ['botocore>=1.4.0, <=1.4.28', 'aiohttp>=0.21.2']
```

**Comment by demmsnt** [comment]
Fixed. Version trouble.... Sorry for took time..

**Comment by jettify** [comment]
not a problem

**Comment by demmsnt** [comment]
But if i use readany i have truncated data. With read all good.
