### ISSUE TITLE
Sync readthedocs page

### ISSUE THREAD

**Issue by and800** [aio-libs/aiobotocore#641]
It seems that [the docs build](https://aiobotocore.readthedocs.io/en/latest/index.html) is out of sync. It doesn't include the latest changes in docs code, for example, native coroutines in examples page.

**Comment by thehesiod** [comment]
@jettify how is this done?  Can we add this to our contributing page or somehow make this automated?

**Comment by thehesiod** [comment]
hmm, seems to all be there: https://aiobotocore.readthedocs.io/en/latest/examples.html

**Comment by willingc** [comment]
@thehesiod Looks up to date yet the RTD build is failing. I've opened PR #672 to correct.
