### ISSUE TITLE
Status of aiobotocore

### ISSUE THREAD

**Issue by gricey432** [aio-libs/aiobotocore#652]
Just found this and it looks like exactly what I need, but it looks like it's unmaintained / approaching being unmaintained.

I'm basing this off PR #639 and the fact there's been one commit in the last 4 months. Is aibotocore still an active project which will continue to track botocore into the future?

**Comment by jettify** [comment]
Project is sort of active, we try to maintain it when have free time or inspiration (sorry we can not guaranty anything more, this is open source), looks like recently we dropped the ball there. We always looking for volunteers and active contributors to make project more active. 

As for #639 PR is merged and new version is released.

**Comment by gricey432** [comment]
Awesome! Totally understand it's OSS, just always good to be sure a project isn't dead before starting a new project that relies on it :+1:

**Comment by thehesiod** [comment]
This was my fault, for some reason I didn't get notifications on that PR. I normally try to review w/in a few days

**Comment by jettify** [comment]
Good news, @terrycain (aiomysql maintainer and contributor of #639 PR) volunteered to help me and @thehesiod with support of aiobotocore. We should be more responsive in future since more people looking after this project.
