### ISSUE TITLE
Is it possible to upload to s3 asynchronously by chunks?

### ISSUE THREAD

**Issue by py-radicz** [aio-libs/aiobotocore#658]
What I am trying to do: I want to download file from remote source and upload it directly to s3 without storing the bytes on the localhost. (Stream the data from remote machine through my machine to s3). There are tens of files in remote location, thats why I want to use async lib, to stream all files simultaneously to save time.

Is it possible with current version of lib to do something like following?

```python
async with aioboto3.client('s3', loop=loop) as client:
    async for chunk in response.content.iter_chunked(1024):
        if chunk:
            # await put chunk into appropriate file handle on s3
```

Thanks for some pointers.

**Comment by thehesiod** [comment]
I'm interested in your findings, let me know if you need some pointers

**Comment by thehesiod** [comment]
ok, working on this now, will require some support

**Comment by thehesiod** [comment]
omg, this is another painful thing.  So first thing needed was adding:
```python
    def tell(self):
        return self._self_amount_read
```
to `StreamingBody`.

Next issue is that the falling callstack needs to be async:
```
    await s3_client.put_object(Bucket='thehesiod-temp', Key='latitude.csv', Body=get_response["Body"])
  File "aiobotocore/aiobotocore/client.py", line 86, in _make_api_call
    request_signer=self._request_signer, context=request_context)
  File "botocore/hooks.py", line 360, in emit_until_response
    return self._emitter.emit_until_response(aliased_event_name, **kwargs)
  File "botocore/hooks.py", line 243, in emit_until_response
    responses = self._emit(event_name, kwargs, stop_on_response=True)
  File "botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "botocore/handlers.py", line 211, in conditionally_calculate_md5
    calculate_md5(params, **kwargs)
  File "botocore/handlers.py", line 189, in calculate_md5
    binary_md5 = _calculate_md5_from_file(body)
```

This is similar in complexity to https://github.com/aio-libs/aiobotocore/issues/619

**Comment by thehesiod** [comment]
ugh, I found that if you do something like:
```python
    boto_session = aiobotocore.session.AioSession()

    async with (await boto_session.create_client('s3')) as s3_client:
        get_response = await s3_client.get_object(Bucket=BUCKET, Key='KEY)

        await s3_client.put_object(Bucket=BUCKET, Key=KEY, Body=get_response["Body"])
```

botocore reads the whole file to calculate an MD5 of the file, so you won't save anything in terms of memory usage.

**Comment by thehesiod** [comment]
@py-radicz could you come up with a botocore solution, I can then try to get it working in aiobotocore.  What I have in my PR I don't think streams as I believe the PutObject doesn't support streaming bodies: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html  seems like it requires a `Content-Length`.

**Comment by py-radicz** [comment]
Hey, thanks for the quick response, I was also unsuccessful with aiobotocore/botocore with what I wanted. 

For anyone interested I have solved the issue using aiohttp + s3fs (which isnt async but read on)

```python

FS = s3fs.S3FileSystem(anon, key, secret)
async with session.get(url) as r:
        chunksize = 1024 * 32
        with FS.open(file, "wb") as f:
            async for chunk in r.content.iter_chunked(chunksize):
                if chunk:
                    f.write(chunk)
                    # this f.write is blocking, chunksize isnt too big, so the async is still kind of leveraged, while using to download from multiple urls at the same time 
```

**Comment by thehesiod** [comment]
Can probably do an multipart upload, have you tried that? You can then do everything in aiobotocore I think

**Comment by thehesiod** [comment]
please see #618, @terrycain described this should be done in aioboto3

**Comment by tingyiy** [comment]
multipart has min 5MB limit. s3fs does not support custom headers (cache control acl etc)

**Comment by thehesiod** [comment]
lets continue discussionon https://github.com/aio-libs/aiobotocore/issues/746
