### ISSUE TITLE
[infra] come up with file stream support strategy

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#666]
based on conversation in https://github.com/aio-libs/aiobotocore/pull/67

**Comment by thehesiod** [comment]
as a reminder, you need all the bytes to be able to sign the AWS API body before sending the data...which makes incremental reading much less interesting. The async incremental reading should be done before calling aiobotocore. I'm going to close this unless there's a good use-case presented.

**Comment by terrycain** [comment]
Yeah in the case of uploading large files to s3, they should be done multipart instead of put-object (for reference of anyone who lands here)

**Comment by thehesiod** [comment]
actually I just remembered the useful case is supporting files so you don't need to keep the whole file in memory
