### ISSUE TITLE
Consider integration tests using minio

### ISSUE THREAD

**Issue by rgbkrk** [aio-libs/aiobotocore#668]
We've had some good success in [`bookstore`](https://github.com/nteract/bookstore) using an [extra container with minio running for integration testing on CircleCI](https://github.com/nteract/bookstore/blob/196d7c06555a2194008c094d0365b4c0832662e8/.circleci/config.yml#L11-L16). Would you all be interested in using CircleCI + a minio server? I'm happy to contribute something now that we're planning to switch off of `s3fs` to `aiobotocore` https://github.com/nteract/bookstore/issues/32.

That is, unless you have integration tests you're running against S3 I'm unaware of.

**Comment by thehesiod** [comment]
I'm unaware of minio, it has a backend compatible with S3 APIs?

**Comment by rgbkrk** [comment]
Yup, https://minio.io/ is an S3 compatible object store. It can be run in a docker container.

**Comment by thehesiod** [comment]
ah, hmm, given it's s3 compatible, as long as we maintain s3 compatibility it should work, any issues would almost be definition be an issue with botocore or minio so I'm not sure this would be the right place for those tests.  thoughts?

**Comment by thehesiod** [comment]
or, an issue with the adapter, in which case we should repro with S3 tests w/ moto.  We already know of one gaping hole, see open issues.  Help wanted if that affects you! :)

**Comment by rgbkrk** [comment]
> any issues would almost be definition be an issue with botocore or minio so I'm not sure this would be the right place for those tests

Yeah I now see how you're wrapping `botocore` so it would likely be a silly suite of tests. We'll keep on with our integration tests using `minio`. 😄
