### ISSUE TITLE
[UNITTESTS] Add test to ensure awscli + boto3 + botocore requirements match

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#670]

**Comment by timsavage** [comment]
With the latest boto3 installed you currently get a dependency failure caused by pip trying to resolve a version that will match: <1.12.92,<1.13.0,>=1.12.127,>=1.12.91

Which will never happen.

**Comment by terrycain** [comment]
Not using much brain power here but couldn't we run a travis test that installs `aiobotocore[boto3]` then run pipdeptree (or similar) and see if its exits 0?

**Comment by pford221** [comment]
It appears as if there is a conflict between version 1.1.0 of this package and the latest version of boto3 (1.14.47). Here the requirement for botocore is `botocore<1.17.45,>=1.17.44`. But boto3 requires `botocore>=1.17.47,<1.18.0`. These are incompatible at the moment.

**Comment by thehesiod** [comment]
checking

**Comment by thehesiod** [comment]
@pford221 you need to install `aiobotocore[boto3]`, 1.1.0 is locked to boto3 `1.14.44` which itself is locked to `botocore>=1.17.44`

**Comment by thehesiod** [comment]
added this test at some point in test_version.py
