### ISSUE TITLE
AttributeError: 'str' object has no attribute 'hyphenize'

### ISSUE THREAD

**Issue by oba11** [aio-libs/aiobotocore#674]
On update of aiobotocore to 0.10.0, started getting below error

```
'str' object has no attribute 'hyphenize': AttributeError
Traceback (most recent call last):
File "/var/task/s3_event_watcher.py", line 72, in handler
db = DynamoDB(loop, table_name)
File "/var/task/chalicelib/dynamodb.py", line 50, in __init__
'dynamodb', region_name=region, **dynamo_kwargs)
File "/var/task/aiobotocore/session.py", line 76, in create_client
client_config=config, api_version=api_version)
File "/var/runtime/botocore/client.py", line 70, in create_client
cls = self._create_client_class(service_name, service_model)
File "/var/task/aiobotocore/client.py", line 49, in _create_client_class
service_id = service_model.service_id.hyphenize()
AttributeError: 'str' object has no attribute 'hyphenize'
```

Rolling back to 0.9.4 resolves this error

**Comment by oba11** [comment]
My requirements.txt looks like below

```
aiobotocore[boto3]==0.10.0
```

Changing my requirements.txt to `aiobotocore[boto3]==0.9.4` resolves it so I think its likely the updated version was pinned to the right `botocore` version.

**Comment by thehesiod** [comment]
the error you stated is a typical problem with mismatched botocore module.  was this in an empty virtualenv or did it already have other module installed.  Please list `pip3 freeze` results.

I just tried and it worked fine.

```
amohr@amohr-macbook /tmp $ pipenv shell
Creating a virtualenv for this project…
Pipfile: /private/tmp/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 (3.7.2) to create virtualenv…
amohr@amohr-macbook /tmp $  . /Users/amohr/.local/share/virtualenvs/tmp-agwWamBd/bin/activate
...
(tmp) amohr@amohr-macbook /tmp $ pip list
Package    Version
---------- -------
pip        18.1   
setuptools 40.6.3 
wheel      0.32.3 
(tmp) amohr@amohr-macbook /tmp $ pip install aiobotocore
...
Successfully installed aiobotocore-0.10.0 aiohttp-3.3.2.2 async-timeout-3.0.1 attrs-18.2.0 botocore-1.12.49 chardet-3.0.4 docutils-0.14 idna-2.8 jmespath-0.9.3 multidict-4.5.2 python-dateutil-2.7.5 six-1.12.0 urllib3-1.24.1 wrapt-1.11.1 yarl-1.3.0
(tmp) amohr@amohr-macbook /tmp $ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiobotocore.session
>>> session = aiobotocore.session.Session(profile='thehesiod')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiobotocore.session' has no attribute 'Session'
>>> session = aiobotocore.session.AioSession(profile='thehesiod')
>>> client = session.create_client('dynamodb')
```

**Comment by oba11** [comment]
I'm actually using a lambda function.

My best guess is because of the botocore requirement in the  `boto3==1.9.49` which is `botocore>=1.12.49,<1.13.0` but was set as `botocore>=1.12.49,<1.12.50` in aiobotocore.

**Comment by thehesiod** [comment]
I just tried again installing in a fresh venv `aiobotocore[boto3]` and still did not repo, please provide reproducible test case or return results of `pip list` or I'll have to close this as there's no way for us to help you.  There's a myriad of things that could be happening in the lambda.

**Comment by oba11** [comment]
I've the able to figure the issue, this wasnt an issue with `aiobotocore` library or lambda but the way I do package/deploy my serverless app. 

Do use [serverless-python-requirements](https://www.npmjs.com/package/serverless-python-requirements) for packaging my serverless apps but I wasnt aware that the serverless-module [excludes](https://github.com/UnitedIncome/serverless-python-requirements#omitting-packages) `boto3` and `botocore` packages during deployment. Removing `boto3` and `botocore` from the default ommitted packages resolved this.

Apologies for the confusion and thanks alot for assisting with figuring out the issue.
