### ISSUE TITLE
Athena queries don't run asynchronously when using aiobotocore and asyncio

### ISSUE THREAD

**Issue by brentEich** [aio-libs/aiobotocore#687]
**Bug Description**
I receive no error when running the code below, however the code does not run asynchronously as the timings of the queries do not occur altogether. Am I missing some code or am I including code which should not be present.

**Checklist**
- [ X ] I have reproduced in environment where `pip check` passes without errors
- [ X ] I have provided `pip freeze` results
- [ X ] I have provided sample code or detailed way to reproduce

**pip freeze results**
```
aiobotocore==0.10.2
botocore==1.12.91
awscli==1.16.101
```

**Environment:**
 - Python Version: 3.6.7
 - OS name and version: Ubuntu 18.04, Bionic Beaver

**Additional context**
The aim of this code is to fire 10 or more queries off asynchronously using AWS athena's _start_query_execution_.

```
import aiobotocore
import botocore

query_list = [
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;'
]
```

```
async def go(loop):
    Database =  db
    OutputLocation =  outputlocation
    QueryString = query_list

    session = aiobotocore.get_session(loop=loop)
    async with session.create_client('athena') as client:
        
        #run athena query
        for query in query_list:
            response = await client.start_query_execution(
                QueryString = query,
                QueryExecutionContext = {
                    'Database': Database
                },
                ResultConfiguration = {
                    'OutputLocation': OutputLocation
                }
            )
            print(response)
loop = asyncio.get_event_loop()
loop.run_until_complete(go(loop))

```

**Comment by thehesiod** [comment]
I think you meant to do this?
```python
import asyncio
import aiobotocore
import botocore

query_list = [
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;',
    'SELECT * FROM table LIMIT 1;'
]

async def dowork(client, **kwargs):
    response = await client.start_query_execution(**kwargs)
    print(response)


async def go(loop):
    Database =  db
    OutputLocation =  outputlocation
    QueryString = query_list

    session = aiobotocore.get_session(loop=loop)
    async with session.create_client('athena') as client:
        #run athena queries
        await asyncio.gather(*[
            dowork(client, QueryString = query,
                QueryExecutionContext = {
                    'Database': Database
                },
                ResultConfiguration = {
                    'OutputLocation': OutputLocation
                })
            for query in query_list
        ])

loop = asyncio.get_event_loop()
loop.run_until_complete(go(loop))
```

be careful with gather as after the first task throws an exception, the method will raise and the rest of the task will keep executing

**Comment by brentEich** [comment]
> I think you meant to do this?
> 
> ```python
> import asyncio
> import aiobotocore
> import botocore
> 
> query_list = [
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;',
>     'SELECT * FROM table LIMIT 1;'
> ]
> 
> async def dowork(client, **kwargs):
>     response = await client.start_query_execution(**kwargs)
>     print(response)
> 
> 
> async def go(loop):
>     Database =  db
>     OutputLocation =  outputlocation
>     QueryString = query_list
> 
>     session = aiobotocore.get_session(loop=loop)
>     async with session.create_client('athena') as client:
>         #run athena queries
>         await asyncio.gather(*[
>             dowork(client, QueryString = query,
>                 QueryExecutionContext = {
>                     'Database': Database
>                 },
>                 ResultConfiguration = {
>                     'OutputLocation': OutputLocation
>                 })
>             for query in query_list
>         ])
> 
> loop = asyncio.get_event_loop()
> loop.run_until_complete(go(loop))
> ```
> 
> be careful with gather as after the first task throws an exception, the method will raise and the rest of the task will keep executing

Many thanks to you @thehesiod! This worked perfectly for me. All the queries fired together.
