### ISSUE TITLE
document how to get back a file from s3

### ISSUE THREAD

**Issue by allan-simon** [aio-libs/aiobotocore#69]
I've just helped somebody answering "how to get a file from s3 and iterate over it line by line"  in stackoverflow there 

http://stackoverflow.com/questions/40203620/aiobotocore-aiohttp-get-s3-file-content-and-stream-it-in-the-response/40204293#40204293

and it's only looking in the source code  and this pull request https://github.com/aio-libs/aiobotocore/pull/19 
that's I've been able to answer it.

I think getting a file from s3 is common enough to see it in the readme. if the piece of code I provided in SO is clear enough, I will propose a PR in the readme

**Comment by asvetlov** [comment]
@jettify ?

**Comment by thehesiod** [comment]
added to homepage

**Comment by allan-simon** [comment]
thanks :)
