### ISSUE TITLE
Reading multiple bulked jsons from s3 asynchronously, is there a better way?

### ISSUE THREAD

**Issue by LeonardAukea** [aio-libs/aiobotocore#694]
Hi all, I asked this question on stackoverflow https://stackoverflow.com/questions/55765219/reading-multiple-bulked-jsons-from-s3-asynchronously-is-there-a-better-way. 

Unfortunately, I could not tag `aiobotocore`.
I'm very unfamiliar with `asyncio`. But I decided it would be fun to try out your library. Since I may possibly have a use case for it. If any of you maintainers have any suggestions or improvements on the code. It would be much appreciated. 

* Basically, I think of two things. Is it really good practice to create a client in each  async function? Maybe it should be lifted out.
* Could I possibly start getting the object as soon as a key is loaded insted of `await`until all keys are loaded `async generator`?

If you have time, your help would be much appreciated. I have a huge amount of jsons in an s3 bucket which I need to load efficiently.

Here is the code:

Imports:

```python
import os 
import asyncio
import aiobotocore
from itertools import chain
import json
from json.decoder import WHITESPACE
```

Some helper generator I found somewhere to return decoded jsons from string with multiple jsons.

```python
def iterload(string_or_fp, cls=json.JSONDecoder, **kwargs):
    '''helper for parsing individual jsons from string of jsons (stolen from somewhere)'''
    string = str(string_or_fp)

    decoder = cls(**kwargs)
    idx = WHITESPACE.match(string, 0).end()
    while idx < len(string):
        obj, end = decoder.raw_decode(string, idx)
        yield obj
        idx = WHITESPACE.match(string, end).end()
```
This function gets keys from an s3 bucket with a given prefix:
```python
# Async stuff starts here
async def get_keys(loop, bucket, prefix):
    '''Get keys in bucket based on prefix'''

    session = aiobotocore.get_session(loop=loop)
    async with session.create_client('s3', region_name='us-west-2',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID) as client:
        keys = []
        # list s3 objects using paginator
        paginator = client.get_paginator('list_objects')
        async for result in paginator.paginate(Bucket=bucket, Prefix=prefix):
            for c in result.get('Contents', []):
                keys.append(c['Key'])
        return keys
```
This function gets the content for a provided key. Untop of that it flattens the list of decoded content:

```python
async def get_object(loop,bucket, key):
    '''Get json content from s3 object'''
    session = aiobotocore.get_session(loop=loop)
    async with session.create_client('s3', region_name='us-west-2',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID) as client:


        # get object from s3
        response = await client.get_object(Bucket=bucket, Key=key)
        async with response['Body'] as stream:
            content = await stream.read()    

    return list(iterload(content.decode()))
```       
Here is the main function which gathers the contents for all the found keys and flattens the list of contents.
```python
async def go(loop, bucket, prefix):
    '''Returns list of dicts of object contents'''
    session = aiobotocore.get_session(loop=loop)
    async with session.create_client('s3', region_name='us-west-2',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID) as client:

        keys = await get_keys(loop, bucket, prefix)

        contents = await asyncio.gather(*[get_object(loop, bucket, k) for k in keys])     

        return list(chain.from_iterable(contents))
```
Finally, I run this and the result list of dicts ends up nicely in result
```python
loop = asyncio.get_event_loop()
result = loop.run_until_complete(go(loop, 'some-bucket', 'some-prefix'))
```

**Comment by LeonardAukea** [comment]
I think, a simplified version of this could be a good as an example as well #288. It was not and still isn't completely obvious to me how to best use this library.  I'd be willing to clean this up and remove eg. the `iterload` stuff to make it more clear and  less confusing.

**Comment by thehesiod** [comment]
Just answered: https://stackoverflow.com/questions/55765219/reading-multiple-bulked-jsons-from-s3-asynchronously-is-there-a-better-way/55780438#55780438

**Comment by LeonardAukea** [comment]
@thehesiod Using your approach actually leads to this happening once in a while `ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)` which leads to data not being loaded. Not sure why it is happening, But it's not super stable.

**Comment by thehesiod** [comment]
Can you tell us a pip freeze plus python version and what platform and openssl version you're using?

**Comment by thehesiod** [comment]
FYI we do millions of these requests each day with this method. May be a bad aiohttp release/python combo

**Comment by LeonardAukea** [comment]
Ok, sorry. I did not use the exact same method. it was when I tired to use it with https://github.com/MagicStack/uvloop:

````
import uvloop

asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())
```

So it works as expected otherwise but it does not seem to work unless you use the built in EventLoop

**Comment by thehesiod** [comment]
I'll report the issue to uvloop then

**Comment by LeonardAukea** [comment]
```
ProductName:	Mac OS X
ProductVersion: 10.14.5
BuildVersion:	18F118d
OpenSSL 1.1.1b  26 Feb 2019

aiobotocore==0.10.2
aiohttp==3.5.4
appnope==0.1.0
async-generator==1.10
async-timeout==3.0.1
asyncpool==1.0
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
botocore==1.12.91
certifi==2019.3.9
chardet==3.0.4
conda==4.3.16
decorator==4.4.0
defusedxml==0.6.0
docutils==0.14
entrypoints==0.3
idna==2.8
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
Jinja2==2.10.1
jmespath==0.9.4
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
jupyterlab==0.35.4
jupyterlab-server==0.2.0
MarkupSafe==1.1.1
mistune==0.8.4
multidict==4.5.2
nbconvert==5.4.1
nbformat==4.4.0
nest-asyncio==1.0.0
notebook==5.7.8
pandocfilters==1.4.2
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prometheus-client==0.6.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycosat==0.6.3
Pygments==2.3.1
pyrsistent==0.14.11
python-dateutil==2.8.0
pyzmq==18.0.1
requests==2.21.0
ruamel.yaml==0.15.94
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
urllib3==1.24.2
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.1
yarl==1.3.0
```

Actually, it is still acting up at least in a notebook environment. First I tried with https://github.com/erdewit/nest_asyncio and it worked fine. but it is supposed to be not needed anymore due to the implementation of `%autoawait`. It seems to not only be a `uvloop` issue. I suspect it has something to do with the implementation of jupyter and ipykernel which runs in a async loop.

**Comment by thehesiod** [comment]
uhh, something like nested event loops, which is not supported by the base python version is almost guaranteed to break stuff

**Comment by thehesiod** [comment]
have you tried 3.7.3?  Also are you using a brewed, official, or custom install of python?  Can you try with botocore with threads?  I wonder if this is a missing retry exception class: https://github.com/boto/botocore/blob/develop/botocore/retryhandler.py#L31 which we extend here: https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/endpoint.py#L35

**Comment by LeonardAukea** [comment]
I'm using `pyenv` which I've installed via brew to manage my pythons. So I've ran this with python 3.7.3. The `SSL Handshake` issue seems to multiply when I have a higher number of workers. Also, memory is reaching the limit at this point. Maybe  it just needs to be tuned correctly. Is there a later release than `aiobotocore==0.10.2`?

**Comment by thehesiod** [comment]
looks like your issue is this: https://github.com/aio-libs/aiohttp/issues/3535

**Comment by thehesiod** [comment]
try downgrading to aiohttp 3.3.2, that's what we're using in prod

**Comment by thehesiod** [comment]
oh, and we're not running 3.7 in prod yet with aiohttp, only 3.6

**Comment by LeonardAukea** [comment]
> try downgrading to aiohttp 3.3.2, that's what we're using in prod

At least this didn't help. I'll try with python 3.6 as well.

**Comment by thehesiod** [comment]
so I'm going to close this as this issue has morphed.  Can you gather your findings into a new issue with the following taking into account:

1.  If the SSL issue is being retried we're behaving normally.
2.  If the SSL issue happens in botocore and is not being retried there as well it's a botocore issue.
3.  If the issue happens w/ raw asyncio sockets it's an asyncio issue
4. If the issue happens w/ raw aiohttp it's an aiohttp issue

If you don't have time to investigate the various issues and  it's not no. 1 then please open a new bug with all the info required and method to repro and we can investigate.  I have a feeling it's going to be dependent on specific combos of python + aiohttp and perhaps version of openssl and platform.

thanks!

**Comment by LeonardAukea** [comment]
@thehesiod yeah that's fine. I will try to find some time during the weekend to test some more.   I'll keep you posted.
