### ISSUE TITLE
Support virtual-hosted style for s3 presigned URLs

### ISSUE THREAD

**Issue by TheDirtyGambit** [aio-libs/aiobotocore#700]
With the new AWS forum post: https://forums.aws.amazon.com/ann.jspa?annID=6776
announcing no longer supporting path-style API requests.

Using:
`async with aws.create_s3_client() as client:
            return client.generate_presigned_url('put_object', Params={
                'Bucket': Bucket, 'Key': Key}, ExpiresIn=3600, HttpMethod='PUT')`

returns a path-style presigned url:
`http://aws_address/test/TestImage.jpeg?AWSAccessKeyId=test&Signature=blah&Expires=1557345465`

I am curious if there is a way already supported that returns virtual-hosted style presigned URLs? If not a new improvement would be required to be able to support this  

**Environment:**
 - Python Version: python:3.7
 - OS name and version: alpine3.9

**Comment by thehesiod** [comment]
this is how I'm doing things because otherwise it fails for keys that include `~`:   
```python
config = AioConfig(s3={'addressing_style': 'path'}, signature_version='s3v4')
```

we support everything that botocore supports, so we shouldn't need to do anything

**Comment by thehesiod** [comment]
closing as this isn't an aiobotocore issue.  Feel free to re-open if you don't feel this is the case!

btw, I think my issue is actually a bug in botocore, one day I may open a bug :)
