### ISSUE TITLE
Reading from response body outside of client context can hang without warning

### ISSUE THREAD

**Issue by mpacer** [aio-libs/aiobotocore#710]
**Describe the bug**
Reading `aiobotocore.response.StreamingBody` outside of the s3.client context manager sometimes hangs forever and does not raise a warning.

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
-  I have tried the same code in botocore to ensure this is a aiobotocore specific issue
(I did not reproduce in botocore because there are no APIs in botocore that use asyncio's async/await syntax for coroutines.) 

**pip freeze results**
adal==1.2.0
aioboto3==6.1.0
aiobotocore==0.10.2
aiohttp==3.5.4
alabaster==0.7.10
alembic==1.0.10
-e git+https://github.com/mpacer/allofplos.git@031b02c75e150ce3150130d3545250b62461a60c#egg=allofplos
ansiwrap==0.8.3
appdirs==1.4.3
appnope==0.1.0
arrow==0.12.1
asn1crypto==0.24.0
astcheck==0.2.5
async-generator==1.10
async-timeout==3.0.1
asyncio==3.4.3
atomicwrites==1.3.0
attrs==17.4.0
aws-xray-sdk==0.95
azure-datalake-store==0.0.36
azure-nspkg==3.0.2
Babel==2.6.0
backcall==0.1.0
backoff==1.7.1
bcrypt==3.1.4
bdp-boto==0.0.24
binaryornot==0.4.4
black==18.9b0
bleach==2.1.3
-e git+https://github.com/mpacer/bookstore.git@5937d0f9bdf17fe61d215af05a216d608e4545ab#egg=bookstore
boto==2.48.0
boto3==1.9.91
botocore==1.12.91
cachetools==3.0.0
cairocffi==0.9.0
CairoSVG==2.2.1
certifi==2019.3.9
certipy==0.1.3
cffi==1.11.5
chardet==3.0.4
check-manifest==0.37
click==6.7
codecov==2.0.15
commonmark==0.9.0
cookiecutter==1.6.0
cookies==2.2.1
coverage==4.5.1
cryptography==2.4.2
cssselect2==0.2.1
cycler==0.10.0
damnpth==0.1
datashape==0.5.2
decorator==4.3.0
defusedxml==0.5.0
-e git+https://github.com/mpacer/disp.git@2b604763ccacac0c1e3fcaa1b8c43cf10fec577c#egg=disp
-e git+https://github.com/mpacer/display_xml.git@62457642760b8c749d2f9416f5754c26b0d80ee8#egg=display_xml
dnspython==1.16.0
docker==3.3.0
docker-pycreds==0.2.3
docutils==0.14
entrypoints==0.2.3
flake8==3.6.0
flit==1.0
future==0.16.0
gcsfs==0.1.2
gdata==2.0.18
-e git+https://github.com/mpacer/ghpro.git@c39b03f1300d0fe18e7cd1a8bf1566973708b37c#egg=ghpro
gitdb2==2.0.3
GitPython==2.1.10
google-api-python-client==1.7.6
google-auth==1.6.1
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.2.0
grave==0.0.3
grpcio==1.17.0
gspread==3.1.0
html5lib==1.0.1
httplib2==0.12.0
idna==2.6
idna-ssl==1.1.0
imagesize==1.0.0
importlib-metadata==0.18
ipaddress==1.0.22
ipdb==0.12
ipykernel==5.1.0
ipython==7.6.1
ipython-genutils==0.3.0.dev0
ipywidgets==7.2.1
jedi==0.12.0
Jinja2==2.10
jinja2-time==0.2.0
jmespath==0.9.3
jprops==2.0.2
jsondiff==1.1.1
jsonpickle==0.9.6
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-conf-search==0.4.4
-e git+https://github.com/mpacer/jupyter_config.git@281d6cf26905e52ec657085c9c1b3591de1d1bab#egg=jupyter_config
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
-e git+https://github.com/mpacer/jupyter_contrib_nbextensions.git@640a7d56699c5197f7090fe90de446d0440a1cc5#egg=jupyter_contrib_nbextensions
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
-e git+https://github.com/mpacer/jupyter_kernel_mgmt.git@3feffc9bc6950d0ec85ae983d7caeb93ebe76459#egg=jupyter_kernel_mgmt
jupyter-kernel-test==0.3
-e git+https://github.com/mpacer/jupyter_latex_envs.git@28b78d76b6c7057c794bfbaa7f86a95b2439d0fe#egg=jupyter_latex_envs
-e git+https://github.com/mpacer/jupyter_nbextensions_configurator.git@4196509100010a65ed4591624d557c4f99302a9f#egg=jupyter_nbextensions_configurator
-e git+https://github.com/mpacer/jupyter_protocol.git@2f91291a92ff097fe292f69b812702e2fe6950af#egg=jupyter_protocol
jupyter-server-proxy==1.0.1
jupyter-ssh-kernels==0.1
jupyterhub==1.0.0
-e git+https://github.com/mpacer/jupyterlab.git@c7720675caa37b68dae42539d80f0fccda01392b#egg=jupyterlab
jupyterlab-launcher==0.11.0
keyring==12.2.1
kiwisolver==1.0.1
lxml==4.2.4
m2r==0.2.1
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.3
mock==2.0.0
more-itertools==4.1.0
moto==1.2.0
mpacer-hello-pypi==1.2.3
mpmath==1.0.0
multidict==4.5.2
multipledispatch==0.6.0
music21==5.3.0
mypy==0.660
mypy-extensions==0.4.1
-e git+https://github.com/mpacer/nbconvert.git@48015d036da9bc2b09eb6bcd45d28b1262c8e6a7#egg=nbconvert
nbformat==4.4.0
networkx==2.3
nltk==3.4.1
nose==1.3.7
-e git+https://github.com/mpacer/notebook.git@eea37a6b2110e0b8a5491f17e241fa3c8aecb5f7#egg=notebook
-e git+https://github.com/mpacer/nteract.git@d79aa32a6da0b437afb230fe69068ab49b017389#egg=nteract_on_jupyter&subdirectory=applications/jupyter-extension
-e git+https://github.com/mpacer/scrapbook.git@89efee8ff39eb46f8c4fa2c15b79e6f1e7d19a1d#egg=nteract_scrapbook
numpy==1.14.3
oauth2client==4.1.3
oauthlib==3.0.1
odo==0.3.1
packaging==17.1
pamela==1.0.0
pandas==0.22.0
pandocfilters==1.4.2
-e git+https://github.com/mpacer/papermill.git@59641ed4dc45a883ff21692fd2781d8d628ce1dd#egg=papermill
paramiko==2.4.1
parso==0.2.0
pbr==4.0.4
peewee==3.6.4
pexpect==4.5.0
pickleshare==0.7.4
Pillow==5.2.0
pkginfo==1.4.2
plotly==3.8.1
pluggy==0.12.0
pockets==0.7.2
poyo==0.4.1
prometheus-client==0.2.0
prompt-toolkit==2.0.4
protobuf==3.6.1
ptyprocess==0.5.2
py==1.5.3
py4j==0.10.6
pyaml==17.12.1
pyarrow==0.11.1
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pyconfigurator==0.4.14
pycparser==2.18
pycrypto==2.6.1
pyflakes==2.0.0
Pygments==2.2.0
PyJWT==1.6.4
PyNaCl==1.2.1
pyOpenSSL==18.0.0
pyparsing==2.2.0
pyspark==2.3.0
pystache==0.5.4
pytest==4.6.3
pytest-asyncio==0.10.0
pytest-cov==2.5.1
pytest-mock==1.10.0
python-dateutil==2.7.2
python-editor==1.0.4
python-language-server==0.18.0
python-Levenshtein==0.12.0
python-utils==2.3.0
pytoml==0.1.14
pytz==2018.4
PyYAML==3.12
pyzmq==17.0.0
readme-renderer==24.0
recommonmark==0.5.0
regex==2018.7.11
reportlab==3.5.9
requests==2.20.0
requests-cache==0.4.13
requests-download==0.1.2
requests-oauthlib==1.0.0
requests-toolbelt==0.8.0
responses==0.9.0
retry==0.9.2
retrying==1.3.3
rise==5.5.0
rope==0.12.0
rsa==4.0
s3fs==0.1.5
s3transfer==0.2.1
scipy==1.1.0
seaborn==0.9.0
selenium==3.13.0
Send2Trash==1.5.0
simpervisor==0.3
simple-crypt==4.1.7
simplegeneric==0.8.1
six==1.11.0
smmap2==2.0.3
snowballstemmer==1.2.1
-e git+https://github.com/mpacer/sphinx.git@bce956d357b7cf988c8ed42b7d82ff6f80b115ab#egg=Sphinx
sphinx-rtd-theme==0.4.1
sphinxcontrib-github-alt==1.0
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-napoleon==0.7
sphinxcontrib-openapi==0.4.0
sphinxcontrib-websupport==1.1.0
SQLAlchemy==1.2.15
sqlparse==0.2.4
svglib==0.8.1
-e git+https://github.com/mpacer/sympy.git@2961d8f076b742919d4a6fbe99a94d3cf5e46f9c#egg=sympy
tabulate==0.8.2
terminado==0.8.1
testpath==0.3.1
textwrap3==0.9.1
tinycss2==0.6.1
toml==0.10.0
toolz==0.9.0
toree==0.2.0
tornado==5.1.1
tox==3.0.0
tqdm==4.31.1
traitlets==4.3.2
twine==1.13.0
typed-ast==1.2.0
typing-extensions==3.7.2
Unidecode==1.0.22
uritemplate==3.0.0
urllib3==1.24.1
-e git+https://github.com/mpacer/vdom.git@eb246ea306956cfc11315d3f42da54c5f6abc4ab#egg=vdom
virtualenv==16.0.0
Wand==0.4.4
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.48.0
Werkzeug==0.14.1
whichcraft==0.4.1
widgetsnbextension==3.2.1
wordcloud==1.5.0
wrapt==1.10.11
xmltodict==0.11.0
yarl==1.3.0
zipp==0.5.1

**Environment:**
 - Python Version: 3.6
 - OS name and version: macOS 10.13.6

**Additional context**

In bookstore (a extension to the Jupyter server that allows more easily interacting with S3), we currently get the response back and assign it to a response object that we then pass around to use in other methods. In one of those other methods, we then read the content of the response body with [`await obj['Body'].read()`](https://github.com/nteract/bookstore/blob/19f0f78d6b9aa2356e5a98bed5bcf3ed73c8e00f/bookstore/clone.py#L271).

In our integration tests, we use a local minio container to mock an s3 server. In that context, this calling `await obj['Body'].read()` outside of the client context (i.e., from other methods) works without issue. 

However, when we communicate with the non-local AWS S3 endpoint, the operation hangs indefinitely. It also raises no warning to indicate that it has been called in a context where it never will complete.

The only thing I've been able to diagnose as being different, would be the speed of communication (i.e., a local vs. a remote endpoint).

I can refactor the code, but it is much cleaner for unit-testing the different pieces of functionality if we can isolate these concerns. So I'd like to understand more about this functionality.

In the response `read` method itself, it calls `await self.__wrapped__.read()`, where `self.__wrapped__`  is an instance of [`ClientResponseContentProxy`](https://github.com/aio-libs/aiobotocore/blob/9413052ced97c62dda7757b617c81ea55b8262d1/aiobotocore/endpoint.py#L83-L86). I am inferring from the `ClientResponseContentProxy` docstring that this passing around behaviour is supported, but I recognize that I may be misinterpreting what is intended by the idea of passing around the response "Body":
```python
class ClientResponseContentProxy(wrapt.ObjectProxy):
    """Proxy object for content stream of http response.  This is here in case
    you want to pass around the "Body" of the response without closing the
    response itself."""
```

Do you have any guidance on these issues?

**Comment by thehesiod** [comment]
I've seen issues with aiohttp 3.5.4, can you try with 3.2.2?  That's what we use for prod

**Comment by thehesiod** [comment]
hanging while reading means most likely that the aiohttp socket read timeout is not functioning.  You can also try reducing the read/connect timeout as the default is 60s: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html

**Comment by thehesiod** [comment]
btw in regard to ```(I did not reproduce in botocore because there are no APIs in botocore that use asyncio's async/await syntax for coroutines.)``` this was meant as trying it with the equivalent synchronous APIs to ensure it's not a botocore issue.  In this case with timeouts you wouldn't be able to try with botocore because botocore uses requests as the backend, whereas aiobotocore uses aiohttp.

**Comment by mpacer** [comment]
Thank you for responding — when I go to try aiohttp 3.2.2 on PyPI I'm having difficulty finding it… it looks like the project had [3.2.1](https://pypi.org/project/aiohttp/3.2.1/) and jumped right to [3.3.0](https://pypi.org/project/aiohttp/3.3.0/) (with a [3.3.0a0 alpha](https://pypi.org/project/aiohttp/3.3.0a0/) inbetween).

**Comment by thehesiod** [comment]
whoops, typo, 3.3.2

**Comment by mpacer** [comment]
I just verified that it hangs for over a minute after updating to 3.3.2 if you don't have the object being read inside the client context manager.

Why do you think the context manager is making this difference as it relates under the hood to aiohttp? Because it's not just that it's hanging, it's that the same request would succeed in the context manager but it doesn't outside of it (unless the s3 communication is happening with a local docker container, in which case it doesn't matter).

**Comment by thehesiod** [comment]
if you could post some example code it would really help.  Without that I can just theorize.  IIRC each client has an aiohttp session, which itself has a pool of connectors.  If you're not reading the body soon enough the connector may get recycled back to the pool.  If this happens you're SOL.  So it's better to hold on to a reference to the body (connector).

**Comment by mpacer** [comment]
I had linked to some example code before (apologies if that wasn't clear). Here is the latest source that works: https://github.com/nteract/bookstore/blob/3e9a7ac13f776ef53a0ea47d06a885e957d60b0c/bookstore/clone.py

But it'll be easier to follow a simplified example:

```python
    async def _clone(self, s3_bucket, s3_object_key):
        async with self.session.create_client('s3') as client:
            try:
                obj = await client.get_object(Bucket=s3_bucket, Key=s3_object_key)
                content = (await obj['Body'].read()).decode('utf-8')
            except ClientError as e:
                raise web.HTTPError(status_code, e.args[0])
```
which works as expected & is the fix that we're currently using.

and then the following will hang indefinitely when talking to S3 (but works fine when talking to the local mock Minio S3 service):

```python
    async def _clone(self, s3_bucket, s3_object_key):
        async with self.session.create_client('s3') as client:
            try:
                obj = await client.get_object(Bucket=s3_bucket, Key=s3_object_key)
            except ClientError as e:
                raise web.HTTPError(status_code, e.args[0])

        content = (await obj['Body'].read()).decode('utf-8')
```

**Comment by thehesiod** [comment]
second one you can't do, because you've closed the client, which holds the aiohttp session.  You can try the same thing directly in aiohttp:
```python
async with aiohttp.ClientSession() as client:
    response = await client.get(...)

await response.read()
```
 will probably have the same issue.

**Comment by thehesiod** [comment]
going to close, if above reply doesn't make sense please re-open.
