### ISSUE TITLE
How to set aiohttp "TCPConnector" "limit" and "limit_per_host" parameters?

### ISSUE THREAD

**Issue by mojimi** [aio-libs/aiobotocore#714]
I couldn't find where I can set these two parameters from aiohttp TCPConnector, I would like to set a limit to rate limit some asynchronous lambda calls.

**Comment by thehesiod** [comment]
`limit` = `Config.max_pool_connections`, see: https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore.config.Config

we currently don't support setting `limit_per_host` as there's a TCPConnector per endpoint (host) so no need.

**Comment by thehesiod** [comment]
feel free to re-open if this didn't answer your question
