### ISSUE TITLE
aiobotocore get_paginator overrides PAGE_ITERATOR_CLS in botocore

### ISSUE THREAD

**Issue by iechevarria** [aio-libs/aiobotocore#717]
I'm currently moving from botocore to aiobotocore, and there are pieces of the application that are dependent on botocore working correctly. aiobotocore [overrides](https://github.com/aio-libs/aiobotocore/blob/b0b63d3eaa74caf6c3fa0482cb55153a117a0fcd/aiobotocore/client.py#L147) PAGE_ITERATOR_CLS in botocore when get_paginator is called, and this breaks functions where botocore's [Paginator.paginate](https://github.com/boto/botocore/blob/develop/botocore/paginate.py#L609) are called because the functions must now be async'ed. 

Is there a way to prevent this change to botocore? Is it perhaps possible to create an AioPaginator class that wraps botocore's Paginator and updates PAGE_ITERATOR_CLS without affecting botocore? Thanks for your time!

**Comment by thehesiod** [comment]
added this to #695 if that's ok with you.  If not feel free to re-open
