### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by mivade** [aio-libs/aiobotocore#729]
Currently the required version of `botocore` is out of date. When trying to install other tools in the same environment that require newer versions I get messages from pip like this:

```
aiobotocore 0.10.3 has requirement botocore<1.12.190,>=1.12.189, but you'll have botocore 1.12.236 which is incompatible.
```

In order to keep using `aiobotocore` these requirements should be relaxed.

**Comment by thehesiod** [comment]
They cannot be relaxed and you should be installing other modules that depend on botocore via our extras. Please read all our docs for details

**Comment by mivade** [comment]
I did read the docs. Unfortunately that doesn't work for me because other packages I have installed in the same environment require different versions of `botocore`. Could you please elaborate on why they cannot be relaxed?

**Comment by thehesiod** [comment]
Docs state is because of the right integration between the two. We inherit from their classes and replace various methods. What modules conflict. Did you try using our extras instead?

**Comment by mivade** [comment]
If I recall correctly it was https://github.com/PyFilesystem/s3fs. (That's not natively async, but I was planning to work around that by using appropriate calls to `loop.run_in_executor`.)

**Comment by thehesiod** [comment]
We can add that as an extra if you'd.  Please open a request for that.

**Comment by thehesiod** [comment]
another option is having us bump up the botocore requirements, feel free to open request for that as well.  There's a doc for how to do that as well.

**Comment by thehesiod** [comment]
actually just opened one :)
