### ISSUE TITLE
Delete all objects from a bucket

### ISSUE THREAD

**Issue by Gloix** [aio-libs/aiobotocore#730]
While trying to delete all objects in a bucket using the resource API:

    aioboto3.resource("s3").Bucket("my-bucket").objects.all().delete()

I get the following error:

    NotImplementedError: <aiobotocore.paginate.AioPageIterator object at 0x7f775d3900f0> is an AsyncIterable: use `async for`

In line 14 of the paginate.py file.

The error originates from [dist-packages/boto3/resources/collection.py, line 166](https://github.com/boto/boto3/blob/develop/boto3/resources/collection.py#L166)

From my understanding the resource API has some logic that iterates over a collection (in this case, a paginated one) and tries to do it in a synchronous way.

**Comment by thehesiod** [comment]
This is an aioboto3 bug and not a aiobotocore bug. Please log there or reopen if I'm missing something
