### ISSUE TITLE
Early Warning: aiohttp v4.0.0a1 has a breaking change in TCPConnector

### ISSUE THREAD

**Issue by erikistre** [aio-libs/aiobotocore#741]
**Describe the bug**
My virtual environment was overzealous and picked up prerelease aiohttp v4.0.0a1. In that version, the `TCPConnector.__init__` no longer accepts a loop argument and the attempted construction of that object in aiobotocore/endpoint.py fails.

I've fixed my environment but I wanted to quickly notify maintainers here in case that change becomes permanent. I know nothing about the release trajectory/plans of aiohttp and this could be transient.

**Comment by asvetlov** [comment]
FYI aiohttp 3.x generates DeprecationWarning if the loop is passed.

**Comment by erikistre** [comment]
Cool. I'll close this.
