### ISSUE TITLE
'async for' requires an object with __aiter__ method, got s3.Bucket.objectsCollection

### ISSUE THREAD

**Issue by parinmaru2** [aio-libs/aiobotocore#750]
**Problem:**

I am using aioboto3 to create s3 resource.
And then I call s3 objects filter method:

```
my_bucket = self.s3_resource.Bucket(bucket_name)
response = my_bucket.objects.filter(Prefix=remote_directory_prefix)
```

I can't loop/iterate over this response:

```
async for r in response:
```
Above async for throws this exception:
**'async for' requires an object with aiter method, got s3.Bucket.objectsCollection**

**Analysis**
It seems s3.Bucket.objectsCollection doesn't implement aiter() method

**Comment by thehesiod** [comment]
that's an aioboto3 object, log here: https://github.com/terrycain/aioboto3/issues
