### ISSUE TITLE
Botocore 1.15.0 compatibility

### ISSUE THREAD

**Issue by JucianoC** [aio-libs/aiobotocore#765]
Has some reason to limit the `botocore` version to be <1.13.15?
https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L11

Has some perspective when the current version (1.15.0) is going to be supported?

**Comment by thehesiod** [comment]
see https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#background-and-implementation and we're working on https://github.com/aio-libs/aiobotocore/pull/767
