### ISSUE TITLE
test_presign_sigv4

### ISSUE THREAD

**Issue by terricain** [aio-libs/aiobotocore#768]
This is mainly for my own reference.

@thehesiod I have a feeling test_presign_sigv4 needs you to explicitly set the addressing style like 
```python
Config(s3={'addressing_style': 'path'})
```
Also https://github.com/aio-libs/aiobotocore/blob/master/tests/conftest.py#L43 generates invalid bucket names when used against real s3, we probably want to patch moto so it also complains

**Comment by thehesiod** [comment]
hmm this sounds like a bug in moto then no?  then it will trickle down to us once they fix that.  Did you already log a bug there?
