### ISSUE TITLE
advice/docs on best practices for client configuration when using aiobotocore

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#777]
This issue centers around a question about whether or not to use client connection pools with aiobotocore.   e.g. is it better to use a single client with a connection pool > 1 connection or is it better to use many clients and each one has only 1 connection?  To illustrate with some code options...

When using botocore, the session can provide default config for clients and it comes with some default values for client connection pools.  These can be plugged in for aiobotocore, e.g.

```python
import asyncio

import aiobotocore.client  # type: ignore
import aiobotocore.config  # type: ignore
import aiobotocore.session  # type: ignore
import botocore.endpoint  # type: ignore
import botocore.session  # type: ignore

#: max_pool_connections for AWS clients (10 by default)
MAX_POOL_CONNECTIONS = botocore.endpoint.MAX_POOL_CONNECTIONS
#: AWS asyncio session config
#: ..seealso:: https://github.com/boto/botocore/blob/develop/botocore/config.py
AIO_AWS_CONFIG = aiobotocore.config.AioConfig(max_pool_connections=MAX_POOL_CONNECTIONS)

#: a semaphore to limit requests to the max client connections
CLIENT_SEMAPHORE = asyncio.Semaphore(MAX_POOL_CONNECTIONS)

AIO_SESSION = aiobotocore.get_session()
AIO_SESSION.set_default_client_config(AIO_AWS_CONFIG)

async def get_stuff():
    async with CLIENT_SEMAPHORE:  # maybe this helps avoid DNS attacks
        async with AIO_SESSION.create_client("s3") as s3_client:
            # assumptions:
            # - it creates a new client with default config
            # - the `s3_client` has a connection pool of 10 connections
            resp = await s3_client.list_buckets()    # how many connections are used?
            return resp
```
(BTW, this is quick snippet, please excuse use of globals for this example.)

The `get_stuff` coroutine creates a new client context-manager that will clean up after itself.  Would it be better if the client created only 1 connection?

Another option is to create a client with a connection pool and pass it around, e.g. building on the above:
```python

AIO_S3_CLIENT = AIO_SESSION.create_client("s3")
# assume it has a connection pool of 10 connections, by default

async def get_stuff(s3_client: aiobotocore.client.AioBaseClient):
    async with CLIENT_SEMAPHORE:  # maybe this helps avoid DNS attacks
        resp = await s3_client.list_buckets()  # how many connections are used?
        return resp


loop = asyncio.get_event_loop()
try:
    loop.run(get_stuff(AIO_S3_CLIENT))
finally:
    loop.run(AIO_S3_CLIENT.close())  # need to close connection(s)
    loop.stop()
    loop.close()
```

Hope this question makes some sense.  I'm not totally familiar with aiohttp sessions and clients and how aiobotocore manages any connection pools, if any.

**Comment by thehesiod** [comment]
always better to keep connections alive, you should use one aiobotocore session if possible and the number of connections you need for parallelism.  Each client uses 1 connection

**Comment by dazza-codes** [comment]
@thehesiod - apologies if this is not the best forum for a question like this, but I need some help to study the source code and understand this better.  Is it possible to track/log the creation and use of connections in the connection pool?  Are the connections in a pool all created (opened) when the session is created?  Or, are they created on demand, as new clients are created with `session.create_client`, and then the connections stay open after a `client.close()` call, so they can be reallocated to a new client?  So I get this clear in my mind, it could help to know whether it's always one-client-per-connection so that every request on the same client passes through one connection (rather than one client using any number of connections to load-balance it's requests across the connections).  If it's one-client-per-connection and a session has a max-pool of 10 connections and the connections are created on-demand, it would take the creation of 10-clients to max-out the connection pool.  It would be great to understand the algorithm used by the session's connection pool to allocate connections to clients and what happens to a connection when any `client.close()` is called.  This understanding is critical to implementation details on whether to create/close clients on-demand (and to use client context managers) or to create a service client and pass it around everywhere and only close it at the top level logic.  That is, how can I study the source code and also monitor the connection pool to better understand what happens with a context manager pattern like:

```python
async with AIO_SESSION.create_client("s3") as s3_client:
    # do stuff
```
When that client is created, I assume that it either creates a new connection on-demand or it competes with any other clients to get a connection from the connection pool.  When the context closes, I assume that it releases the connection back to the connection pool that is managed by the session and the session keeps the connection alive.  If the connection pool is say 10 by default, to max out the throughput of the connection pool, it requires creating/releasing a rotating pool of at least 10 clients.  When the clients are created and competing for a connection, it seems like it's possible and a best-practice to `await` for the client to be created and get a handle on a connection.  If many coroutines are all sharing one client, they are all sharing one connection, which would be slower than many coroutines creating many clients using a context-manager to create/release clients on-demand, given that each client can complete to get a connection from the session connection pool.

**Comment by dazza-codes** [comment]
It could help to somehow expose aiohttp client tracing
- https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing

**Comment by thehesiod** [comment]
@dazza-codes no worries, sorry I misspoke, each client uses a aiohttp client pool.  When a connection is done it's put back into the pool and maintains a link to the server.  This is IFF the response is completely read, otherwise the connection is dropped and a new one will replace it when needed. The only time you should need multiple clients is if you have connections to multiple boto endpoints/regions to avoid contention between hosts you're connecting to (although this is already taken care of at the aiohttp level since it segregates the pool by hosts).  This is also already taken care of at the botocore API level since you can only have one session per `create_client` call.

**Comment by thehesiod** [comment]
if there are certain aspects of the aiohttp TCPConnector you'd like to control I added a `connector_args` param to AioConfig, we could add extra things there.  Here are the things we can control: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/connector.py#L697

**Comment by thehesiod** [comment]
@dazza-codes feel free to open issue about that or create PR!  We're at the mercy of have aiohttp behaves so this is more a question for them

**Comment by thehesiod** [comment]
my understanding is for every call you make via a particular client will acquire a connection from the pool size you set, then the requests will start blocking once you hit the max connector limit you've set.

**Comment by dazza-codes** [comment]
Oh thanks, will have to follow up on all this and better understand urllib3 vs. aiohttp connection pooling.  Some notes on botocore/urllib3 are in:
- https://gitlab.com/dazza-codes/aio-aws/-/wikis/botocore-clients
- if there's no license on that content, assume creative commons

AFAICT, the urllib3 documentation indicates that a pool-manager maintains a connection-pool for each endpoint, so that separation of AWS services for each `create_client` (service-name, region) makes sense.  In addition, it seems like `MAX_POOL_CONNECTIONS` is _not_ a hard limit on the number of connections, by default, in urllib3.  There is an option to force it as a hard limit (I haven't seen any botocore code that forces a hard limit based on that config option).  I haven't yet done enough reading on aiohttp to fully understand whether it adopts similar behavior/defaults to urllib3.

**Comment by thehesiod** [comment]
cool, ya if you see differences between pool behavior in aiobotocore vs botocore please do open issues
