### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by jettify** [aio-libs/aiobotocore#78]
@thehesiod @vas3k you did great job on supporting aiobotocore, I want to thank you for that!

If you still interested in this project I would like to invite you to aio-libs as aiobotocore maintainers. Rules are simple:
1) on each change please create pull request
2) each PR should be reviewed and tested
3) if PR is not commented for more than 3 days by other maintainers, feel free to merge it
4) be nice and respectful to others :)

What do you think? Feel free to ask me or @asvetlov (BDFL of aio-libs) any questions.

**Comment by thehesiod** [comment]
Want to thank you for creating this project and support in changes! sounds great to me!  I'm not quite clear though on what types of responsibilities are required outside PRs I create, could you elaborate?  I want to make sure I have enough free time to handle this.  Thanks!

**Comment by vas3k** [comment]
Hey. It is a honor for me to be invited to the maintainers and Make Aiolibs Great Again :D But unfortunately I think have not enough time and responsibility to do it well. So let me just stay as a contributor. Maybe if I will have more pull-request ideas, I will write you :)

**Comment by jettify** [comment]
Thanks for replies folks!

There are no strict responsibilities, it is not paid job, if you have free time just help to keep project alive:
* creating/reviewing PRs
* try to keep up with botocore
* improve docs
* improve tests coverage

**Comment by thehesiod** [comment]
cool count me in.  I'll help as much as possible.

**Comment by vas3k** [comment]
Yep, me too :) I've subscribed to all notifications. I'm thinking about documentation improvement. When I searched for it, I thought it's a dead project because lack of docs.

**Comment by thehesiod** [comment]
so here's the relevant code from `aiohttp.client.ClientSession.request`:

```python
            req = self._request_class(
                method, url, params=params, headers=headers,
                skip_auto_headers=skip_headers, data=data,
                cookies=cookies, encoding=encoding,
                auth=auth, version=version, compress=compress, chunked=chunked,
                expect100=expect100,
                loop=self._loop, response_class=self._response_class,
                proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)

            with Timeout(timeout, loop=self._loop):
                conn = yield from self._connector.connect(req)
```

note that timeout is sent to the request_class, which is used for the stream read.  So as long as your read_timeout is > than your connect timeout (which should be default) it should be fine.
