### ISSUE TITLE
Need info: Ceph support

### ISSUE THREAD

**Issue by poul1x** [aio-libs/aiobotocore#783]
Is *aiobotocore* able to interact with [Ceph](https://ceph.io/)? I've found s3 examples [here](https://docs.ceph.com/docs/mimic/radosgw/s3/python/). But I need async.

**Comment by terrycain** [comment]
There's a difference between the boto library and the botocore library, but you might get away with it by specifying the endpoint url to point to ceph

**Comment by poul1x** [comment]
Ok, thanks!

**Comment by nicholasamorim** [comment]
It is possible, yes. I use it.


```python
self.session = aiobotocore.get_session(loop=asyncio.get_event_loop())
return self.session.create_client(  # type: ignore
    "s3",
    aws_access_key_id=self.access_key_id,
    aws_secret_access_key=self.secret_access_key,
    endpoint_url=self.host,  # http://your-ceph-ip
    use_ssl=self.use_ssl,
)
```

**Comment by thehesiod** [comment]
closing, feel free if this didn't answer your question
