### ISSUE TITLE
Can botocore 1.13 support be re-enabled?

### ISSUE THREAD

**Issue by matt2000** [aio-libs/aiobotocore#785]
This commit added support for botocore 1.15 while disabling it for 1.13:

https://github.com/aio-libs/aiobotocore/commit/9f004bd534abc43c81b08630fb32352c245364cc#diff-2eeaed663bd0d25b7e608891384b7298L11

I use another package that does not yet support 1.15. Does aiobotocore now depend on some 1.15 specific functionality, or could the minimum version be reduced back to 1.13 for improved compatibility?

**Comment by thehesiod** [comment]
sorry there's a very tight integration between aiobotocore and botocore much like between awscli + boto3 and botocore, just a fact of life

**Comment by thehesiod** [comment]
I suggest you ask the other package to upgrade
