### ISSUE TITLE
HTTP Proxy settings not passed to aiohttp request

### ISSUE THREAD

**Issue by jjonek** [aio-libs/aiobotocore#79]
HTTP proxy defined in *HTTP_PROXY* and *HTTPS_PROXY* environment variables are not passed to *aiohttp request*, which makes the library unusable in private VPCs for other things than S3 with VPC endpoint.

Looks like the proxy configuration is read using utils derived from *botocore* but then it's just ignored in the AioEndpoint constructor.

**Comment by thehesiod** [comment]
fixed by https://github.com/aio-libs/aiobotocore/pull/97
