### ISSUE TITLE
aiohttp client tracing

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#791]
It could help to somehow expose aiohttp client tracing
- https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing

**Comment by dazza-codes** [comment]
The only clue to adding some tracing or monitoring is in `create_client` where it has an option to register a 'monitor' component that can listen to client events.

```python
# snippet from botocore.session.Session.create_client

        client_creator = botocore.client.ClientCreator(
            loader, endpoint_resolver, self.user_agent(), event_emitter,
            retryhandler, translate, response_parser_factory,
            exceptions_factory, config_store)
        client = client_creator.create_client(
            service_name=service_name, region_name=region_name,
            is_secure=use_ssl, endpoint_url=endpoint_url, verify=verify,
            credentials=credentials, scoped_config=self.get_scoped_config(),
            client_config=config, api_version=api_version)
        monitor = self._get_internal_component('monitor')
        if monitor is not None:
            monitor.register(client.meta.events)
        return client
```

**Comment by thehesiod** [comment]
actually there's an event you can trace: 

```python
        await self._event_emitter.emit(
            'creating-client-class.%s' % service_id,
            class_attributes=class_attributes,
            base_classes=bases)
```

could you state the goal you want with tracing the underlying aiohttp client?

**Comment by dazza-codes** [comment]
Essentially, it would be ideal to better understand and monitor how the clients are using a connection pool so that concurrent processes can be optimized for repeatable workloads or debugged for performance issues.  Some relevant notes on the connection pool for botocore/urllib3 are in https://gitlab.com/dazza-codes/aio-aws/-/wikis/botocore-clients and similar notes for aiobotocore would be great, with additional notes on how to monitor and tune the connection pools.  Hooking into the 'creating-client-class' event is not quite enough to actually trace the number of connections used and whether or not they are part of a connection pool or not.

**Comment by dazza-codes** [comment]
Most of the answers to some details are in `aiobotocore.endpoint` module.

Looking at `AioEndpointCreator`, it seems there might be no way to pass through any tracing from `AioConfig` because the signature for `create_endpoint` does not allow it and it should remain consistent with botocore; unless it might be added to `connector_args`?

There is also an interesting `botocore.endpoint.history_recorder` that is used to track all the request/response details.  But, it doesn't provide any details on how the connection pool is used or optimized.
