### ISSUE TITLE
JSONDecodeError for moto response content stream

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#793]
**Describe the bug**

aiobotocore@0.12.x works fine with actual AWS lambda response data, but unit tests with moto are returning something that the stream reader can read but it borks decoding the data with json.  (I'm hoping something like this looks familiar and there's a simple fix to handle the moto lambda response with the stream reader.  Maybe this is a bug on moto if it has a significantly different response from the actual AWS response.  Also, this should be different from https://github.com/aio-libs/aiobotocore/issues/710 because the response is read in the context of an active client.)

```
(Pdb) self.response
{'ResponseMetadata': {'RequestId': 'OP99TJZK54T3JE8TIZ9XPJ1VKPBJRA8X1GL1NQF8XH9XSLZNH3MR', 'HTTPStatusCode': 202, 'HTTPHeaders': {'x-amz-log-result': 'G1szMm1TVEFSVCBSZXF1ZXN0SWQ6IGM1YWU4NGY4LThhMDUtMWEwNC05ZDNjLWMyOWVlZmVkZDMxZSBWZXJzaW9uOiAxG1swbQp7J2knOiAxfQowLCAxLCAyLCAzLCA0LCA1LCA2LCA3LCA4LCA5ChtbMzJtRU5EIFJlcXVlc3RJZDogYzVhZTg0ZjgtOGEwNS0xYTA0LTlkM2MtYzI5ZWVmZWRkMzFlG1swbQobWzMybVJFUE9SVCBSZXF1ZXN0SWQ6IGM1YWU4NGY4LThhMDUtMWEwNC05ZDNjLWMyOWVlZmVkZDMxZQlJbml0IER1cmF0aW9uOiAzMzYuMjMgbXMJRHVyYXRpb246IDMuMjggbXMJQmlsbGVkIER1cmF0aW9uOiAxMDAgbXMJTWVtb3J5IFNpemU6IDEyOCBNQglNYXggTWVtb3J5IFVzZWQ6IDI2IE1CCRtbMG0KCnsic3RhdHVzQ29kZSI6MjAwLCJib2R5IjoiXCIwLCAxLCAyLCAzLCA0LCA1LCA2LCA3LCA4LCA5XCIifQ==', 'content-length': '409', 'x-amzn-requestid': 'OP99TJZK54T3JE8TIZ9XPJ1VKPBJRA8X1GL1NQF8XH9XSLZNH3MR', 'x-amz-crc32': '773298142', 'content-type': 'text/html; charset=utf-8', 'server': 'Werkzeug/1.0.1 Python/3.6.10', 'date': 'Wed, 08 Apr 2020 01:22:27 GMT'}, 'RetryAttempts': 0}, 'StatusCode': 202, 'LogResult': 'G1szMm1TVEFSVCBSZXF1ZXN0SWQ6IGM1YWU4NGY4LThhMDUtMWEwNC05ZDNjLWMyOWVlZmVkZDMxZSBWZXJzaW9uOiAxG1swbQp7J2knOiAxfQowLCAxLCAyLCAzLCA0LCA1LCA2LCA3LCA4LCA5ChtbMzJtRU5EIFJlcXVlc3RJZDogYzVhZTg0ZjgtOGEwNS0xYTA0LTlkM2MtYzI5ZWVmZWRkMzFlG1swbQobWzMybVJFUE9SVCBSZXF1ZXN0SWQ6IGM1YWU4NGY4LThhMDUtMWEwNC05ZDNjLWMyOWVlZmVkZDMxZQlJbml0IER1cmF0aW9uOiAzMzYuMjMgbXMJRHVyYXRpb246IDMuMjggbXMJQmlsbGVkIER1cmF0aW9uOiAxMDAgbXMJTWVtb3J5IFNpemU6IDEyOCBNQglNYXggTWVtb3J5IFVzZWQ6IDI2IE1CCRtbMG0KCnsic3RhdHVzQ29kZSI6MjAwLCJib2R5IjoiXCIwLCAxLCAyLCAzLCA0LCA1LCA2LCA3LCA4LCA5XCIifQ==', 'Payload': <StreamingBody at 0x7f9c50c64b48 for ClientResponseContentProxy at 0x7f9c50c53908>}

(Pdb) data  # this from response.get("Payload").read()
b'\x1b[32mSTART RequestId: c5ae84f8-8a05-1a04-9d3c-c29eefedd31e Version: 1\x1b[0m\n{\'i\': 1}\n0, 1, 2, 3, 4, 5, 6, 7, 8, 9\n\x1b[32mEND RequestId: c5ae84f8-8a05-1a04-9d3c-c29eefedd31e\x1b[0m\n\x1b[32mREPORT RequestId: c5ae84f8-8a05-1a04-9d3c-c29eefedd31e\tInit Duration: 336.23 ms\tDuration: 3.28 ms\tBilled Duration: 100 ms\tMemory Size: 128 MB\tMax Memory Used: 26 MB\t\x1b[0m\n\n{"statusCode":200,"body":"\\"0, 1, 2, 3, 4, 5, 6, 7, 8, 9\\""}'

(Pdb) json.loads(data)
*** json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(Pdb) json.loads(data.decode())
*** json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This can be reproduced using
- https://gitlab.com/dazza-codes/aio-aws/-/blob/lambda-responses/tests/test_aio_aws_lambda.py

```
git clone https://gitlab.com/dazza-codes/aio-aws
cd aio-aws
conda create -n aio-aws python=3.6
conda activate aio-aws
make init  # calls poetry install
pytest --pdb tests/test_aio_aws_lambda.py
```

### versions

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"

$ python --version
Python 3.6.10

$ pip freeze | grep oto
aiobotocore==0.12.0
boto==2.49.0
boto3==1.12.3
botocore==1.15.3
moto==1.3.14

$ pip freeze | grep aio
aiobotocore==0.12.0
aiocontextvars==0.2.2
aiofiles==0.4.0
aiohttp==3.6.2
```

### AWS lambda works OK

```
$ ./aio_aws/aio_aws_lambda.py 

Test async lambda functions
[INFO]  2020-04-08T01:40:43.619Z  aio-aws:invoke:163  AWS Lambda (lambda_dev) invoked OK
{'ResponseMetadata': {'RequestId': 'aab74e21-0b85-479b-aee7-bfd69bf7d80f', 'HTTPStatusCode': 200, 'HTTPHeaders': {'date': 'Wed, 08 Apr 2020 01:40:43 GMT', 'content-type': 'application/json', 'content-length': '63', 'connection': 'keep-alive', 'x-amzn-requestid': 'aab74e21-0b85-479b-aee7-bfd69bf7d80f', 'x-amzn-remapped-content-length': '0', 'x-amz-executed-version': '$LATEST', 'x-amzn-trace-id': 'root=1-5e8d2b9b-de096df0f01d5b5a5cd0e280;sampled=0'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'ExecutedVersion': '$LATEST', 'Payload': <StreamingBody at 0x7f28cb42f9c8 for ClientResponseContentProxy at 0x7f28cb42f988>}
{'statusCode': 200, 'body': '"0, 1, 2, 3, 4, 5, 6, 7, 8, 9"'}
1 lambdas finished in 0.66 seconds.
```

### moto test code

- https://github.com/spulec/moto/blob/master/tests/test_awslambda/test_lambda.py#L124-L125

The moto test code doesn't need an aiohttp stream reader and it seems to work fine.  Something happens when the stream reader is involved.

**Comment by thehesiod** [comment]
thanks @dazza-codes for the great test case, what's coincidental is last night I just got our AWS testcases ported to aiobotocore 1.x and the latest moto and didn't have any issues.  I'll take a look asap

**Comment by thehesiod** [comment]
ok, so what you're seeing is the fact that the lambda via moto via the underlying lambci is returning ansi color codes code the response text.  Try echoing the bytes string you get back in bash for example:

```
echo -e "\e[32mSTART RequestId: 31619f03-e184-17ef-3242-a80d342688cc Version: 1\x1b[0m\n{\'hello\': \'world\'}\n\x1b[32mEND RequestId: 31619f03-e184-17ef-3242-a80d342688cc\x1b[0m\n\x1b[32mREPORT RequestId: 31619f03-e184-17ef-3242-a80d342688cc\tInit Duration: 93.27 ms\tDuration: 2.87 ms\tBilled Duration: 100 ms\tMemory Size: 128 MB\tMax Memory Used: 25 MB\t\x1b[0m\n\n{"statusCode":200,"body":{"hello":"world"}}"
```

and you'll get some nice green text around some non white text

**Comment by thehesiod** [comment]
I'm adding a test on your behalf https://github.com/aio-libs/aiobotocore/pull/796.  I'm going to close because I think it's working as expected.  This is nothing to do with aiobotocore, and instead with how moto lambda backend works.

**Comment by thehesiod** [comment]
feel free to re-open if you do not believe this is the case though

**Comment by dazza-codes** [comment]
Not sure this is entirely relevant here, but if moto is using anything from `botocore.awsrequest`, it might be relevant, e.g. botocore uses some headers to detect encodings:
- https://github.com/boto/botocore/blob/develop/botocore/utils.py#L1707
- used in `botocore.awsrequest.AWSResponse.text()` 
  - https://github.com/boto/botocore/blob/develop/botocore/awsrequest.py#L524

**Comment by dazza-codes** [comment]
So moto is returning the log-messages from the lambda invocation as the `Payload` instead of the actual lambda function return data.  That looks like a moto bug.  Thanks so much for looking into this and solving the test-case (case closed, until there's a fix upstream in moto).

**Comment by thehesiod** [comment]
Could you link there bug here if you log or find one? I'd like to know as well. Thanks!

**Comment by thehesiod** [comment]
Oh you did already, ignore :)

**Comment by dazza-codes** [comment]
This is fixed in a prerelease of moto
- `poetry add --dev moto=1.3.15.dev620 -E server`
