### ISSUE TITLE
Issue with handling credentials with credentials.process

### ISSUE THREAD

**Issue by mvalkon** [aio-libs/aiobotocore#794]
**Describe the bug**
Credential loading fails when using [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) with the following exception. I am not sure if this is a bug asyncio?

```
  File "/usr/local/lib/python3.7/contextlib.py", line 570, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/app/.venv/lib/python3.7/site-packages/aioboto3/session.py", line 195, in __aenter__
    client = await self.client.__aenter__()
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/session.py", line 19, in __aenter__
    self._client = await self._coro
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/session.py", line 92, in _create_client
    credentials = await self.get_credentials()
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/session.py", line 117, in get_credentials
    'credential_provider').load_credentials())
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/credentials.py", line 787, in load_credentials
    creds = await provider.load()
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/credentials.py", line 409, in load
    creds_dict = await self._retrieve_credentials_using(credential_process)
  File "/app/.venv/lib/python3.7/site-packages/aiobotocore/credentials.py", line 430, in _retrieve_credentials_using
    stderr=subprocess.PIPE)
  File "/usr/local/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1529, in subprocess_exec
    f"program arguments must be a bytes or text string, "
TypeError: program arguments must be a bytes or text string, not list
```

The exception occurs when a dynamodb client is being created, and credentials are loaded. I have the following two files

```
$ ll test                                                                                                                                     
total 16
-rw-r--r--  1 mvalkonen  xxx   573B Apr  8 18:40 credentials.json
-rw-r--r--  1 mvalkonen  xxx    66B Apr  8 18:29 credentials.process
```

The `credentials.process`-file contains just the following

```
$ cat test/credentials.process                                                                                                                
[default]
credential_process = cat /meta/aws-iam/credentials.json
```

The contents of `credentials.json` are valid, they work in my production environment with aiobotocore 0.11.1

I am using `aioboto3` and `aiohttp`. Running in a container environment, with a base ubuntu image and python 3.7.6. Will try to provide an isolated example of the issue. 

UPDATE:
Seems like unpacking `args` to `self._popen` in https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/credentials.py#L428 will fix this.  

```python
p = await self._popen(*process_list,
                      stdout=subprocess.PIPE,
                      stderr=subprocess.PIPE)
```

Not sure if this change should be done?

**Checklist**
- [x] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [x] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [x] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**Comment by mvalkon** [comment]
ping @terrycain as this affects `aioboto3`.

**Comment by terrycain** [comment]
@mvalkon yeah, this one is my fault when porting said credentials class. I'll look into it.

**Comment by terrycain** [comment]
@mvalkon can you try the change here - https://github.com/aio-libs/aiobotocore/pull/795

**Comment by mvalkon** [comment]
Seems to work @terrycain!

**Comment by thehesiod** [comment]
1.0.3 is live with fix

**Comment by mvalkon** [comment]
Thank you @terrycain and @thehesiod for reacting so quick to this. Much appreciated!

**Comment by thehesiod** [comment]
Glad people are using it!
