### ISSUE TITLE
share aiohttp.ClientSession between clients

### ISSUE THREAD

**Issue by adamko147** [aio-libs/aiobotocore#797]
According to documentation at https://docs.aiohttp.org/en/stable/client_reference.html#client-reference it's suggested to use single ClientSession for app

> Session encapsulates a connection pool (connector instance) and supports keepalives by default. Unless you are connecting to a large, unknown number of different servers over the lifetime of your application, it is suggested you use a single session for the lifetime of your application to benefit from connection pooling.

Is there any way how to achieve sharing single ClientSession in aiobotocore accross multiple clients? I'm running multiple requests to AWS resources and each `client` uses own ClientSession.

Thanks

**Comment by dazza-codes** [comment]
My 2c - good question - but aiobotocore is kinda tied to botocore design patterns (AFAIK) and it has to stick the patterns in `aiobotocore.endpoint.AioEndpointCreator` to instantiate the `aiohttp.ClientSession` on the `endpoint_instance.http_session`.

In botocore, if you want to try to override things by first creating a single client and then using it everywhere else (for a given AWS service, of course), you could register a handler for the `create-client` event.  But `aiobotocore` is not using the same event registration/handler pattern for clients to ensure that it uses the aiohttp client (AFAICT).

Details are in
- `aiobotocore.session.AioSession.create_client`
- `aiobotocore.endpoint.AioEndpointCreator`

**Comment by adamko147** [comment]
Thanks @dazza-codes for your reply. I can see the pattern in `botocore`. Unless `aiobotocore` wants to strictly follow that, I would suggest to have additional parameter `http_session` on `aiobotocore.session.AioSession.create_client`. If session was provided, that would be passed down the call stack to endpoint and used instead of creating new session. I could try to do the work, if you think it's worth to try :)

**Comment by dazza-codes** [comment]
See also #749 .

**Comment by thehesiod** [comment]
aiobotocore follows botocore, which my default uses a session per client, however, it allows you to pass in your own session class, see https://github.com/boto/botocore/blob/develop/botocore/endpoint.py#L280 so you can try using that however it doesn't seemed to be hooked up all the way in botocore.  Fixing a small bug of this in https://github.com/aio-libs/aiobotocore/pull/844
