### ISSUE TITLE
response type and parsing - not requests - aiohttp.ClientResponse

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#800]
RE https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/endpoint.py#L26

```python
async def convert_to_response_dict(http_response, operation_model):
    """Convert an HTTP response object to a request dict.
    This converts the requests library's HTTP response object to
    a dictionary.
    :type http_response: botocore.vendored.requests.model.Response
    :param http_response: The HTTP response from an AWS service request.
    ... """
    # etc
```
Is this a legacy of a prior fork or copy-paste from botocore?  It seems like it's actually an `aiohttp.ClientResponse` (or wrapper from `aiobotocore._endpoint_helpers.ClientResponseProxy`):
- https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse

It's no longer a `:type http_response: botocore.vendored.requests.model.Response` because requests was removed.
- https://github.com/boto/botocore/pull/1829 removed requests.
- see also notices for lambda 
  - https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/
  - https://aws.amazon.com/blogs/compute/upcoming-changes-to-the-python-sdk-in-aws-lambda/

> In August of last year, we made significant improvements to the internals of Botocore to allow for pluggable HTTP clients. A key part of the internal refactoring was changing the HTTP client library from the requests library to urllib3. As part of this change, we also decided to unvendor our HTTP library. This allows us to support a range of versions of urllib3 instead of requiring us to depend on a specific version. This meant that we no longer used the vendored version of requests in Botocore and we could remove this unused code.

Throwing a breakpoint or print statement into `convert_to_response_dict` reveals:
- `print(type(http_response))`
- `aiobotocore._endpoint_helpers.ClientResponseProxy`

**Comment by thehesiod** [comment]
this is the wording from botocore, see https://github.com/boto/botocore/blob/develop/botocore/endpoint.py#L39. closing as this is from them.  If I'm missing something please re-open
