### ISSUE TITLE
persistent client

### ISSUE THREAD

**Issue by potatochip** [aio-libs/aiobotocore#806]
I understand you changed the api to make a client accessible only from a context manager, but is it still safe to persist the client anyway?

I am using the following to persist it.
```python
_SESSION = aiobotocore.get_session()
client_context = _SESSION.create_client('s3')
self._client = await client_context.__aenter__()
```

**Comment by thehesiod** [comment]
If you don't close the client you'll get warnings about unclosed connections

it's better to use [AsyncExitStack](https://docs.python.org/3/library/contextlib.html#contextlib.AsyncExitStack)

and then aexit that when you're done

**Comment by thehesiod** [comment]
I'm going to leave this open to remember to do some examples about this topic

**Comment by thehesiod** [comment]
ex:
```python
exit_stack = AsyncExitStack()
s3_client = await exit_stack.enter_async_context(_SESSION.create_client('s3'))
```
then later during shutdown:
```python
await exit_stack.__aexit__(None, None, None)
```

the nice thing of exitstack is you can stick a bunch of things in it

**Comment by potatochip** [comment]
awesome. thanks for the heads up. ive been using `await client.close()` when finished.

you could probably add a __call__ method to ClientCreatorContext that returns the client. Then a user could use it as context when they need creds refreshed every time or call it as a function when they need a persistent client.

**Comment by thehesiod** [comment]
but that's on a `create_client` so it would still need to be a context because only after you have a client can you make a method call, and then free the context.  It would only make sense if we had a static client.  aiohttp had something similar to this, static methods on the `ClientSession` but deprecated as it's not efficient and really not the way the library wanted to go in terms of resource management.

**Comment by terrycain** [comment]
https://aioboto3.readthedocs.io/en/latest/usage.html#aiohttp-server-example

I have an example, you should add one too :wink:

**Comment by thehesiod** [comment]
ok added a couple examples to the front page, please re-open if that doesn't fit the bill :)

**Comment by fabiopedrosa** [comment]
@thehesiod @terrycain 
The documentation doesn't make any reference to this, and it still seems unclear to me what the answer is.

Is persisting the client safe, and is this a good approach?

```
_SESSION = aiobotocore.get_session()
client_context = _SESSION.create_client('s3')
self._client = await client_context.__aenter__()
```

If that's so, why not expose the `_get_client` to allow the manual creation/clean-up?

**Comment by thehesiod** [comment]
persisting the client is ok, however its better to put into a context to be cleaned up when you process/function exits, just better style to let you know the client should be cleaned up
