### ISSUE TITLE
get_credentials() raises exception "object NoneType can't be used in 'await' expression"

### ISSUE THREAD

**Issue by igorsobreira** [aio-libs/aiobotocore#817]
**Describe the bug**
`get_credentials` raises an exception:

    object NoneType can't be used in 'await' expression

```
TypeError: object NoneType can't be used in 'await' expression
  File "clips/transfer.py", line 73, in perform_transfer
    clip_url = coroutines.run(coroutine, timeout=TIMEOUT)
  File "clips/coroutines.py", line 28, in run
    return loop.run_until_complete(_run_with_timeout(coro, timeout))
  File "asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "clips/coroutines.py", line 35, in _run_with_timeout
    return await asyncio.wait_for(coro, timeout)
  File "asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "clips/transfer.py", line 127, in start_transfers
    container_url = await get_container_url(container_name)
  File "clips/containers.py", line 14, in get_container_url
    async with aioboto3.client('mediastore') as ms:
  File "aiobotocore/session.py", line 19, in __aenter__
    self._client = await self._coro
  File "aiobotocore/session.py", line 93, in _create_client
    credentials = await self.get_credentials()
  File "aiobotocore/session.py", line 117, in get_credentials
    self._credentials = await (self._components.get_component(
  File "aiobotocore/credentials.py", line 787, in load_credentials
    creds = await provider.load()
```

inspecting the exception above, provider instance on `provider.load()` is [SSOProvider, a recent addition in botocore](https://github.com/boto/botocore/commit/50e684025f0a7691eaa538a4c7bd55c50e56403c)

This happens with botocore 1.17.4. Downgrading to aiobotocore 1.16.26 works as usual.

It can be an issue with this new provider from botocore, but it could also indicate we can improve error handling when trying multiple providers:
https://github.com/aio-libs/aiobotocore/blob/ec0b676eeaa76ce9e181f3327058b0019bf0073b/aiobotocore/credentials.py#L787-L789

**Environment:**
 - Python Version: 3.8.1
 - aiobotocore 1.0.7

**Comment by thehesiod** [comment]
if you note setup.py (https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L10)  aiobotocore is tied to a specific version of botocore which you're not using.  Feel free to open a bug to support later versions

**Comment by thehesiod** [comment]
actually opened one for you :)

**Comment by igorsobreira** [comment]
thanks @thehesiod ! we are also using botocore (from boto) outside aiobotocore, so we ended up adding to our requirements.
I'll make sure to match that now 👍

**Comment by thehesiod** [comment]
boto is dead for awhile, I'm guessing you meant boto3?  if so, there's an aioboto3 too from @terrycain

**Comment by igorsobreira** [comment]
@thehesiod yes boto3. I'm aware of aioboto3, we just have some interactions with aws in this specific project that are not using asyncio (yet?!) :-)
