### ISSUE TITLE
Bump botocore requirement

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#818]

**Comment by thehesiod** [comment]
https://github.com/aio-libs/aiobotocore/issues/817 demonstrates that new versions are incompatible

**Comment by rgbkrk** [comment]
Thank you for opening this!

**Comment by CMCDragonkai** [comment]
Does aiobotocore have a really specific version constraint on:

```
    'botocore>=1.15.32,<1.15.33',
```

Can it be loosened?

**Comment by thehesiod** [comment]
@CMCDragonkai unfortunately no due to the tight coupling between aiobotocore and botocore.  I'll try to work on this bump today

**Comment by CMCDragonkai** [comment]
Does every minor patch to botocore imply a minot patch needed for aiobotocore?

**Comment by CMCDragonkai** [comment]
May I suggest bumping to 1.17.32. That would be great!

**Comment by CMCDragonkai** [comment]
Hopefully it's already compatible.

**Comment by thehesiod** [comment]
we never know what they may change so yes :(

**Comment by thehesiod** [comment]
ok coming in https://github.com/aio-libs/aiobotocore/pull/823, had to do a bit of work because they introduced a new credential resolver

**Comment by CMCDragonkai** [comment]
I'll have to test if this works with the botocore that I have 1.17.32. Getting exact versions of botocore is a pain!
