### ISSUE TITLE
Aiobotocore might not return connections to the pool in some situations

### ISSUE THREAD

**Issue by pfreixes** [aio-libs/aiobotocore#819]
**Describe the bug**

Looking at this code [1] seems that Aiohttp takes care of releasing the connection without having to make an explicit close/release through a call to the methods provided by the response object or implicitly by using a context.

However, it seems that some sort of situation might provoke that the connection could not be returned to the pool if the explicit call to the close/release method is mot done.

When `keep-alive` is used, if the header is sent - which is by default in Aiohttp unless a header is provided for indicating the opposite or protocol 1.0 is used [2], the server won't close immediately the connection so no EOF could not be triggered - I have to doublecheck this but seems that EOF policy is decided considering different parameters, but when length [3] is not informed a typical EOF is configured -  would be sent and the connection won't be returned to the pool until the connection is closed after a while by the sever.

Also if an exception happens here [4], for example, because the request is canceled the connection won't be recycled either.

Both use cases are covered using the Aiothtp client since the prescripted pattern of using a context forces implicitly to return always the connection to the pool.

So the question would be, should Aiobotocore release the connection after a request explicitly if this response is not a streaming one? I would say yes, this won't damage at all the current behavior and would follow the pattern prescribed by Aiohttp

Thoughts?

[1] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L806
[2] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L486
[3] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/http_parser.py#L564
[4] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L792

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: [e.g. 3.6]
 - OS name and version: [e.g. darwin stretch]

**Additional context**

**Comment by thehesiod** [comment]
will look asap if someone else doesn't get to it.  Been inundated with issues at work recently

**Comment by pfreixes** [comment]
Thanks @thehesiod in any case IMO I would decouple the Httpx discussion vs making sure that Aiobotcore makes everything that it can for returning back a connection to the pool.

For the second one IMO would be just a matter of calling almost always the `resp.release()` - not when it's handling a streaming call - method, which in most of the situations will end up as a no-op operation because Aiohttp already released it.

**Comment by thehesiod** [comment]
as a last stopgap measure the ClientResponse class has a `__del__` which handles this: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client_reqrep.py#L695.  It even spits out a warning if the connector was not released properly so if this was an issue you should see some debug messages.

[4] is called from here: https://github.com/aio-libs/aiohttp/blob/3.3/aiohttp/client.py#L387 in which case if an exception happens the connection is closed, which makes sense since there's a http protocol error in that case.

**Comment by pfreixes** [comment]
> as a last stopgap measure the ClientResponse class has a __del__

The destructor method is not the best place for having resource cleanup, which can be used only as a last hope. You don't know when the object will be ready for being deallocated.

Good point about 4, theoretically conn should be released in that case.

In any case, having the feeling that for the sake of following the good practices advised from Aiohttp we should try to close/release the connection gracefully, so not relating on safety nets that might not be applied after a while or not even applied -If I'm not wrong - as it would be the use case of a pipelining operation with the response being returned without content length.

**Comment by thehesiod** [comment]
I'll throw some more time at this when I get a chance

**Comment by thehesiod** [comment]
btw @pfreixes  I'd suggest updating the links to a specific git commit so the underlying code doesn't change over time

**Comment by thehesiod** [comment]
I'm wary of diverging from botocore behavior as who knows if they want to do something with the connection after that point.
