### ISSUE TITLE
swap to bytecode patching?

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#826]
Instead of us generating tons of copy/pasted code for sections where we're only adding an await perhaps we should think about swapping to bytecode patching.  There are helpers like bytecode and codetransformer that could help

the worry I would have is for debugging.  As long as it would match up line for line I think it would be ok, definitely would be a little weird ;)

**Comment by thehesiod** [comment]
@terrycain thoughts?

**Comment by thehesiod** [comment]
@jettify ?

**Comment by graingert** [comment]
@thehesiod I strongly recommend going the other way around with https://pypi.org/project/unasync/ and having botocore be generated from aiobotocore

**Comment by thehesiod** [comment]
we can't generate botocore from aiobotocore, botocore is the truth, aiobotocore is a third party enhancement

**Comment by terrycain** [comment]
Got any references/examples of it? sounds cool/scary/error-prone :smile:

**Comment by thehesiod** [comment]
@terrycain  exactly, lol I was looking at this: https://rushter.com/blog/python-bytecode-patch/ that referenced those modules, I need to spend some time to play around with it

**Comment by thehesiod** [comment]
I think it combined with the patcher would be ok, but ya debugging would suk, unless we generate python code from the bytecode and add them as reference files, actually that would be cool.
