### ISSUE TITLE
Boto3 dep

### ISSUE THREAD

**Issue by Laksh1997** [aio-libs/aiobotocore#828]
Hi - I'm having trouble installing this package because it forces boto3 to be of a specific version, resulting in a version conflict.

Is there a reason for the strict boto3 requirement?

**Comment by thehesiod** [comment]
boto3 is tied to specific botocore, and aiobotocore to specific version of botocore due to our replacement of their methods

**Comment by thehesiod** [comment]
you can install boto3 via our extras to pick up the correct version of boto3/awscli, ex: `pip3 install aiobotocore[boto3]`

**Comment by thehesiod** [comment]
closing as there's no way around this for now
