### ISSUE TITLE
Pinned botocore requirement makes it impossible to package this

### ISSUE THREAD

**Issue by mgorny** [aio-libs/aiobotocore#829]
Given that botocore is being released *daily*, pinning to a specific version makes it practically impossible to package aiobotocore for distributions. This might be possible if you managed to keep up with daily synchronized releases but otherwise packaging it would block our users to a specific old version of botocore. I don't think it is a good idea to force-downgrade Linux distributions for this. Could you consider exploring other options that would let us avoid pinning it that narrow?

**Comment by shughes-uk** [comment]
I'm maintaining a package that requires boto3 and aiobotocore (dependency of a dependency not a direct one) and it's causing issues too. For now i've solved it by adding a dependency on aiobotocore[boto3] but that's not really ideal for me.

**Comment by thehesiod** [comment]
sorry but the only way to resolve this due to the tight coupling is by botocore itself supporting async

**Comment by thehesiod** [comment]
also I'm not sure why you're saying force downgrade linux, linux is orthogonal to this module ;)

**Comment by thehesiod** [comment]
if we were to unpin botocore there would be no guarantees as to if this module would work or not given changes that can happen internally to botocore.  If anyone has a better plan of how to integrate botocore please open issue with ideas, otherwise this is not possible.

**Comment by mgorny** [comment]
How about working with botocore maintainers to integrate the extra functionality in the same package?

**Comment by shughes-uk** [comment]
It's rather extreme but you could repackage botocore and re-release it under another namespace and depend on that instead.

**Comment by thehesiod** [comment]
Ah vendoring. Ya we discussed that, perhaps time to revisit. However I don't see a use case where you'd want one version of botocore for aiobotocore, and a different version for your other tools

**Comment by thehesiod** [comment]
We already have an open issue for several years without any traction on their side, further I've had speed fixes open for many years that have no traction. Don't seem interested in patches/fixes

**Comment by shughes-uk** [comment]
> 
> 
> Ah vendoring. Ya we discussed that, perhaps time to revisit. However I don't see a use case where you'd want one version of botocore for aiobotocore, and a different version for your other tools

It's mostly just something that my users seem to have happen to them, and then all our entry points stop working because of the requirements mismatch. Pip's lack of a resolver is the real issue

**Comment by thehesiod** [comment]
We've switched to pipfile s to avoid this, should check out pipenv/poetry/piptools

**Comment by shughes-uk** [comment]
we are using poetry

**Comment by thehesiod** [comment]
you should be using extras then, ex: `aiobotocore[boto3,awscli]`

**Comment by shughes-uk** [comment]
I do, what happens is my users install some other package into their environment that upgrades botocore and messes everything else up because pip has no proper dependency resolving. I can't enforce much of anything on them. If aiobotocore wasn't so tightly coupled they'd be much less likely to have any issue.

**Comment by thehesiod** [comment]
it would still be the same issue, boto3 + awscli are also tightly coupled in the same way

**Comment by shughes-uk** [comment]
Right so when my users install my library, but then perhaps install awscli later, it breaks everything

**Comment by mgorny** [comment]
So aiobotocore now requires 3 months old botocore. A self-fulfilling prophecy maybe?

**Comment by thehesiod** [comment]
> Right so when my users install my library, but then perhaps install awscli later, it breaks everything

The same happens with botocore/awscli. You install botocore and use it, then install newer awscli, it will update botocore and break your code that uses botocore. You need to use something like pipenv/poetry/pip-tools, a meta package manager

**Comment by shughes-uk** [comment]
If I could get my users to stick to best practice I wouldn't be here. awscli does break at lot yes and I also wish amazon would vendorize botocore there too.

**Comment by thehesiod** [comment]
new pip is supposed to solve some of these issues 🤞
