### ISSUE TITLE
AioSession and get_credentials as blocking operations?

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#836]
Since ver 0.x, the AioSession has been modified to use coroutines to get credentials, e.g.
- https://github.com/aio-libs/aiobotocore/blob/master/aiobotocore/session.py#L118

2c Opinions:

- Since credentials are essential to any request, should they be a blocking operation (i.e. not coroutines)?  AFAIK, they only read from a file system to read a small file or two, or they read env-vars.  The IO demands to get credentials are not onerous.
- There must be some design considerations at play, but where do you draw the line between a blocking operation vs. everything is an async coroutine?  Since an `AioSession` is a complex object, but it is cheap to instantiate (possibly a singleton/factory pattern), it seems that most of the operations it performs could be blocking operations.  The difference from a `botocore.Session` is that it generates clients that use non-blocking, async HTTP-IO.  It seems like all the non-blocking operations belong on the client (and possibly only on the client).  Once a session is used to get credentials and return a client, it's almost no longer required for anything else (except generating more clients, if desired, but a single client already contains a connection pool).

This is motivated by an update from 0.x to 1.x and a simple unit test failing, i.e.
```
    def test_aio_aws_session_credentials(aio_aws_session):
        assert isinstance(aio_aws_session, AioSession)
        credentials = aio_aws_session.get_credentials()
>       assert credentials.access_key == AWS_ACCESS_KEY_ID
E       AttributeError: 'coroutine' object has no attribute 'access_key'
```
On review of the latest master branch, it turns out that this is now a coroutine that needs to be used/tested within an `async def` coroutine.

**Comment by thehesiod** [comment]
this statement is not true, credentials can, and often come from https calls, for instance when running on ec2

**Comment by dazza-codes** [comment]
Interesting point about EC2, but then it is a localhost server (IIRC) and there is not really any network traffic/delay to be too concerned about.  There might be a case to be made that getting credentials is something that an `AioSession` could be doing once and memoize them (assuming that the config-details at the time of instantiation are immutable for the session object instantiated; if not, then memoizing the credentials would need to be reset if the config-details are modified).

**Comment by dazza-codes** [comment]
I put this issue/opinion out as food for thought or discussion, I'm not saying it's a bug.  I don't know where else to voice an opinion or point for discussion.  I can only assume there are good reasons for using coroutines in `AioSession` public methods.  I am fortunate that my project is easily adapted to the 1.x coroutine pattern.  e.g. the unit test is easily fixed with:

```python
@pytest.mark.asyncio
async def test_aio_aws_session_credentials(aio_aws_session):
    assert isinstance(aio_aws_session, AioSession)
    credentials = await aio_aws_session.get_credentials()
    assert credentials.access_key == AWS_ACCESS_KEY_ID
    assert credentials.secret_key == AWS_SECRET_ACCESS_KEY
    assert os.getenv("AWS_ACCESS_KEY_ID")
    assert os.getenv("AWS_SECRET_ACCESS_KEY")
    assert os.getenv("AWS_ACCESS_KEY_ID") == AWS_ACCESS_KEY_ID
    assert os.getenv("AWS_SECRET_ACCESS_KEY") == AWS_SECRET_ACCESS_KEY
```

**Comment by joseph-jones** [comment]
to expand on @thehesiod  statement. there is also the case where the application is assuming a role and has to make a call to STS to get the assumed role credentials. 

it's also possible to assume that someone may have a use-case where they need multiple sessions in a single application. e.g cross-account operations.

**Comment by terrycain** [comment]
Yeah also there are other more... unique ways to get credentials that can block for longer than talking to the metadata address. EKS is a bit more long winded as it does some assume role stuff and there is support for calling external programs to get credentials too.

**Comment by dazza-codes** [comment]
Thanks for the additional explanations; it sounds like there are cases for using an async non-blocking function to get credentials and it sounds like those cases require the general case to also use async.  If this issue is any use for updating doc-snippets it might morph in that direction, or close it out.

**Comment by thehesiod** [comment]
I've enabled discussions so we can discuss these ideas there, please do start discussions like these there, thanks!  Going to close this out as I don't see anything needed for now, if I missed something though please re-open
