### ISSUE TITLE
Sporadic SSL Certificate verification errors in aiobotocore

### ISSUE THREAD

**Issue by mariusvniekerk** [aio-libs/aiobotocore#837]
**Describe the bug**
Under certain rare occasions aiobotocore will fail to connect to s3 throwing the following error (as part of a very long running process)

```
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host xxxx.s3.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')]
```

I have not been able to reproduce it as it appears to be intermittent.  Will test to see if setting `ca_path` to the same default that botocore resolves to fixes the issue.

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [x] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [x] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: 3.8 (conda-forge)
 - OS name and version: ubuntu-16.04

**Additional context**

I suspect that this can be mitigated by using the get_cert_path method provided by botocore 
https://github.com/boto/botocore/blob/f67b21be15ca2e48ee419b1939edf61ab7652d83/botocore/httpsession.py#L43
would help since botocore vendors a ca but will defer to certifi if it is installed, instead of falling back to the `$REQUESTS_CA_BUNDLE` environment variable that is presently the case in aiobotocore

**Comment by thehesiod** [comment]
I don't think this is aiobotocore specific, unless we're missing retry type. Do you have their full stack trace?

**Comment by thehesiod** [comment]
Ahh nice find thanks, I see now

**Comment by amitlevy21** [comment]
I had the same issue with aiohttp installed with version 3.7 and downgrading to 3.3 is a workaround

**Comment by thehesiod** [comment]
ah, so may be aiohttp issue?

**Comment by amitlevy21** [comment]
Maybe, I don't know

**Comment by daveisagit** [comment]
I have experienced the same intermittent issue using requests (about 5 in  every 10,000) connecting to Microsoft Azure. 
Using
Python 3.8.6
requests 2.25.1
    - certifi [required: >=2017.4.17, installed: 2020.12.5]
    - chardet [required: >=3.0.2,<5, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.5]
    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.3]

**Comment by thehesiod** [comment]
I believe this has been resolved, we have done some changes to how certificates are loaded.  I'm going to close for now, if you can still repro with latest build please re-open
