### ISSUE TITLE
How can I check if a bucket exists and create if necessary?

### ISSUE THREAD

**Issue by FyZzyss** [aio-libs/aiobotocore#839]
How can I check if a bucket exists? And if the bucket doesn't exist, create a new one with the passed name.

**Comment by thehesiod** [comment]
this is more of a generic botocore question, there are a variety of mechanisms, you can either run list buckets first, or try to create it and handle the error returned

**Comment by thehesiod** [comment]
closing, feel free to re-open if this isn't a generic botocore question, if so suggest asking there.
