### ISSUE TITLE
Replace PyUp bot with GitHub Dependabot

### ISSUE THREAD

**Issue by ediskandarov** [aio-libs/aiobotocore#847]
Many projects migrate to `dependabot`.

https://bluesock.org/~willkg/blog/mozilla/pyup_to_dependabot.html

> Starting in October of 2019, pyup stopped doing monthly updates. A co-worker of mine tried to contact them to no avail. I don't know what happened. I got tired of waiting for it to start working again.

PyUp seems to stop working.

**Comment by thehesiod** [comment]
open to PR or pointers to other projects that have this setup so we can copy :)
