### ISSUE TITLE
How can I upload file as public  ie 'acl': 'public-read'

### ISSUE THREAD

**Issue by awemulya** [aio-libs/aiobotocore#849]
**Describe the Issue**
expection to upload a file publiclly,
```
client.put_object(
    Bucket=bucket, Key=_name, Body=_file.read(), extra_args={'ACL': 'public-read'})
)
```

How can I achieve this in aiobotocore

IN boto core I use to do 
```
transfer.upload_file('/tmp/myfile', bucket, key,
                     extra_args={'ACL': 'public-read'})
```

**Comment by thehesiod** [comment]
FYI for questions like this you should add it to the discussions panel.  you can do it like this which works in botocore + aiobotocore:

```python
with open('file.txt') as file_handle:
    client.put_object(Bucket=bucket, Key=key, Body=file_handle)
```

**Comment by awemulya** [comment]
@thehesiod I am uploading files the same way you explained, 
but the file urls are not accessible in my case,
`with open('file.txt') as file_handle:
    client.put_object(Bucket=bucket, Key=key, Body=file_handle)`

**Comment by thehesiod** [comment]
what do you mean by `url give permission denied`?  What's the exception and stack trace look like?

**Comment by thehesiod** [comment]
btw I think we have a misunderstanding, `upload_file` is a boto3 method, this is aiobotocore, not aioboto3, please try with https://github.com/terrycain/aioboto3

**Comment by thehesiod** [comment]
@terrycain can help you.  You can deconstruct what boto3 does for this method (it's just a layer on top of botocore), and try the equivalent in aiobotocore if you'd like.  Otherwise if you want the `upload_file` you should use aioboto3

**Comment by awemulya** [comment]
I am using aiobotocore .
```
boto_session = aiobotocore.get_session()
async with boto_session.create_client(
        "s3",
        region_name=settings.do_region_name,
        endpoint_url=settings.do_endpoint_url,
        aws_access_key_id=settings.do_access_key_id,
        aws_secret_access_key=settings.do_secret_access_key,
    ) as client:
    upload_image_to_space(**)
```

``` 
async def upload_image_to_spaces(
    boto_client, bucket: str, filename: Path, folder_path: str = None
):
    _name = filename.name
    if folder_path:
        _name = f"{folder_path}/{_name}"
    with open(filename, "rb") as _file:
        _ = await boto_client.put_object(
            Bucket=bucket, Key=_name, Body=_file.read()
        )

```
Files are uploaded but cannot be viewed publicly.
I want to upload files to storage with publicly accessible.

@thehesiod @terrycain  Have I described my problem corectly.

**Comment by thehesiod** [comment]
boto3 takes the param `extra_args={'ACL': 'public-read'}` which does this, and translates that to some other botocore API.  You need to figure out what it does, or use aioboto3

**Comment by jone** [comment]
I just spend some time with this problem with MinIO, so maybe this could help someone.

I tried to set the canned ACL with `put_object(..., ACL='public-read')`, but it simply was not set.
The problem is actually that MinIO simply does not support canned ACLs.
