### ISSUE TITLE
Feature Request: AioBotocore Specific User-Agent

### ISSUE THREAD

**Issue by joguSD** [aio-libs/aiobotocore#853]
Right now AioBotocore uses Botocore's user agent from what I can tell:
```python
'User-Agent': b'Botocore/1.19.52 Python/3.7.6 Darwin/18.7.0'
```

It's pretty trivial to override the user agent configuration for the `botocore.session.Session` class by updating `user_agent_name` and `user_agent_version`.

We can do this in the same manner as botocore by setting these values in the `AioSession` constructor:
```python
super().__init__(session_vars, event_hooks, include_builtin_handlers, profile)

self.user_agent_name = 'AioBotocore'
self.user_agent_version = aiobotocore.__version__
```

Is this something you would consider changing or is there a specific reason that you're keeping the botocore user agent?

**Comment by terrycain** [comment]
I think this would be a good thing. If anything I'm sure aws does some analytics on api requests so we'd show up

**Comment by thehesiod** [comment]
aiobotocore is defaulting to behave like botocore right now, no specific reason to my knowledge. This is only visible to the AWS backend (or moto or similar), and easily overridable as you stated. 

my worry would be aws changing their behavior for whatever reason based on the user_agent.  The safest I think would be adding a `Aiobotocore/[version]` to the existing string, however that would change the behavior where setting the `user_agent_name` right now replaces the botocore part yet leave the aiobotocore part.

Replacing the user-agent wholesale I'm not convinced on yet.  Perhaps we can parameterize it via a custom config, thoughts?

**Comment by joguSD** [comment]
Using the changes suggested you'd go from a User-Agent that looks like:
```
'User-Agent': b'Botocore/1.19.52 Python/3.7.6 Darwin/18.7.0'
```
To something that looks like:
```
'User-Agent': b'AioBotocore/1.2.0 Python/3.7.6 Darwin/18.7.0'
```

Given that the User-Agent is a publicly configurable option on botocore clients I don't think there's much potential for a User-Agent change to impact service-side behavior.

If you're still concerned we could leverage the `user_agent_extra` field to retain the original botocore user agent:

```
self.user_agent_extra = 'AioBotocore/%s' % aiobotocore.__version__
```
Which would produce a User-Agent like:
```
b'Botocore/1.19.52 Python/3.7.6 Darwin/18.7.0 AioBotocore/1.2.0'
```

**Comment by thehesiod** [comment]
i think it would be better to go to 
`'AioBotocore/1.2.0 Botocore/1.19.52 Python/3.7.6 Darwin/18.7.0'`
as that's more representative.  but like i said, if we do do that then the meaning of the override changes behavior, but maybe that's ok

**Comment by thehesiod** [comment]
let me know what you guys think about https://github.com/aio-libs/aiobotocore/pull/870

**Comment by jakob-keller** [comment]
I'm very much in favor of customising the `User-Agent` header: It would improve visibility for `aiobotocore` at AWS and might help them to prioritize providing first party asyncio support in `botocore` (#36).

The syntax of the `User-Agent` header is guided by standards and convention: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

AWS's own `aws-cli` project already uses the mechanisms provided by `botocore` for `User-Agent` customization:
https://github.com/aws/aws-cli/blob/b862122c76a3f280ff34e93c9dcafaf964e7bf9b/awscli/clidriver.py#L84

I think we should follow their lead and mimic that behavior. The resulting `User-Agent` header would look something like:

`aiobotocore/2.10.0 Python/3.7.6 Darwin/18.7.0 botocore/1.34.22`

I will prepare a PR along these lines.
