### ISSUE TITLE
Requirements botocore pegging. Is an upgrade possible?  

### ISSUE THREAD

**Issue by julianmack** [aio-libs/aiobotocore#855]
Currently the botocore requirements are pegged as:
```python
'botocore>=1.19.52,<1.19.53',
```
However, for my application I need botocore 1.20. -is there any plan to upgrade to this?

**Comment by thehesiod** [comment]
we do them ad-hoc, if no one gets to this will look asap, been swamped at work.  Feel free to submit PR as well!

**Comment by thehesiod** [comment]
done https://github.com/aio-libs/aiobotocore/releases/tag/1.3.0
