### ISSUE TITLE
Signature Expired error

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#864]
In an AWS-Lambda ("main" lambda) that can run up to the limit of 15 mins, a single aiobotocore session is used to spawn a single lambda client to run many lambda functions (a lambda calls many other lambdas in a map/reduce operation).  The following error is observed at some point within a 15 min window of the lambda runtime:

```
[ERROR] ClientError: An error occurred (InvalidSignatureException) when calling 
the Invoke operation: Signature expired: 20210426T210213Z is now earlier 
than 20210426T210213Z (20210426T210713Z - 5 min.)
```

This error is not handled, so it causes the "main" lambda to crash while many concurrent "map" lambda functions are running.  

The traceback doesn't contain much detail
```
/opt/python/lib/python3.7/site-packages/aiobotocore/client.py
154
raise error_class(parsed_response, operation_name)
^ ClientError An error occurred (InvalidSignatureException) when calling 
the Invoke operation: Signature expired: 20210426T210213Z is now earlier 
than 20210426T210213Z (20210426T210713Z - 5 min.)
/opt/python/lib/python3.7/site-packages/aio_aws/aio_aws_lambda.py
164
response = await lambda_client.invoke(**self.params)
```

Is there any `config` option that can be passed during the client creation to avoid this signature expiry error?  Are there any settings available to define the signature expiry / TTL in a Config object?  Since a single AWS-Lambda function can run for 15 mins, it would be ideal to set the expiry / TTL to at least 15 mins.

**Comment by thehesiod** [comment]
can you verify this is unique to aiobotocore, or is this a fundamental botocore issue?

**Comment by thehesiod** [comment]
also are you sure this isn't a bug in aio_aws ?  signatures are generated during calls to AWS methods in aiobotocore/botocore, they're not cached.  The only thing cached is the cert, which is auto renewed before it expires

**Comment by dazza-codes** [comment]
The traceback points to line 154 of `aiobotocore.client.py` rather than anything in botocore exactly.  I guess that means it lies in aiobotocore or something that it is doing to handle an error raised by botocore?

AFAIK, the `aio-aws` lib does nothing explicit with signatures and this is the first time I've seen this error.  This could be because this is a relatively new use-case of using a single aiobotocore/botocore client instance in a process running for a long time.  Although this has not occurred for AWS-Batch jobs, which run for a long time.

**Comment by dazza-codes** [comment]
Similar issue reported in:
- https://github.com/aws/aws-sdk-net/issues/1506

**Comment by thehesiod** [comment]
that's just because we've overloaded `_make_api_call`, raising the exception from our version, not that this it's a specific aiobotocore issue

**Comment by thehesiod** [comment]
here's the docs: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/Runtime/TClientConfig.html .  I don't think there's an equivalent in botocore, I'd add a feature request, if they support it aiobotocore will as well.  Basically botocore will retry up to 5 times, IIRC w/ a randomly increasing timeout, if it doesn't re-sign between retries theoretically the signature could become invalid.

**Comment by thehesiod** [comment]
a workaround could be to set retries to 1 and do retries yourself

**Comment by dazza-codes** [comment]
Is a signature cached along with a connection and could it live for a long time in a connection pool?

**Comment by thehesiod** [comment]
the signature is part of the request headers and is "cached" along with the request object.  It will live for as long as the request is held onto by botocore

**Comment by dazza-codes** [comment]
The signature expired after 5 mins and the config used a read timeout of 300 sec (5 mins), but the lambda function it is reading from might take longer than 5 mins to execute.  Maybe the signature TTL is auto-configured to correspond to the read-timeout (guessing).  I'll try to bump the read-timeout to 15 mins plus a buffer (960 sec), which is crazy -- because the "main" lambda doing the reading using a lambda client to read from another "map" lambda and the "main" lambda will itself timeout before then.

**Comment by thehesiod** [comment]
see `ExponentialBackoff` in botocore for the max retry length.  however looking at `Endpoint._send_request` it seems to be creating a new request for each retry so it shouldn't be caching the signature.  Most likely the signature expired between being generated and consumed by AWS.  This whole error though should be retried so something interesting must be going on, I'd enable DEBUG logging for botocore to see what's going on

**Comment by dazza-codes** [comment]
I think I'm persuaded that this is not an issue for aiobotocore.  AFAICT, it may have nothing to do with aiohttp or connection pooling therein.

**Comment by thehesiod** [comment]
ya I don't think it is, we don't do anything special in regards to this
