### ISSUE TITLE
Can a Client be used in different event loops?

### ISSUE THREAD

**Issue by librehat** [aio-libs/aiobotocore#865]
Once I create a `Client` instance, is it safe to run different operations asynchronously using the same client instance?

The example usage `await` each operation so it's not clear whether it'd be allowed to do such a thing, e.g. `asyncio.gather()` with multiple operations

**Comment by thehesiod** [comment]
yes, each client supports up to [max_pool_connections](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html) operations at the same time
