### ISSUE TITLE
Change 1.4.0 to 2.0.0 when it removes AioSession and get_session top level names

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#880]
The changes in 1.4.0 really feel like a massive breaking change rather than only a new feature enhancement.  As I understand sem-ver practices, that constitutes a breaking API change that requires a 2.x.x release.
- https://semver.org/

Can the 1.4.0 release get pulled back from pypi?  If not, I have to start to pin dependent libs on a ~1.3.x release of aiobotocore.

**Comment by thehesiod** [comment]
hmm, what do you think about minor bump where we change the exceptions to be subclasses of the asyncio + botocore exceptions?  then it should be backwards compatible

**Comment by dazza-codes** [comment]
I haven't had time to investigate further to understand the intentions behind the changes for 1.4.0; I'm sure they are good intentions.  I'm in a rush to do some other things and noticed that my aio-aws library now needs to pin aiobotocore to 1.3.x to avoid the breaking changes.  I did quickly read the change log to get some idea of what's happening, but have not yet digested any related PRs for the changes, or tried to update aio-aws to adapt to the changes.  I'm just in a reactive-mode at present, to move along with more downstream concerns.  I will have to come back to this soon, since aiobotocore is so valuable 🚀

**Comment by thehesiod** [comment]
Oh i misread this is in regard to the aiosession change, hmm

**Comment by thehesiod** [comment]
I think what I'll do is put the links back in 1.4.1 and do the subclass thing to make it backwards compatible later tonight

**Comment by thehesiod** [comment]
Then 2.0 remove the links

**Comment by JustinTArthur** [comment]
Thanks, a lot of red lines in CI/CD consoles today

**Comment by thehesiod** [comment]
@JustinTArthur @dazza-codes want to try the linked PR?

**Comment by thehesiod** [comment]
fyi the changes are in the right direction either way going forward, so doesn't hurt to do if you can't wait for this release coming up. It was basically to bring the aiobotocore apis in-line with botocore

**Comment by thehesiod** [comment]
actually I have to change the exception type, because otherwise the retry won't work, hmmm

**Comment by thehesiod** [comment]
@mariaines warning of upcoming change, in 1.4.1 you'll need to set `AIOBOTOCORE_DEPRECATED_1_4_0_APIS` env var to 0 so that we don't break API compatibility until 2.0 w/o that env var.
