### ISSUE TITLE
Incompatible with botocore >= 1.21.0

### ISSUE THREAD

**Issue by rggjan** [aio-libs/aiobotocore#890]
Due to dependencies, it is impossible to install `aiobotocore` together with any other package depending on a recent version of botocore. For example:

```
aiobotocore==1.4.2 depends on botocore < 1.20.107
boto3==1.18.0 depends on botocore>=1.21.0
```

Which also makes it impossible to install packages with a dependency on `boto3>=1.18.0`

**Comment by rggjan** [comment]
Thanks @terrycain 
Unfortunately that doesn't help when I (or a package I need) depends on boto3>=1.18.0

**Comment by thehesiod** [comment]
I think what you're saying is you'd like a version bump

**Comment by thehesiod** [comment]
will get on it asap

**Comment by thehesiod** [comment]
going to try to carve out time for this today

**Comment by yogevyuval** [comment]
@thehesiod Thanks a lot!
Is there going to be a release soon in pypi?

**Comment by thehesiod** [comment]
o strange, sometime must have happened because it was supposed to get released automatically, let me c

**Comment by thehesiod** [comment]
looks like 3.10 is not valid in setup.py, lets see if it gets released now

**Comment by thehesiod** [comment]
ok up https://pypi.org/project/aiobotocore/
