### ISSUE TITLE
Starlette StreamReader not reading all chunks in aio s3 get_object response

### ISSUE THREAD

**Issue by scattym** [aio-libs/aiobotocore#891]
**Describe the bug**
I originally filed this as a bug against starlette, but I have since confirmed+validated that passing a raw aiohttp response (response.content.iter_any()) to starlette StreamingResponse results in expected behaviour. Apologies if this is still not the right place for this bug but I am struggling to track the execution path through the feed_data handling...

Passing a web.StreamReader returned from AioBoto S3 get_object() function to a StreamingResponse results in a hung connection. I can't yet tell if this is because of an incompatibility between the StreamingResponse and the aiohttp web.StreamReader, or if this is a bug.

**Checklist**
- [X] I have reproduced in environment where `pip check` passes without errors
- [X] I have provided `pip freeze` results
- [X] I have provided sample code or detailed way to reproduce
- [X] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [X] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [X] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

```
aioboto3==9.2.2
aiobotocore==1.4.2
aiohttp==3.7.3
aioitertools==0.8.0
aioredis==2.0.0
anyio==3.3.4
asgiref==3.4.1
async-timeout==3.0.1
attrs==21.2.0
boto3==1.17.106
botocore==1.20.106
chardet==3.0.4
click==8.0.3
gunicorn==20.1.0
h11==0.12.0
hiredis==2.0.0
idna==3.3
jmespath==0.10.0
multidict==5.2.0
prometheus-client==0.11.0
python-dateutil==2.8.2
python-json-logger==2.0.2
s3transfer==0.4.2
six==1.16.0
sniffio==1.2.0
starlette==0.16.0
starlette-exporter==0.11.0
typing-extensions==3.10.0.2
urllib3==1.26.7
uvicorn==0.15.0
uvloop==0.16.0
wrapt==1.13.2
yarl==1.7.0
```

**Environment:**
 - Python Version: 3.9.0
 - OS name and version: linux

### To reproduce

```python
import logging
import aioboto3
from starlette.applications import Starlette
from starlette.responses import StreamingResponse
from starlette.routing import Route

logger = logging.getLogger(__name__)

async def read_bytes(s3_obj):
    chunk_size = 1024
    async with s3_obj["Body"] as stream:
        file_data = await stream.read(chunk_size)
        while file_data:
            yield file_data
            file_data = await stream.read(chunk_size)


async def yield_bytes(s3_ob):
    while True:
        chunk = await s3_ob["Body"].readchunk()
        yield chunk[0]
        if chunk[1]:
            break


async def proxy_fragment_request(request):

    boto3_session = aioboto3.Session()
    async with boto3_session.client(
            "s3",
            endpoint_url='http://minios3server.local',
            aws_access_key_id='SOMEKEY',
            aws_secret_access_key='SOMEPASS',
    ) as s3:
        bucket = 'bucket1'
        blob_s3_key = 'bigfile'  # bigfile is only around 30KB i.e. more than approx 4096 and I see the issue
        s3_ob = await s3.get_object(Bucket=bucket, Key=blob_s3_key)

        # return StreamingResponse(yield_bytes(s3_ob))
        # return StreamingResponse(read_bytes(s3_ob))
        return StreamingResponse(s3_ob["Body"])

routes = [
    Route("/tests3", endpoint=proxy_fragment_request),
]

app = Starlette(routes=routes)


def main():
    import uvicorn

    logger = logging.getLogger('')
    logger.setLevel(logging.DEBUG)
    ch = logging.StreamHandler()
    ch.setLevel(logging.DEBUG)
    formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    ch.setFormatter(formatter)
    logger.addHandler(ch)
    uvicorn.run(app, http='h11', loop='uvloop', log_level=0)


if __name__ == "__main__":
    main()

```

### Expected behavior

Full file streamed to the client

### Actual behavior

Streaming stops after first 4KB read

### Debugging material

I have tried the following functions to abstract away the StreamReader, but with similar results:

```python
async def read_bytes(s3_obj):
    chunk_size = 1024
    async with s3_obj["Body"] as stream:
        file_data = await stream.read(chunk_size)
        while file_data:
            yield file_data
            file_data = await stream.read(chunk_size)
return StreamingResponse(read_bytes(s3_ob))

async def yield_bytes(s3_ob):
    while True:
        chunk = await s3_ob["Body"].readchunk()
        yield chunk[0]
        if chunk[1]:
            break
return StreamingResponse(yield_bytes(s3_ob))

```

### Environment

- OS: Linux
- Python version: 3.9.0
- Starlette version: 0.16.0 (tested back to the version that starts checking for for AsyncIterator)

### Additional context

I tracked the execution chain through to aiohttp waiting for the reader to request more data (or at least that's what I think it's doing) in aiohttp/streams.py line 306. i.e.:

```python
        waiter = self._waiter = self._loop.create_future()
        try:
            if self._timer:
                with self._timer:
                    await waiter  ## <---------- last call I see
            else:
                await waiter
        finally:
            self._waiter = None
```

When I ctrl-c the app it still believes there are open connections:
2021-10-15 13:14:23,702 - uvicorn.error - INFO - Shutting down
2021-10-15 13:14:23,803 - uvicorn.error - INFO - Waiting for connections to close. (CTRL+C to force quit)

If I instead ctrl-c the client (curl instance) then code picks up from the await waiter line above.

**Comment by thehesiod** [comment]
There are some known issues with low level asyncio streams, want to try with uvloop?

**Comment by thehesiod** [comment]
thank you for the experiment! so must be a logic issue in aiohttp/aiobotocore, hopefully me or someone else can help investigate soon

**Comment by thehesiod** [comment]
I've repro'd btw, great testcase. unfortunately I have a travel emergency so won't get to investigate this for a bit, but definitely on my radar as I'd like to get a resolution to this as well.

**Comment by thehesiod** [comment]
ok this is user error, you're closing the client `s3` from the `async with clause` after the line `return StreamingResponse(s3_ob["Body"])` so in effect pulling the rug from underneath yourself :). You should init the client with like `on_startup` and pass it to your method

**Comment by scattym** [comment]
Ugh sorry. Well, that's great news and thank you for looking into this.
