### ISSUE TITLE
Consider support more versions of botocore

### ISSUE THREAD

**Issue by dnp1** [aio-libs/aiobotocore#898]
I'm currently using aws lambda, however I could not find any versions matching the lambda provided versions of botocore

for python 3.9 is boto3-1.18.55 botocore-1.21.55

Due to the fact botocore is "enormous" I would use the available one instead of installing a new one.

**Comment by thehesiod** [comment]
we did consider it, too much work, we'd have to support all code changes across all overridden methods across all versions.  We just bumped botocore recently, please request newer updates or submit PRs
