### ISSUE TITLE
New Versions Breaks pandas read_csv when used from AWS Sagemaker Studio

### ISSUE THREAD

**Issue by Deom23** [aio-libs/aiobotocore#899]
**Describe the bug**

I am running jobs in AWS sagemaker studio, and the new version of this package that was released in 2.0 is breaking the functionality of pandas read_csv for some reason. When trying to read a file from S3 into python, I receive this error:

AttributeError: 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'

If I manually install the older version of the package to the kernal, then everything works as expected. 

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: [e.g. 3.7]
 - OS name and version: [e.g. darwin stretch]

**Additional context**

**Comment by thehesiod** [comment]
Interesting, will look into it, probably a missing import from the botocore bump

**Comment by thehesiod** [comment]
dup of https://github.com/aio-libs/aiobotocore/issues/900

**Comment by thehesiod** [comment]
issue is mismatched requirements, ensure the botocore matches the version required by aiobotocore. re-open if something diff

**Comment by allomer** [comment]
In our case I only had to update aiobotocore==2.0.1 (default DataScience image / Python3 kernel has 1.4.2) and restart the SageMaker Studio kernel, and this error went away. Thx @thehesiod
