### ISSUE TITLE
bump to botocore 1.23.0 or later

### ISSUE THREAD

**Issue by hayashier** [aio-libs/aiobotocore#904]
Some packages depends on aiobotocore, but aiobotocore doesn't support botocore 1.23.0 or later.

https://github.com/aio-libs/aiobotocore/blob/2.0.1/setup.py#L10
```
'botocore>=1.22.8,<1.22.9',
```

So, due to dependencies, it is impossible to update the packages which depends on botocore to 1.23.0 or later.

When I updated botocore to 1.23.14, I faced this issue(https://github.com/aio-libs/aiobotocore/issues/900, https://github.com/aio-libs/aiobotocore/issues/905).

boto is used by many different libraries, so it is difficult to lock the boto version.

That is why I opened this issue which requests to bump to botocore 1.23.0 or later (For example, 1.23.14).

Thanks,

**Comment by thehesiod** [comment]
Will work on a bump hopefully today

**Comment by yan12125** [comment]
Any updates? The patch mentioned at https://github.com/aio-libs/aiobotocore/issues/905#issuecomment-980524777 looks good. A confirmation from the maintainer will be better.

**Comment by hayashier** [comment]
@thehesiod I confirmed this error was resolved with aiobotocore 2.1.0. Thank you very much!
