### ISSUE TITLE
Documentation regarding assuming roles

### ISSUE THREAD

**Issue by nilsdebruin** [aio-libs/aiobotocore#911]
Is there documentation regarding the creation of temporary credentials based on assumed roles?

We now have aiobotocore combined with a regular iam user to interact with AWS, but we would like to change this that the iam user needs to assume a role to interact with AWS.

Something like this:
https://github.com/benkehoe/aws-assume-role-lib

In aiobotocore I can see AioAssumeRoleProvider, but I cannot grasp how I could leverage this provider.

My use case is as follows:

I have an application that is running outside of AWS. This application only has access to the AWS keys to log in to the AWS cloud. It does not contain a local ~/.aws/config or ~/.aws/credentials. At this moment, this user logs in with the credentials and gets direct access to the resources. I want to change this and let the user log in, assume a role, and then access the resources.

**Comment by thehesiod** [comment]
I would re-write that lib to be async by using aioboto3

**Comment by nilsdebruin** [comment]
@thehesiod thanks for your answer, great suggestion!

Out of curiosity, should the following snippet work, when assumed role credentials are used?

```
credentials = await get_role_credentials(session)
    async with session.create_client('sts', aws_access_key_id=credentials["AccessKeyId"], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials["SessionToken"]):
        second_async_caller = await client.get_caller_identity()
```

I now get:

```
botocore.exceptions.HTTPClientError: An HTTP Client raised an unhandled exception: Session is closed
```

**Comment by thehesiod** [comment]
i think you example above is incomplete, where did `get_session` come from, also it's confusing, you appear to be mixing and matching boto3 + aiobotocore

**Comment by nilsdebruin** [comment]
I understand it can be confusing, apologies for that! I wanted to show an example of both approaches in one. The following example is only using aiobotocore:

```
from aiobotocore.session import get_session
import asyncio

AWS_ACCESS_KEY_ID = "AKAASDASDSDASDSAD"
AWS_SECRET_ACCESS_KEY = "j34j34kkjfkdjfkdjfkdjkfjk34"
role_arn = "arn:aws:iam::123456789:role/testrole"

# Supporting function to get role credentials
async def get_role_credentials(session):
    # Here we create an sts client and assume a role based on the role_arn
    async with session.create_client('sts', aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY) as client:
        response = await client.assume_role(
            RoleArn=role_arn,
            RoleSessionName="RoleSession"
        )

    return response['Credentials']

async def go():
    session = get_session()
    # Here we create an sts client and get the caller identity (the current AWS user / role)
    async with session.create_client('sts', aws_access_key_id=AWS_ACCESS_KEY_ID, aws_secret_access_key=AWS_SECRET_ACCESS_KEY) as client:
        first_async_caller = await client.get_caller_identity()
        print(first_async_caller)
    
    # Here we get the role credentials based on the supplied AWS credentials
    credentials = await get_role_credentials(session)
    # Here we create an sts client based on the assumed role credentials and get the caller identity (the assumed AWS role)
    async with session.create_client('sts', aws_access_key_id=credentials["AccessKeyId"], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials["SessionToken"]):
        second_async_caller = await client.get_caller_identity()

        print(second_async_caller)

loop = asyncio.get_event_loop()
loop.run_until_complete(go())

**Comment by thehesiod** [comment]
you have a typo, after fixing:
```python
    async with session.create_client('sts', aws_access_key_id=credentials["AccessKeyId"], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials["SessionToken"]):
```

->

```python
    async with session.create_client('sts', aws_access_key_id=credentials["AccessKeyId"], aws_secret_access_key=credentials['SecretAccessKey'], aws_session_token=credentials["SessionToken"]) as client:
```

it works

**Comment by nilsdebruin** [comment]
Thanks for helping out and spotting the typo!!! Unfortunately, it still doesn't work, I get the following exception:

```
Traceback (most recent call last):
  File "/Users/nilsdebruin/Library/Caches/pypoetry/virtualenvs/pipeline-2rqYbmAC-py3.8/lib/python3.8/site-packages/aiobotocore/httpsession.py", line 172, in send
    resp = await self._session.request(
  File "/Users/nilsdebruin/Library/Caches/pypoetry/virtualenvs/pipeline-2rqYbmAC-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 399, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed

**Comment by thehesiod** [comment]
make sure your botocore matches that your aiobotocore version request, works for me:
```bash
04:57 AM alexmohr@amohr-C02C870YMD6M ~/dev/fbn.com/ops/fbn_async_server (thehesiod/temp)$ pip3 list | grep botocore
aiobotocore              2.1.0
botocore                 1.23.24
```

**Comment by nilsdebruin** [comment]
Thanks for your replies and helping out! Unfortunately it still doesn't work. This is my output:
```
❯ pip3 list | grep botocore
aiobotocore                       2.1.0
botocore                          1.23.24
```

Could it maybe be aiohttp? This is my version:
```
❯ pip3 list | grep aiohttp
aiohttp                           3.8.1
```

I am using Python 3.8.5

**Comment by thehesiod** [comment]
Can you create a docker container that reproduces the issue?

**Comment by nilsdebruin** [comment]
Sorry for my delayed response! I created a docker container, only containing aiobotocore in combination with Python 3.8. It looks like it is working now, so maybe it could be something in combination with my project (other dependencies) or my M1 Mac! Thanks for your help and responses, it is really appreciated!
