### ISSUE TITLE
Event loop blocked during client-side rate limiting?

### ISSUE THREAD

**Issue by Neki** [aio-libs/aiobotocore#912]
**Describe the bug**

This is more of a question than an actual bug at this point. I don't understand how aiobotocore avoids blocking when a retry handler is installed.

Let's assume we have an aiobotocore client with the "adaptive" retry handler installed:

```python
import asyncio
from aiobotocore.session import get_session
from aiobotocore.config import AioConfig

async def main():
    config = AioConfig(retries={"max_attempts": 5, "mode": "adaptive"})
    async with get_session().create_client("s3", config=config) as client:
        print(await client.get_object(Bucket="bucket", Key="key"))

asyncio.run(main())
```
When instantiating the client, [this code](https://github.com/aio-libs/aiobotocore/blob/0b71254446ef7ba6d93016d5a8b5b02c665a7b0b/aiobotocore/client.py#L41) is called in the `AioClientCreator.create_client` method:
```python
self._register_retries(service_client)
```
This method not overriden by aiobotocore, so from here we jump into botocore. Ultimately, we arrive at the `register_retry_handler` method [here](https://github.com/boto/botocore/blob/06b18608833ea59a501f54470efdf19926f701cd/botocore/retries/adaptive.py#L13):
```python
def register_retry_handler(client):
    # ... skipped some lines
    limiter = ClientRateLimiter(
        token_bucket=token_bucket,
    )
    client.meta.events.register(
        'before-send', limiter.on_sending_request,
    )
```

aiobotocore emits the ["before-send" event](https://github.com/aio-libs/aiobotocore/blob/0b71254446ef7ba6d93016d5a8b5b02c665a7b0b/aiobotocore/endpoint.py#L141) normally. Reading through the aiobotocore event machinery, it seems that it ends up directly calling the `limiter.on_sending_request` method registered above.

This [method](https://github.com/boto/botocore/blob/06b18608833ea59a501f54470efdf19926f701cd/botocore/retries/adaptive.py#L52) is:
```python
def on_sending_request(self, request, **kwargs):
    if self._enabled:
        self._token_bucket.acquire()
```
where `self._token_bucket.acquire()` comes from the [`TokenBucket` class](https://github.com/boto/botocore/blob/06b18608833ea59a501f54470efdf19926f701cd/botocore/retries/bucket.py#L19). The key elements are:

```python
class TokenBucket(object):

    def __init__(self, max_rate, clock, min_rate=_MIN_RATE):
        # ...
        self._lock = threading.Lock()
        self._new_fill_rate_condition = threading.Condition(self._lock)

    def acquire(self, amount=1, block=True):
        """Acquire token or return amount of time until next token available.

        If block is True, then this method will block until there's sufficient
        capacity to acquire the desired amount.

        If block is False, then this method will return True is capacity
        was successfully acquired, False otherwise.

        """
        with self._new_fill_rate_condition:
            # ...
```
so it seems to me that we may block on a `threading.Condition` here. Am I missing something? The `retry` parameter in the AioConfig object is explicitly covered by tests, so maybe there's a part of the code I'm overlooking.

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [x] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [x] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

```
aiobotocore==2.1.0
aiohttp==3.8.1
aioitertools==0.8.0
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
botocore==1.23.24
charset-normalizer==2.0.10
frozenlist==1.3.0
idna==3.3
jmespath==0.10.0
multidict==6.0.2
python-dateutil==2.8.2
six==1.16.0
urllib3==1.26.8
wrapt==1.13.3
yarl==1.7.2
```

**Environment:**
 - Python Version: [e.g. 3.6] 3.8.10
 - OS name and version: [e.g. darwin stretch] Ubuntu 20.04

**Additional context**

I stumbled into this while trying to understand in detail the retry behaviour of aiobotocore. In our production systems, we do observe that our event loop is sometimes blocked, but there's nothing that points so far to this specific issue. I'm asking this question purely based on reading the code.

**Comment by thehesiod** [comment]
it's definitely possible you may have found a missing override, things end up getting more and more convoluted as they add features.  Will check asap

**Comment by thehesiod** [comment]
ya, this is busted for this type rate limiter, will require quite a bit of work to fix as we'll need an async token bucket as well as async version of items in adaptive.py, will try to carve up some time to do this, otherwise feel free to post PR

**Comment by thehesiod** [comment]
btw started work on adding test here: https://github.com/aio-libs/aiobotocore/pull/913

**Comment by Neki** [comment]
I'm definitely happy to submit a PR :) the approach would be to override `_register_retries` in `create_client` and register a custom async ClientRateLimiter. If we inherit from the existing classes in botocore there's not that much code to change. I'll try to get it done this week. Thanks for the test, it will come in handy.

I think the other retry strategies are also impacted (see for instance in `retries/quota.py` the `acquire` method that also waits for a `threading.Lock`), but as a first step I can implement the async version of the adaptive retry strategy, and emit a warning when another strategy is selected.

**Comment by thehesiod** [comment]
ya we typically inherit, you can see examples in our code
