### ISSUE TITLE
[consent request] Permission to publish `types-aiobotocore` package to PyPI

### ISSUE THREAD

**Issue by vemel** [aio-libs/aiobotocore#916]
Hello!

I am the guy behind [boto3-stubs](https://pypi.org/project/boto3-stubs/) package that provides auto-complete and type checking for all `boto3` modules.

I have just finished adding support for `aiobotocore` here: https://github.com/vemel/mypy_boto3_builder/pull/127

If you do not mind, I am going to publish `types-aiobotocore` (static stubs for `aiobotocore`) and `types-aiobotocore-<service>` (explicit type annotations for a particular `botocore` service) packages to PyPI, as well as create a new repo with documentation for `types-aiobotocore`.

I would also be happy to get feedback regarding `types-aiobotocore`, because I am not actively using this library.

Docs: https://vemel.github.io/types_aiobotocore_docs/

Regards, Vlad.

**Comment by thehesiod** [comment]
I'd like it to work like botocore, how does it correctly work for botocore?

**Comment by vemel** [comment]
For boto3/botocore:

- it adds overloads for `boto3.client` / `boto3.resource`, so client type can be discovered implicitly
- for dynamic client/resource creation, you can use `mypy-boto3-<service>` packages to explicitly set types

For aiobotocore:
- no implicit typing, but I already have the necessary code. I did not test performance though
- for dynamic client creation, you can use `types-aiobotocore-<service>` packages to explicitly set types

**Comment by vemel** [comment]
Here we go: https://pypi.org/project/types-aiobotocore/

**Comment by thehesiod** [comment]
cool, well if it's the same I'm all for it!

**Comment by thehesiod** [comment]
going to close since i think this is resolved?

**Comment by vemel** [comment]
Would it be helpful to add `types-aiobotocore` installation instruction and link to docs to `README`?

**Comment by thehesiod** [comment]
@vemel sure, want to create PR?

**Comment by vemel** [comment]
@thehesiod Hello! Sorry to bother you, but could you please take a look at the PR and let me know if there is anything else to be done.
