### ISSUE TITLE
Bump `botocore` & remove restriction

### ISSUE THREAD

**Issue by kaxil** [aio-libs/aiobotocore#924]
### Discussed in https://github.com/aio-libs/aiobotocore/discussions/920

<div type='discussions-op-text'>

<sup>Originally posted by **kaxil** March  1, 2022</sup>
Hi team,

[Apache Airflow](https://github.com/apache/airflow) Committer here 👋 , I would like to propose that we remove the pinned version of `botocore` if there is no specific reason (please correct me if there is a reason).

https://github.com/aio-libs/aiobotocore/blob/40215851cbc48b01428ae43565d827fa8436d040/setup.py#L10

In the Airflow project, we provide a set of known working Constraints files (for each python version) with every Airflow release described in https://github.com/apache/airflow#installing-from-pypi

In general, if you restrict the version of botocore, it makes it very difficult to satisfy dependencies from all the other projects.

Context: We are building new Airflow Operators leveraging Python's Async framework and using `aiobotocore` lib (thanks for all the work here) to interact with AWS services. 

I understand if you pin the major version for `botocore` but is there a reason we can't bump this dependency?</div>

**Comment by thehesiod** [comment]
there is a very specific reason it is pinned, please read https://github.com/aio-libs/aiobotocore/blob/master/CONTRIBUTING.rst#background-and-implementation we can definitely do a bump to the latest though.  Will work on it asap, or if you'd like to propose a PR too it's welcome.  It is fairly involved though as you need to validate all changes made to all functions/classes we override

**Comment by kaxil** [comment]
That sounds good, looks like it is definitely more involved and manual than I thought :) so would wait for your PR for now.

**Comment by kaxil** [comment]
Awesome, thanks @thehesiod
