### ISSUE TITLE
ImportError cannot import name 'is_valid_ipv6_endpoint_url' from 'botocore.endpoint'

### ISSUE THREAD

**Issue by dazza-codes** [aio-libs/aiobotocore#925]
### First some context

We are using an AWS-Lambda runtime and packaging aiobotocore, but relying on AWS-Lambda to provide botocore, so there is always a risk that the two libraries will be incompatible at some point.  The deployment strategies and packaging can apply some hacks and tests to check compatibility, which results in a deployment that either crashes hard or it works all of the time (until AWS-Lambda changes the runtime).  The AWS-Lambda runtime is updated occasionally, at random.  It's best practice to also bundle versions of boto3, botocore for the function  --  but due to size restrictions on a .zip layer, this is not the case in some functions we manage (this will likely change soon when a docker image is used instead of a .zip layer).

### Bug

Today there is a strange error that occurs in AWS-Lambda in us-west-2 region, but not in us-east-1 region, e.g.

```python
/opt/python/lib/python3.7/site-packages/aiobotocore/endpoint.py
5
from botocore.endpoint import EndpointCreator, Endpoint, DEFAULT_TIMEOUT, \
^ ImportError cannot import name 'is_valid_ipv6_endpoint_url' from 'botocore.endpoint' (/var/runtime/botocore/endpoint.py)
```

The interesting thing is, the error only appears when `s3fs` is imported.  It does not appear when only `aiobotocore`, `botocore` etc are imported (versions below and test function below).  It seems strange that after importing `s3fs` that it could somehow modify the runtime behavior of `aiobotocore` in this way.  I'm at a loss about how to understand this behavior, or fix it.

#### versions
```
s3fs == '2022.02.0'
aio_aws==0.18.0
aiobotocore==2.1.2
boto3==1.20.32
botocore==1.23.32
jmespath==0.10.0
dateutil==2.8.2
s3transfer==0.5.1
six==1.16.0
urllib3==1.26.6
```

### Lambda test function

```python
"""
Lambda Layer Test
*****************

This lambda function handler can test that project dependencies
can be imported from the project layer(s).

"""

import dataclasses
import json
from pprint import pprint
from types import ModuleType

import aio_aws
import aiobotocore
import boto3
import botocore
import dateutil
import jmespath

import numpy
import pandas as pd
import requests
#import s3fs   # enable this to get the crash
import s3transfer
import six
import urllib3

def lambda_handler(event, context):

    versions = {
        #"s3fs": s3fs.__version__,
        "aio_aws": aio_aws.VERSION,
        "aiobotocore": aiobotocore.__version__,
        "boto3": boto3.__version__,
        "botocore": botocore.__version__,
        "jmespath": jmespath.__version__,
        "dateutil": dateutil.__version__,
        "s3transfer": s3transfer.__version__,
        "six": six.__version__,
        "urllib3": urllib3.__version__,
    }
    pprint(versions)
    print()

    # pip requirements format
    for k, v in versions.items():
        print(f"{k}=={v}")
    print()

    return {"statusCode": 200, "body": json.dumps("package imports are OK!")}

```

**Comment by dazza-codes** [comment]
I don't know if this commonly occurs when AWS-Lambda updates the runtime in a region.  For a while, the lambda invoke results were not deterministic - i.e. suggesting that the cloud infrastructure might have contained some mixture of old and new runtimes.  After some time, things settled down and the error disappeared.

**Comment by alexanderluiscampino** [comment]
throwing my hat in the ring here, same issue. I mentioned this on `s3fs` thread [here](https://github.com/fsspec/s3fs/issues/604)

**Comment by alexanderluiscampino** [comment]
> were not deterministic - i.e. sug

Experienced the same, not deterministic behavior. I think AWS updated their shipped python libs yesterday between 5AM and 12PM PST. We saw some lambdas failing others worked fine. I believe they do rolling deployments to their servers, which takes a while until all computing servers are updated.

**Comment by alexanderluiscampino** [comment]
The question here for the maintainers of these library, `aibotocore` is how can we maintain a faster level of compatibility with the releases of `botocore`. Unfortunately, we lambda users, are at the mercy of AWS and when they decide to release a new version of their shipped libraries. In this case, the new version of `botocore==1.23.32` introduced a breaking change. Should `aibotocore` be ahead of the curve and be proactive on avoiding production issues with lambdas depending on this handy lib?

For example, `botocore` is currently on version `1.24.20`, changelog [here](https://github.com/boto/botocore/blob/develop/CHANGELOG.rst). AWS just released `1.23.32` almost one major version behind their latest. 

Is there something that is stopping `aibotocore` to be updated when `botocore` is updated, besides lack of maintainers/time?

**Comment by thehesiod** [comment]
just ppl/time.  I think I have a short break, let me try now

**Comment by thehesiod** [comment]
btw this is not a bug, as it's breaking the import requirements of aiobotocore, aiobotocore==2.1.2 requires botocore 1.23.24
