### ISSUE TITLE
Question about unit testing a Lambda function

### ISSUE THREAD

**Issue by jrobbins-LiveData** [aio-libs/aiobotocore#927]
I recently switched a Python Lambda function from synchronous to asyncio.  Some of my unit tests (using `moto`) broke, raising `AttributeError: 'AWSResponse' object has no attribute 'raw_headers'`

I searched issues in `aiobotocore` and found https://github.com/aio-libs/aiobotocore/issues/755#issuecomment-590065305, which included this statement

> So we basically don't support the moto wrapper based tests...

The comment refers to a `PR`, but in reviewing the lengthy thread, I didn't feel confident I knew which `PR` was meant.  Basically, I'm looking for recommendations on how to unit test my Lambda function, specifically needing to mock the `cognito-idp` service.  Is there an asyncio `pytest` package recommended?  Are there any tutorials or howtos?

**Comment by thehesiod** [comment]
you can see how we test lambda here: https://github.com/aio-libs/aiobotocore/blob/88a43098b1194bf759581acc710ad5bdbdd99a96/tests/test_lambda.py#L44-L73

**Comment by thehesiod** [comment]
please re-open if that does not help

**Comment by jrobbins-LiveData** [comment]
Thank you.
