### ISSUE TITLE
__anext__() magic method usage in AioPageIterator

### ISSUE THREAD

**Issue by akash329d** [aio-libs/aiobotocore#943]
This might be a misunderstanding on my end but why is `__anext__()` implemented in the [AioPageIterator](https://github.com/aio-libs/aiobotocore/blob/e4ea0edfc11951deb9f3593d24238132ea1a1e2f/aiobotocore/paginate.py#L10)? From my understanding `__anext__()` should be an awaitable whereas this function is a async generator. It still works in an `async for` since `aiter` calls the generator, but as a beginner this was pretty confusing for me. I attempted to use the `anext` builtin on an AioPageIterator object and couldn't figure out why it wasn't working initially. 

Might make more sense to just rename the __anext__ function to something else? Unless there's a reason for it that I'm missing.

**Comment by thehesiod** [comment]
this was so the code would be very similar to the botocore implementation: https://github.com/boto/botocore/blob/develop/botocore/paginate.py#L252 to make diffing easier, so ya it's pretty funky.  Open to suggestions for how to make more sense

**Comment by akash329d** [comment]
One easy way to fix it would be just just rename it to prevent confusion. But if keeping diff easy is important then I'd probably just leave it unchanged, isn't a huge issue.
