### ISSUE TITLE
PyPI Wheels

### ISSUE THREAD

**Issue by groodt** [aio-libs/aiobotocore#944]
**Describe the bug**
The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple.

It appears wheels were previously published, so a regression has occurred somewhere. 
https://github.com/aio-libs/aiobotocore/issues/58

Would you accept a PR to publish wheels?

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: [e.g. 3.6]
 - OS name and version: [e.g. darwin stretch]

**Additional context**

**Comment by yan12125** [comment]
https://github.com/aio-libs/aiobotocore/pull/946 tried to add wheel support, but [failed](https://github.com/aio-libs/aiobotocore/runs/7029545565?check_suite_focus=true) due to missing wheel package.

**Comment by yan12125** [comment]
Nice! Let's wait thehesiod for a review. I don't have the permission to merge, either.
