### ISSUE TITLE
Can't install latest s3fs + awscli/boto3 libraries due to version constraints defined in setup.py

### ISSUE THREAD

**Issue by walterdolce** [aio-libs/aiobotocore#947]
**Describe the bug**
Hello, as per title, I was trying to use the latest versions of `awscli` (1.25.16), `boto3` (1.24.16) and `s3fs` (2022.5.0), however it does not look like that's possible because aiobotocore - a dependency of s3fs - pins awscli & boto3 to specific version ranges in the setup.py file: 

https://github.com/aio-libs/aiobotocore/blob/master/setup.py#L18-L19

```
extras_require = {
    'awscli': ['awscli>=1.22.76,<1.22.77'],
    'boto3': ['boto3>=1.21.21,<1.21.22'],
}
```

Is there any chance these dependencies could be updated? Or is there a version constraint because aiobotocore would not be able to work altogether if this dependency version restriction would be lifted? 

Thanks!

**Comment by darioackermann** [comment]
We have been running `aiobotocore` with the newest boto3 / awscli version installed in parallel, without any issues so far. Since `boto3` only receives minor updates, locking boto/awscli version is probably unnecessary...

**Comment by thehesiod** [comment]
there's an open PR to upgrade, just haven't had a chance to review it, been totally swamped

**Comment by thehesiod** [comment]
bumped
