### ISSUE TITLE
Adopt black

### ISSUE THREAD

**Issue by gmsantos** [aio-libs/aiobotocore#951]
I was looking to bump the botocore version and while I was comparing the changes in [botocore](https://github.com/boto/botocore/compare/1.24.21...1.27.0?diff=unified), I noticed that botocore applied black at the codebase (https://github.com/boto/botocore/pull/2666).

Should this something aiobotocore plans to adopt? For me, it makes sense for consistency and makes it easier to compare the changes in the next botocore bumps. I am happy to do that at the same during I try to push a PR to bump botocore or as a full separate contribution.

**Comment by thehesiod** [comment]
I agree too, please do.  When bumping botocore make sure to diff botocore from old to new version and compare all the files aiobotocore overrides and apply changes as necessary, and update patch hashes.

**Comment by thehesiod** [comment]
I think this is now done right?  I saw flake complains if things aren't black compatible

**Comment by gmsantos** [comment]
yes, it should be done @thehesiod. About flake complaining about black, I can take a look. The idea behind adding flake8-black and flake8-isort was to avoid that.

https://github.com/aio-libs/aiobotocore/pull/952/commits/5933acfb0569b74f66fe79046830c2d40f11b3d0#diff-230078d672f10d17463a8a6265cad825b790885898256a3365be90685caac58dR11-R12

**Comment by thehesiod** [comment]
@gmsantos oh I just meant it's working correctly, thank you!
