### ISSUE TITLE
Failed to import 'resolve_checksum_context' from botocore

### ISSUE THREAD

**Issue by aaronclong** [aio-libs/aiobotocore#957]
**Describe the bug**
There seems to be an issue in importing 'resolve_checksum_context' from 'botocore.client'. The exact exception is `cannot import name 'resolve_checksum_context' from 'botocore.client'`. 

I have tried downgrading and upgrading my botocore several times, but can't get it to work. This library is a transitive library from `s3fs`.

![image](https://user-images.githubusercontent.com/7354981/179568443-41889586-48d4-4a1f-9e17-64f2e49d4aed.png)

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [ ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: 3.8
 - OS name and version: Windows 10

**Additional context**

**Comment by thehesiod** [comment]
you need to use the botocore that aiobotocore requires, exactly.

**Comment by aaronclong** [comment]
@thehesiod is there any way to mitigate the exact version match here? This library is coming as a transitive dep, and it was quite hard to see where this issue came from.

I am wondering if there is a way to improve this or at least make it easier for the next person.

**Comment by thehesiod** [comment]
aiobotocore needs exact matching by design, in general you should always run pip check to ensure your modules aren't in conflict, or use a module manager like pipenv/poetry
