### ISSUE TITLE
submit latest release to pypi

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiobotocore#96]
Should release the latest one to pypi, unfortunately I don't have perms ;)

**Comment by jettify** [comment]
I will do this tonight, and will add autodeploy on tag, so everyone with access to repo can deploy to pypi

**Comment by jettify** [comment]
@thehesiod done, added autodeploy on tag, just create release here https://github.com/aio-libs/aiobotocore/releases and it will be deployed to pypi automatically.

**Comment by thehesiod** [comment]
cool
