### ISSUE TITLE
Async function `_create_client()` being called in sync context

### ISSUE THREAD

**Issue by jameseggers** [aio-libs/aiobotocore#966]
**Describe the bug**
The Async function `_create_client()` being called in sync context, which results in the following error: `RuntimeWarning: coroutine 'AioSession._create_client' was never awaited`.

You can see [here](https://github.com/aio-libs/aiobotocore/blob/fbfeb1242ab1f378f6d4fe84b5d3dacdd8874189/aiobotocore/session.py#L109) that `create_client()` runs `return ClientCreatorContext(self._create_client(*args, **kwargs))` which contains a call to `async def _create_client`, however this is never awaited, and this causes the warning noted above. Everything is functionally working fine for us, however it would be great to get your thoughts on this..

**Replication**
Any code that calls this method should produce this warning.

**Checklist**
- [ ] I have reproduced in environment where `pip check` passes without errors
- [ ] I have provided `pip freeze` results
- [x] I have provided sample code or detailed way to reproduce
- [x] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [x] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**

**Environment:**
 - Python Version: 3.8
 - OS name and version: Ubuntu 20.04 LTS

**Additional context**
n/a

**Comment by thehesiod** [comment]
you need to use a context manager when using aiobotocore per the home page:
```python
    async with session.create_client('s3', region_name='us-west-2',
                                   aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                   aws_access_key_id=AWS_ACCESS_KEY_ID) as client:
```

**Comment by jameseggers** [comment]
> you need to use a context manager when using aiobotocore per the home page:
> 
> ```python
>     async with session.create_client('s3', region_name='us-west-2',
>                                    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
>                                    aws_access_key_id=AWS_ACCESS_KEY_ID) as client:
> ```

Thanks @thehesiod - my mistake, will close this.
