### ISSUE TITLE
As a library, this should not pin to a specific version of botocore or boto3

### ISSUE THREAD

**Issue by tleonhardt** [aio-libs/aiobotocore#971]
As a library, `aiobotocre` should not require a specific version of any of these in the `setup.py`:
- `botocore` 
- `boto3`
- `awscli`

If this were an application, it would be different.  But in order to use this library with a wide variety of other libraries, you want to use `>=` not a combination of `>= and <` which is effectively an `==`.  

I have had to regretfully remove this and things that depend on it from a JupyterHub/JupyterLab system I maintain because it wouldn't allow me to upgrade to the latest version of `botocore` and `boto3` and hence prevented other tools from working properly.

**Comment by mathewlee11** [comment]
Yeah especially with the new pip resolver that fails on conflicts the current setup makes it very difficult to include `aiobotocore` in anything

**Comment by thehesiod** [comment]
this is due to how this module overrides many classes in botocore, please see history: https://github.com/aio-libs/aiobotocore/issues?q=is%3Aissue+is%3Aclosed+pin.  Otherwise we'd need to vendor botocore, which means it wouldn't match the botocore installed next to it.  If you'd like a newer botocore please open a ticket or if you have any other suggestions please feel free to re-open.

**Comment by tleonhardt** [comment]
We'll just tell our customers to use [awswrangler](https://pypi.org/project/awswrangler/) instead so we can stick with sane dependency management.

**Comment by alvaro-ponce** [comment]
Same problem here, it is impossible to install s3fs and boto3 at the same time because of the dependency generated by this strict policy of installing a specific version.
At this point I am forced to do not use s3fs and use awswrangler or create my own s3filesystem handler.

**Comment by bnavigator** [comment]
aiobotocore is about to drop out of openSUSE Tumbleweed because it can't keep up with botocore and boto3

**Comment by thehesiod** [comment]
so ya if it needs to match botocore/boto3 then we'll have to vendor botocore ;(

**Comment by thehesiod** [comment]
I'm not even sure how that would work, because when in botocore it does an import it will need to import from the vendored copy as well, which I think means we have to re-write all the import statements
