### ISSUE TITLE
Integration with moto

### ISSUE THREAD

**Issue by yuvalshi0** [aio-libs/aiobotocore#979]
Hi maintainers,
I've been using `aiobocore` and wanted to mock s3 in my tests, I've you seen under [moto_server.py
](https://github.com/aio-libs/aiobotocore/blob/master/tests/moto_server.py) you actually run a moto service to test your services.
So to my suggesion: why not add it to moto? Or create a new package (i.e. aiobotomoto)?

**Comment by thehesiod** [comment]
I think we have a request to add it as an extra, I'm game if someone comes up with PR :). Or may take me a bit to get to
