### ISSUE TITLE
PutObject fails due to missing x-amz-content-sha256 header

### ISSUE THREAD

**Issue by kamikaze** [aio-libs/aiobotocore#984]
**Describe the bug**
```python
import asyncio
import json

from aiobotocore.session import get_session
from botocore.config import Config


AWS_REGION_NAME = 'eu-north-1'
AWS_ACCESS_KEY_ID = 'xxx'
AWS_SECRET_ACCESS_KEY = 'xxx'
S3_BUCKET_NAME = 'bucket-name'


async def test_aiobotocore3():
    body = json.dumps({'aaa': 'bbb'})
    key = f'test.json'
    session = get_session()

    async with session.create_client('s3',
                                     region_name=AWS_REGION_NAME,
                                     aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
                                     aws_access_key_id=AWS_ACCESS_KEY_ID,
                                     config=Config(signature_version='v4')) as client:
        resp = await client.put_object(Body=body.encode(), Bucket=S3_BUCKET_NAME, Key=key)

        print(resp)


if __name__ == '__main__':
    asyncio.run(test_aiobotocore3())

```
Fails with:
```
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the PutObject operation: Missing required header for this request: x-amz-content-sha256
```

If I remove `config=` part - it failed before about XML issue, but now it worked. Anyway... is there any way to use v4 api? Thanks

**Checklist**
- [ v ] I have reproduced in environment where `pip check` passes without errors
- [ v ] I have provided `pip freeze` results
- [ v ] I have provided sample code or detailed way to reproduce
- [ ] I have tried the same code in botocore to ensure this is an aiobotocore specific issue
- [ ] I have tried similar code in aiohttp to ensure this is is an aiobotocore specific issue
- [ ] I have checked the latest and older versions of aiobotocore/aiohttp/python to see if this is a regression / injection

**pip freeze results**
```
aioboto3==10.1.0
aiobotocore==2.4.0
aiohttp==3.8.3
aioitertools==0.11.0
aiosignal==1.3.1
async-timeout==4.0.2
attrs==22.1.0
boto3==1.24.59
botocore==1.27.59
charset-normalizer==2.1.1
frozenlist==1.3.3
idna==3.4
jmespath==1.0.1
multidict==6.0.2
python-dateutil==2.8.2
s3transfer==0.6.0
six==1.16.0
urllib3==1.26.12
wrapt==1.14.1
yarl==1.8.1
```

**Environment:**
 - Python Version: 3.11
 - OS name and version: Ubuntu Linux 22.04.1 LTS

**Additional context**

**Comment by thehesiod** [comment]
same problem happens with botocore, so not an aiobotocore issue.  I think you need to use s3v4 and not v4.  Otherwise a bug in botocore.  If you find a version that works let me know

**Comment by thehesiod** [comment]
you didn't follow the issue checklist, had you followed it you would have discovered this yourself :)
